### ISSUE TITLE
No top-level directory in tarballs

### ISSUE THREAD

**Issue by tanuk** [alsa-project/alsa-ucm-conf#10]
Usually release tarballs have a top-level directory in the format "&lt;packagename>-&lt;version>". At least the 1.2.1.2 release of alsa-ucm-conf didn't have any such directory, which caused some headache for me as a packager. I figured out how to deal with it, so I don't need this issue fixed, but it would probably still be a good idea to add the conventional directory in future releases.

**Comment by lgirdwood** [comment]
@juimonen can you look at this if ok with @perexg

**Comment by perexg** [comment]
It's in my queue for the next release. For Fedora, I just use this tar ball as another source to alsa-lib, so everything is unpacked to the alsa-lib directory (ucm/topology) and then the packages are build from this tree. But I agree to follow the convention.

**Comment by perexg** [comment]
Fixed in 1.2.2. Thank you for the notice.
