### ISSUE TITLE
Dell platform adding ucm2 conf with generic mic-mute LEDs feature

### ISSUE THREAD

**Issue by GoPerry** [alsa-project/alsa-ucm-conf#105]
As the post-patch did, I would need to add one patch for the dell platform which has enabled the generic mic mute feature.
But I did not see the below paths. 

/sys/class/sound/ctl-led/speaker
/sys/class/sound/ctl-led/mic

https://www.spinics.net/lists/alsa-devel/msg125821.html

**Comment by GoPerry** [comment]
root@dell-Latitude-94xx:/sys/module/snd_ctl_led# ll
total 0
drwxr-xr-x   5 root root    0 Jun 28 04:55 ./
drwxr-xr-x 304 root root    0 Jun 23 21:49 ../
-r--r--r--   1 root root 4096 Jun 28 04:55 coresize
drwxr-xr-x   2 root root    0 Jun 28 04:55 holders/
-r--r--r--   1 root root 4096 Jun 28 04:57 initsize
-r--r--r--   1 root root 4096 Jun 28 04:57 initstate
drwxr-xr-x   2 root root    0 Jun 28 04:57 notes/
-r--r--r--   1 root root 4096 Jun 28 04:55 refcnt
drwxr-xr-x   2 root root    0 Jun 28 04:57 sections/
-r--r--r--   1 root root 4096 Jun 28 04:57 srcversion
-r--r--r--   1 root root 4096 Jun 28 04:57 taint
--w-------   1 root root 4096 Jun 28 04:55 uevent

**Comment by GoPerry** [comment]
snd_ctl_led            24576  0
input_leds             16384  0
ledtrig_audio          16384  4 snd_ctl_led,dell_wmi,snd_sof,dell_laptop

**Comment by GoPerry** [comment]
@perexg @jwrdegoede 

Do I need to add any kernel option to enable the generic mute led ?
Seems like the speaker and mic dirs are not created by default

**Comment by jwrdegoede** [comment]
You are doing a `ll` in `/sys/module/snd_ctl_led`, while you should be doing it in `/sys/class/sound/ctl-led`.

**Comment by GoPerry** [comment]
> You are doing a `ll` in `/sys/module/snd_ctl_led`, while you should be doing it in `/sys/class/sound/ctl-led`.
Thank you Hans!
correct!
I see the mic and speaker dirs now.

**Comment by GoPerry** [comment]
root@dell-Latitude-9420:/sys/devices/virtual/sound/ctl-led/mic# echo "follow mute" > mode
root@dell-Latitude-9420:/sys/devices/virtual/sound/ctl-led/mic# ls
brightness  card0  mode  power  uevent
root@dell-Latitude-9420:/sys/devices/virtual/sound/ctl-led/mic# cat mode 
follow-mute
root@dell-Latitude-9420:/sys/devices/virtual/sound/ctl-led/mic# cat brightness 
1
root@dell-Latitude-9420:/sys/devices/virtual/sound/ctl-led/mic# cat brightness 
1
root@dell-Latitude-9420:/sys/devices/virtual/sound/ctl-led/mic# cat brightness 
1

did some testing with the ctl-led loaded, the brightsness value is not changed when switching mute/unmute state

**Comment by GoPerry** [comment]
another problem is that the snd-ctl-led module is not loaded after i add the patch.
Do i need to update alsa-lib ?

**Comment by GoPerry** [comment]
@jwrdegoede  @perexg 
Could you help to comment this .
1. the mic and speaker brightness are not changed when switch mic/spk mute state.
2. snd-ctl-led is not loaded automatically after the rt715-sdca/init.conf  updated to latest

**Comment by perexg** [comment]
@GoPerry : You should add configuration like https://www.spinics.net/lists/alsa-devel/msg125821.html to the UCM card. It loads the kernel module and attaches the selected ALSA controls for the LED trigger.

**Comment by GoPerry** [comment]
root@dell-Latitude-xx0:/sys/class/sound/ctl-led/mic/card0# echo "ADC Capture Switch" > attach 
bash: echo: write error: No such file or directory

root@dell-Latitude-xx0:/sys/class/sound/ctl-led/mic/card0# ls
attach  card  detach  list  power  reset  uevent 

It is weird that the  attach file cannot  be written by this command.

**Comment by perexg** [comment]
Try `echo -n  "ADC Capture Switch" > attach` .

**Comment by perexg** [comment]
Also, the control should exists. Use `amixer -c 0 controls` to get list of controls. Perhaps, you want to attach another one.

**Comment by GoPerry** [comment]
root@dell-Latitude-9420:/sys/class/sound/ctl-led/mic# ls
brightness  card0  mode  power  uevent
root@dell-Latitude-9420:/sys/class/sound/ctl-led/mic# cat brightness 
0
root@dell-Latitude-9420:/sys/class/sound/ctl-led/mic# cat brightness 
1
root@dell-Latitude-9420:/sys/class/sound/ctl-led/mic# cat brightness 
0
root@dell-Latitude-9420:/sys/class/sound/ctl-led/mic# cat brightness 
1


It works for me now  with right kcontrol.

**Comment by GoPerry** [comment]
then the only prolem need to resolve is the ucm2  loading snd_ctl_led.

FixedBootSequence [
	exec "-/sbin/modprobe snd_ctl_led"
	sysw "-/class/sound/chctl-led/mic/card${CardNumber}/attach:rt714 FU02 Capture Switch"
]

I would like to check where the alsa code will  call the FixedBootSequence ?

**Comment by GoPerry** [comment]
Is it the alsa-lib will trigger the FixedBootSequence ?

**Comment by GoPerry** [comment]
if alsa-lib trigger the FixedBootSequence, then i would need to upgrade the alsa-lib

**Comment by perexg** [comment]
You need 1.2.5 alsa-lib and alsa-utils packages. The fixed boot sequence is called from the `alsactl` utility (invoked via systemd/udev rules).

**Comment by perexg** [comment]
> sysw "-/class/sound/chctl-led/mic/card${CardNumber}/attach:rt714 FU02 Capture Switch"

Typo? It should be `class/sound/ctl-led/...`.

**Comment by jwrdegoede** [comment]
Note there also is an selinux issue where selinux is blocking alsactl from doing the modprobe:

https://bugzilla.redhat.com/show_bug.cgi?id=1958210

Try setting enforcing=0 on the kernel commandline as a workaround for now.

**Comment by GoPerry** [comment]
> Note there also is an selinux issue where selinux is blocking alsactl from doing the modprobe:
> 
> https://bugzilla.redhat.com/show_bug.cgi?id=1958210
> 
> Try setting enforcing=0 on the kernel commandline as a workaround for now.

Thank you Hans, let me try disable the selinux

**Comment by GoPerry** [comment]
> > sysw "-/class/sound/chctl-led/mic/card${CardNumber}/attach:rt714 FU02 Capture Switch"
> 
> Typo? It should be `class/sound/ctl-led/...`.

yeah, typo, the touchpad corrupting the input method.
