### ISSUE TITLE
kbl-r5514-5663-max Headphone does not work

### ISSUE THREAD

**Issue by jmontleon** [alsa-project/alsa-ucm-conf#108]
On a Pixelbook I have copied these firmware files in place:
- /opt/google/dsm/dsmparam.bin
- /lib/firmware/9d71-GOOGLE-EVEMAX-0-tplg.bin
- /lib/firmware/dsp_lib_dsm_core_spt_release.bin
- /lib/firmware/intel/dsp_fw_C75061F3-F2B2-4DCC-8F9F-82ABB4131E66.bin

With that alone the speakers started working after a reboot.

I have been trying to modify the ucm HiFi.conf to ucm2 on Fedora. If I comment out all of `SectionDevice."Headphones"` the speakers and internal microphone work. If I leave it I see a bunch of error messages in dmesg. Pulseaudio also produces some error messages and then just loads a dummy device.

dmesg:
```
[ 7866.107942]  Kbl Audio Headset Playback: ASoC: no backend DAIs enabled for Kbl Audio Headset Playback
[ 7866.107950]  Kbl Audio Headset Playback: ASoC: dpcm_fe_dai_prepare() failed (-22)
```

pulseaudio:
```
D: [pulseaudio] alsa-util.c: Maximum hw buffer size is 21845 ms
I: [pulseaudio] (alsa-lib)pcm_hw.c: SNDRV_PCM_IOCTL_PREPARE failed (-22)
I: [pulseaudio] (alsa-lib)pcm_hw.c: SNDRV_PCM_IOCTL_PREPARE failed (-22)
I: [pulseaudio] (alsa-lib)pcm_hw.c: SNDRV_PCM_IOCTL_PREPARE failed (-22)
I: [pulseaudio] (alsa-lib)pcm_hw.c: SNDRV_PCM_IOCTL_PREPARE failed (-22)
D: [pulseaudio] alsa-util.c: Set neither period nor buffer size.
I: [pulseaudio] (alsa-lib)pcm_hw.c: SNDRV_PCM_IOCTL_PREPARE failed (-22)
I: [pulseaudio] alsa-util.c: snd_pcm_hw_params failed: Invalid argument
D: [pulseaudio] alsa-util.c: Trying plug:_ucm0006.hw:kblr55145663max,2 with SND_PCM_NO_AUTO_FORMAT ...
I: [pulseaudio] (alsa-lib)conf.c: Unknown parameter 1
I: [pulseaudio] (alsa-lib)conf.c: Parse arguments error: No such file or directory
I: [pulseaudio] (alsa-lib)pcm.c: Unknown PCM plug:_ucm0006.hw:kblr55145663max,2
I: [pulseaudio] alsa-util.c: Error opening PCM device plug:_ucm0006.hw:kblr55145663max,2: No such file or directory
D: [pulseaudio] alsa-mixer.c: Profile set 0x555cededf730, auto_profiles=no, probed=yes, n_mappings=0, n_profiles=0, n_decibel_fixes=0
E: [pulseaudio] module-alsa-card.c: Failed to find a working profile.
E: [pulseaudio] module.c: Failed to load module "module-alsa-card" (argument: "device_id="0" name="platform-kbl_r5514_5663_max" card_name="alsa_card.platform-kbl_r5514_5663_max" namereg_fail=false tsched=yes fixed_latency_range=no ignore_dB=no deferred_volume=yes use_ucm=yes avoid_resampling=no card_properties="module-udev-detect.discovered=1""): initialization failed.
I: [pulseaudio] module-udev-detect.c: Card /devices/platform/kbl_r5514_5663_max/sound/card0 (alsa_card.platform-kbl_r5514_5663_max) failed to load module.
```

From reading I gather there's probably some routing incorrectly or incompletely set up that is the cause, but I'm at a bit of a loss on where to go from here.

I saw a suggestion somewhere to set this module option, but as far as I can tell it makes no difference:
```
cat /etc/modprobe.d/dsp.conf 
options snd_intel_dspcfg dsp_driver=2
```

Not really an alsa / ucm problem as far as I am aware but in the interest of giving as much info as possible I originally switched to pulseaudio because I had an easier time finding meaningful logs. I switched back to pipewire later to realize the mic is just producing awful noise so I went back to pulseaudio for the time being. Might need to file a pipewire bug later.

The HiFi.conf and alsa-info are attached.

[alsa-info.txt](https://github.com/alsa-project/alsa-ucm-conf/files/6870590/alsa-info.txt)
[Hifi.conf.txt](https://github.com/alsa-project/alsa-ucm-conf/files/6870593/Hifi.conf.txt)

**Comment by plbossart** [comment]
````
[ 7866.107942]  Kbl Audio Headset Playback: ASoC: no backend DAIs enabled for Kbl Audio Headset Playback
````
is a clear sign that the patch from your PCM device to the endpoint selected is missing an ALSA mixer configuration, typically a 'Switch' setting

In the past there was a confusion between mute and switch, it could be that you have an inversion in your settings. Switch On means the path is enabled or audio is NOT muted.

**Comment by jmontleon** [comment]
OK. I flipped a couple Switch options from off to on in the `SectionVerb` `EnableSequence`. I'll try to find a pair of headphones in the house somewhere now and if it works narrow down which of the two did it. Thank you!

**Comment by jmontleon** [comment]
I confirmed the headset audio and microphone work after switch `cset “name=‘codec1_out mo hs_pb_in mi Switch’ off”` to `cset “name=‘codec1_out mo hs_pb_in mi Switch’ on”`.

Thank you again!

**Comment by plbossart** [comment]
That's the one I was thinking about. I don't know why it was set to off. It's enough for power management to turn the endpoints pins on/off but leave all the internal circuits inside the Intel DSP on by default.
Glad you're in business.

**Comment by perexg** [comment]
Can someone clarify the change which should be merged to the UCM configuration files ?

@plbossart : It's just one machine specific thing or we can do this change for all kbl-r5514-5663-max hardware types ?

**Comment by plbossart** [comment]
@perexg I don't see any upstream UCM file that manages this platform. Likely still in Chrome-only overlays?

**Comment by perexg** [comment]
Thanks @plbossart . I see. So it's not an upstream request. Closing for now.
