### ISSUE TITLE
No support for Kaby Lake DA7219 (on Chromebooks)

### ISSUE THREAD

**Issue by FantasyCookie17** [alsa-project/alsa-ucm-conf#11]
I'm sorry if this is the wrong page and the bug tracking mailing list would be better, or if this is the wrong part of the ALSA project, however this seems indeed related to ALSA UCM configuration. The original issue is [here](https://github.com/GalliumOS/galliumos-distro/issues/536), however OP and developers did not seem to care or know what to do, so I wondered whether a fixed version of this could be put into the standard ALSA configuration. The support in the kernel seems to be there, at least theoretically. The firmware might be adopted into alsa-firmware, if it is actually needed.

**Comment by FantasyCookie17** [comment]
Seems like this MAY be unnecessary, as it is already being worked on [hre](https://github.com/thesofproject/sof/issues/1899).

**Comment by lgirdwood** [comment]
@FantasyCookie17 your right, we are discussing this on  https://github.com/thesofproject/sof/issues/1899 I will close this duplicate but feel free to add any extra information you have to #1899.
