### ISSUE TITLE
only have sound after mute and unmute and set volume in alsamixer

### ISSUE THREAD

**Issue by amazingfate** [alsa-project/alsa-ucm-conf#113]
I have a x86 thinclient with debian bullseye installed. It has no sound in my headphone after boot, but I open alsamixer and then:
1, press M to mute the master
2, press M again to unmute the master
3, change the master volume from 100 to 99
After the above three steps I can hear the sound from my headphone.
Here is the alsainfo before and after the three steps:
[alsa-info_nosound.txt](https://github.com/alsa-project/alsa-ucm-conf/files/7452255/alsa-info_nosound.txt)
[alsa-info_sound.txt](https://github.com/alsa-project/alsa-ucm-conf/files/7452258/alsa-info_sound.txt)

I can see the difference in "Amp-Out vals".

**Comment by perexg** [comment]
It's unlikely an UCM issue. Please, create a kernel audio driver bug at https://bugzilla.kernel.org .
