### ISSUE TITLE
UCM can't match the USB device ID in Ubuntu 20.04

### ISSUE THREAD

**Issue by shumingfan** [alsa-project/alsa-ucm-conf#119]
We created the UCM2 conf files and used the 'components' string to match the right UCM config.
Unfortunately, the system can't apply the right UCM config.

The test files and alsa-lib version shows below.
USB-Audio.conf
https://github.com/perexg/alsa-ucm-conf/commit/e3517b1cbb4ac0c69496329eeb15dc6bd4ed3a13
Dell-Desktop UCM2 files
https://github.com/shumingfan/alsa-ucm-conf/commit/16dce692843b05d9cd720ddae1e790c26881d47e
$ alsaucm --version
alsaucm: version 1.2.2

Is it possible to resolve this problem when using alsa-lib-1.2.2?

**Comment by perexg** [comment]
Could you show me /usr/share/alsa/ucm2/ucm.conf file ? (Use distgist or pastebin and put a link here.)

Also, show output from `alsaucm -c hw:CARDNO set _verb HiFi` .

**Comment by shumingfan** [comment]
Please check the following link where I put the content of ucm.conf.
https://pastebin.com/raw/8D2bJtVR

Card 1 is front UAC and card 2 is rear UAC.
I already used the new USB-Audio.conf before I input alsaucm command.

shuming@Latitude-5410: $ alsaucm -c hw:1 set _verb HiFi
ALSA lib parser.c:1836:(parse_master_file) Incompatible syntax 4 in USB-Audio.conf
ALSA lib main.c:1014:(snd_use_case_mgr_open) error: failed to import hw:1 use case configuration -22
alsaucm: error failed to open sound card hw:1: Invalid argument
shuming@Latitude-5410: $ alsaucm -c hw:2 set _verb HiFi
ALSA lib parser.c:1836:(parse_master_file) Incompatible syntax 4 in USB-Audio.conf
ALSA lib main.c:1014:(snd_use_case_mgr_open) error: failed to import hw:2 use case configuration -22
alsaucm: error failed to open sound card hw:2: Invalid argument

**Comment by perexg** [comment]
Try to change 'Syntax 4' to 'Syntax 3' in USB-Audio.conf . The ucm.conf file should be fine.

**Comment by shumingfan** [comment]
It works after changing Syntax 4 to Syntax 3 in USB-Audio.conf. Thanks a lot.

**Comment by perexg** [comment]
Ok, please, create a new pull request with your dell desktop changes and add my USB-Audio.conf there. From the first glance, your configuration is missing the hardware volume control (missing mixer element specification and initialization).

**Comment by shumingfan** [comment]
@perexg @jason77-wang Thanks. I added the mixer element for headphone/speaker/line-out.
A new pull request #120 had been submitted.

**Comment by perexg** [comment]
The PR#120 will resolve this issue.
