### ISSUE TITLE
Support for TC-Helicon GoXLR

### ISSUE THREAD

**Issue by Toniob** [alsa-project/alsa-ucm-conf#121]
Hi,

I’m the owner of a GoXLR : https://www.tc-helicon.com/product.html?modelCode=P0CQK . It is a usb sound mixer that is not supported officially with Linux. The main issue is that the GoXLR is a multi inputs / multi outputs device, but it is not seen as one. It works great under Windows thanks to a driver. With Linux, it is seen as a single usb sound device with a single multichannel output. Right now, I managed with other people to separate those channels with pulseaudio or jack or even pipewire, using loopback modules for example. For exemple, Front Left and Front Right are the stereo output named "System". Rear left and rear right are another stereo output named "Game". There are other outputs, and it is the same mechanism for the inputs.

I opened an issue on pipewire, but someone told me it wasn’t possible to separate the in/outputs with a profile : https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1787 .

I then wondered if it was possible with a kernel quirk, which I asked : https://bugzilla.kernel.org/show_bug.cgi?id=215035 .

I was adviced to open a ticket here. So here I am. Do you think it would be possible to create a profile for my device ?

[alsa-info.txt](https://github.com/alsa-project/alsa-ucm-conf/files/7553207/alsa-info.txt)
[pipewire.conf.txt](https://github.com/alsa-project/alsa-ucm-conf/files/7553220/pipewire.conf.txt)

**Comment by perexg** [comment]
I created a test configuration for one stereo stream at https://github.com/perexg/alsa-ucm-conf/commit/goxlr (patch URL: https://github.com/perexg/alsa-ucm-conf/commit/goxlr.patch).

Please, get the latest alsa-ucm-conf from this repo, pull / unpack it somewhere and redirect (symlink) /usr/share/alsa/ucm2 to the unpacked ucm2 tree (backup/rename the original /usr/share/alsa/ucm2 tree). Also, apply the above patch.

Let me know, if the Speaker / System device is detected, eventually show me the PW log.

**Comment by Toniob** [comment]
I did it but when I do so, I don’t have the output anymore.

[pw-dump.txt](https://github.com/alsa-project/alsa-ucm-conf/files/7569075/pw-dump.txt)
[spa-acp-tool.txt](https://github.com/alsa-project/alsa-ucm-conf/files/7569076/spa-acp-tool.txt)
![Capture d’écran de 2021-11-19 09-54-04](https://user-images.githubusercontent.com/113461/142596469-ca9e8499-39e0-4871-9a56-96bba55a11bb.png)
![Capture d’écran de 2021-11-19 09-54-32](https://user-images.githubusercontent.com/113461/142596473-24414f25-64df-4376-a48f-3df36ecb8f3f.png)

**Comment by perexg** [comment]
Thanks, the spa-acp-tool output is sufficient. Could you show me output from `alsaucm -c hw:2 get _alibcfg` ?

**Comment by Toniob** [comment]
Here it is
[alsaucm.txt](https://github.com/alsa-project/alsa-ucm-conf/files/7569599/alsaucm.txt)

**Comment by perexg** [comment]
Also `alsaucm -c hw:2 dump text` ?

**Comment by Toniob** [comment]
Here is the dump
[alsaucm_dump.txt](https://github.com/alsa-project/alsa-ucm-conf/files/7569707/alsaucm_dump.txt)

If I do add Syntax 4 as the first line of the file, I now have a warning
`ALSA lib parser.c:2107:(parse_master_file) unknown master file field Syntax`
Is it expected ?

For the following tests, is there a way to reload the ucm configuration without rebooting ?

**Comment by perexg** [comment]
> Here is the dump [alsaucm_dump.txt](https://github.com/alsa-project/alsa-ucm-conf/files/7569707/alsaucm_dump.txt)
> 
> If I do add Syntax 4 as the first line of the file, I now have a warning `ALSA lib parser.c:2107:(parse_master_file) unknown master file field Syntax` Is it expected ?

Ahh. OK. The syntax cannot be changed. Please, modify `Syntax 3` to `Syntax 4` in USB-Audio/USB-Audio.conf .

> For the following tests, is there a way to reload the ucm configuration without rebooting ?

It should be enough to restart pipewire / run acp tool or alsaucm.

**Comment by Toniob** [comment]
It works with `Syntax 4` moved to the USB-Audio.conf file. I’ve got the output showing in Gnome settings and I can play audio.

[alsaucm_dump.txt](https://github.com/alsa-project/alsa-ucm-conf/files/7569851/alsaucm_dump.txt)
[alsaucm_cfg.txt](https://github.com/alsa-project/alsa-ucm-conf/files/7569852/alsaucm_cfg.txt)

**Comment by perexg** [comment]
OK, now it's the time to analyze the channel / output jack mapping. What output jack is connected to first two channels?

In configuration, look for the two bindings lines:

```
bindings.0 0
bindings.1 1
```

Change just the second value (like `bindings.0 2` `bindings.1 3` and so on - test and describe the used stereo output. I'll add missing devices.

**Comment by Toniob** [comment]
You have the corresponding outputs in my pipewire.conf file in the first message
0 1 : System
2 3 : Game
4 5 : Music
6 7 : Voice Chat
8 9 : Sample

Thanks a lot for your work. It helps a lot.

**Comment by perexg** [comment]
I updated https://github.com/perexg/alsa-ucm-conf/commit/goxlr for playback.

**Comment by Toniob** [comment]
Thanks. It is not working currently. Here is my last working GoXLR-HiFi.conf file.
[GoXLR-HiFi.conf.txt](https://github.com/alsa-project/alsa-ucm-conf/files/7570427/GoXLR-HiFi.conf.txt)

I changed the bindings to 8 and 9 for Sample, not 10 and 11. But it doesn’t change the fact that the moment I uncomment one more Sectiondevice part, it isn’t working anymore. With only one sectiondevice
[spa-1sectiondevice.txt](https://github.com/alsa-project/alsa-ucm-conf/files/7570442/spa-1sectiondevice.txt)
It is ok and I can use my output in Gnome Settings.

With 2 or more uncommented
[spa-2sectiondevice.txt](https://github.com/alsa-project/alsa-ucm-conf/files/7570450/spa-2sectiondevice.txt)
And my outputs, even the system one, totally disappear.

**Comment by Toniob** [comment]
You’re right, it got 10 channels : FL, FR, RL, RR, SL, SR, FC, LFE, AUX0, AUX1. I tried your new patch, but it still not working. In fact, the moment I uncomment something else than the System sectiondevice, it doesn’t work anymore.
[spa.txt](https://github.com/alsa-project/alsa-ucm-conf/files/7570542/spa.txt)

Also, is there something to force 48khz and s32le to get rid of this
```
Device goxlr_system:GoXLR doesn't support 44100 Hz, changed to 48000 Hz.
Device goxlr_system:GoXLR doesn't support sample format s16le, changed to s32le.
```

**Comment by perexg** [comment]
I updated https://github.com/perexg/alsa-ucm-conf/commit/goxlr again. The channels settings were at the wrong place.

**Comment by Toniob** [comment]
It works ! Wonderful ! Thank you so much.
[spa.txt](https://github.com/alsa-project/alsa-ucm-conf/files/7570621/spa.txt)

One mistake from my side. Maybe somewhere pipewire and ucm differs in naming the outputs. But Voice chat and music are inverted. Music should be 6 and 7 and Voice is 4 and 5.
I think System should be the output with the priority (you put sample). And I still have the sample and rate warning.

Can we now try with the inputs ?

**Comment by Toniob** [comment]
Can you please also add this usb id : 1220:8FE4 , which is another version of the GoXLR (the Mini version but it works the same) ? Thanks

**Comment by perexg** [comment]
I updated https://github.com/perexg/alsa-ucm-conf/commit/goxlr again. I simplified playback (needs verification) and added capture (input). I don't know how many channels the PCM capture device has. It should be tweaked in the config. Also, the mono mic channel is not readable from the pipewire config. I expect errors somewhere.

**Comment by Toniob** [comment]
Thanks a lot again. It works if I take off the Mono mic. But I checked on windows, and this input isn’t present. I changed your file to make the names the same as Windows. What do you think ?

[GoXLR-HiFi.conf.txt](https://github.com/alsa-project/alsa-ucm-conf/files/7572168/GoXLR-HiFi.conf.txt)

**Comment by Toniob** [comment]
Damn ! Another issue. Everything is working fine with a kernel 5.10 (which I was using for the tests). But if I reboot to the same system but with a kernel 5.14, the profile is gone. There is only the "off" profile available. Do you have an idea ?

[spa-5.14.txt](https://github.com/alsa-project/alsa-ucm-conf/files/7572311/spa-5.14.txt)

The fact is, I don’t have sound working on a 5.14 kernel even when I don’t use this new ucm profile. The multichannel stays mute. So it’s not because of what we’ve done, I had the problem before. But I was hoping it will solve this issue.

**Comment by perexg** [comment]
Report this in the kernel's bugzilla: https://bugzilla.kernel.org . It appears like a kernel bug:

```
Trying _ucm0001.goxlr_sample_input:GoXLR with SND_PCM_NO_AUTO_FORMAT ...
snd_pcm_hw_params_any failed
unable to initialize slave
Error opening PCM device _ucm0001.goxlr_sample_input:GoXLR: Invalid argument
```

It's better to test the input using `arecord` or any other simple application.

**Comment by Toniob** [comment]
The bug is reported : https://bugzilla.kernel.org/show_bug.cgi?id=215079

Thanks again for your kind help.
