### ISSUE TITLE
No audio from Starship/Matisse HD Audio Controller

### ISSUE THREAD

**Issue by ljmc2000** [alsa-project/alsa-ucm-conf#129]
I have an AMD ryzen 3900X paired with a Gigabyte AX370-Gaming 5 motherboard. I use arch linux. Upon upgrading the package alsa-ucm-conf from version 1.2.6.1-1 to 1.2.6.2-2 and rebooting, my onboard audio stops working completely. Downgrading restores functionality after another reboot. In pavucontrol, for 1.2.6.1-1 there are many available profiles, but for 1.2.6.2-2 there is only one, which says unavailable. I also use pipewire rather than pulseaudio if that makes a difference

**Comment by perexg** [comment]
Please, show output from `alsa-info.sh --no-upload` (attach or post URL to gist / pastebin) and `alsa-info.sh -c hw:0` (replace eventually 0 with the correct ALSA card number - `aplay -l` will give hints). Thank you.

**Comment by SirFooOfBar** [comment]
alsaucm -c hw:0 dump text
ALSA lib main.c:1412:(snd_use_case_mgr_open) error: failed to import hw:0 use case configuration -2
alsaucm: error failed to open sound card hw:0: No such file or directory

as for alsa-info.sh
https://gist.github.com/SirFooOfBar/c5d5e4358da417902e97e37258b02677

**Comment by perexg** [comment]
Thanks, the right card is 2: `alsaucm -c hw:2 dump text` . Please, provide output from this command.

**Comment by SirFooOfBar** [comment]
for i in 0 1 2 3; do alsaucm -c hw:$i dump text; done
ALSA lib main.c:1412:(snd_use_case_mgr_open) error: failed to import hw:0 use case configuration -2
alsaucm: error failed to open sound card hw:0: No such file or directory
ALSA lib main.c:1412:(snd_use_case_mgr_open) error: failed to import hw:1 use case configuration -2
alsaucm: error failed to open sound card hw:1: No such file or directory
ALSA lib main.c:1412:(snd_use_case_mgr_open) error: failed to import hw:2 use case configuration -2
alsaucm: error failed to open sound card hw:2: No such file or directory
ALSA lib main.c:1412:(snd_use_case_mgr_open) error: failed to import hw:3 use case configuration -2
alsaucm: error failed to open sound card hw:3: No such file or directory

**Comment by perexg** [comment]
Thanks. Please, output from `strace alsaucm -c hw:2 dump text` . Thank you.

**Comment by SirFooOfBar** [comment]
strace alsaucm -c hw:2 dump text
execve("/usr/bin/alsaucm", ["alsaucm", "-c", "hw:2", "dump", "text"], 0x7ffd8e5e41a0 /* 95 vars */) = 0
brk(NULL)                               = 0x557e66420000
arch_prctl(0x3001 /* ARCH_??? */, 0x7fffc9580f80) = -1 EINVAL (Invalid argument)
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=286844, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 286844, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f18a1625000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/libasound.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0 \320\2\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=944560, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f18a1623000
mmap(NULL, 947568, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f18a153b000
mmap(0x7f18a1568000, 540672, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2d000) = 0x7f18a1568000
mmap(0x7f18a15ec000, 188416, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xb1000) = 0x7f18a15ec000
mmap(0x7f18a161a000, 36864, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xde000) = 0x7f18a161a000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\300\200\0\0\0\0\0\0"..., 832) = 832
pread64(3, "\4\0\0\0@\0\0\0\5\0\0\0GNU\0\2\0\0\300\4\0\0\0\3\0\0\0\0\0\0\0"..., 80, 792) = 80
pread64(3, "\4\0\0\0\24\0\0\0\3\0\0\0GNU\0\7\310\371[O2Q\320\205P!z\330\241\363\20"..., 68, 872) = 68
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=154040, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 131472, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f18a151a000
mprotect(0x7f18a1521000, 81920, PROT_NONE) = 0
mmap(0x7f18a1521000, 61440, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x7000) = 0x7f18a1521000
mmap(0x7f18a1530000, 16384, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x16000) = 0x7f18a1530000
mmap(0x7f18a1535000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1a000) = 0x7f18a1535000
mmap(0x7f18a1537000, 12688, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f18a1537000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0`|\2\0\0\0\0\0"..., 832) = 832
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
pread64(3, "\4\0\0\0@\0\0\0\5\0\0\0GNU\0\2\0\0\300\4\0\0\0\3\0\0\0\0\0\0\0"..., 80, 848) = 80
pread64(3, "\4\0\0\0\24\0\0\0\3\0\0\0GNU\0K@g7\5w\10\300\344\306B4Zp<G"..., 68, 928) = 68
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=2150424, ...}, AT_EMPTY_PATH) = 0
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
mmap(NULL, 1880536, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f18a134e000
mmap(0x7f18a1374000, 1355776, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x26000) = 0x7f18a1374000
mmap(0x7f18a14bf000, 311296, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x171000) = 0x7f18a14bf000
mmap(0x7f18a150b000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1bc000) = 0x7f18a150b000
mmap(0x7f18a1511000, 33240, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f18a1511000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/libm.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\260\363\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=1323472, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 1323032, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f18a120a000
mprotect(0x7f18a1219000, 1257472, PROT_NONE) = 0
mmap(0x7f18a1219000, 630784, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xf000) = 0x7f18a1219000
mmap(0x7f18a12b3000, 622592, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xa9000) = 0x7f18a12b3000
mmap(0x7f18a134c000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x141000) = 0x7f18a134c000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0000\"\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=22704, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 24720, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f18a1203000
mmap(0x7f18a1205000, 8192, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7f18a1205000
mmap(0x7f18a1207000, 4096, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x4000) = 0x7f18a1207000
mmap(0x7f18a1208000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x4000) = 0x7f18a1208000
close(3)                                = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f18a1201000
arch_prctl(ARCH_SET_FS, 0x7f18a1202480) = 0
mprotect(0x7f18a150b000, 12288, PROT_READ) = 0
mprotect(0x7f18a1208000, 4096, PROT_READ) = 0
mprotect(0x7f18a134c000, 4096, PROT_READ) = 0
mprotect(0x7f18a1535000, 4096, PROT_READ) = 0
mprotect(0x7f18a161a000, 32768, PROT_READ) = 0
mprotect(0x557e657bf000, 4096, PROT_READ) = 0
mprotect(0x7f18a169a000, 8192, PROT_READ) = 0
munmap(0x7f18a1625000, 286844)          = 0
set_tid_address(0x7f18a1202750)         = 3809
set_robust_list(0x7f18a1202760, 24)     = 0
rt_sigaction(SIGRTMIN, {sa_handler=0x7f18a1521b70, sa_mask=[], sa_flags=SA_RESTORER|SA_SIGINFO, sa_restorer=0x7f18a152d870}, NULL, 8) = 0
rt_sigaction(SIGRT_1, {sa_handler=0x7f18a1521c10, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART|SA_SIGINFO, sa_restorer=0x7f18a152d870}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
prlimit64(0, RLIMIT_STACK, NULL, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
brk(NULL)                               = 0x557e66420000
brk(0x557e66441000)                     = 0x557e66441000
futex(0x7f18a1622260, FUTEX_WAKE_PRIVATE, 2147483647) = 0
newfstatat(AT_FDCWD, "/usr/share/alsa/alsa.conf", {st_mode=S_IFREG|0644, st_size=10119, ...}, 0) = 0
openat(AT_FDCWD, "/usr/share/alsa/alsa.conf", O_RDONLY) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=10119, ...}, AT_EMPTY_PATH) = 0
read(3, "#\n#  ALSA library configuration "..., 4096) = 4096
read(3, "mehint.extended\n\t\t}\n\t\tdescriptio"..., 4096) = 4096
read(3, "ace\n#\n\nhwdep.default {\n\ttype hw\n"..., 4096) = 1927
read(3, "", 4096)                       = 0
close(3)                                = 0
futex(0x7f18a1209048, FUTEX_WAKE_PRIVATE, 2147483647) = 0
access("/var/lib/alsa/conf.d", R_OK)    = -1 ENOENT (No such file or directory)
access("/usr/etc/alsa/conf.d", R_OK)    = -1 ENOENT (No such file or directory)
access("/etc/alsa/conf.d", R_OK)        = 0
newfstatat(AT_FDCWD, "/etc/alsa/conf.d", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
openat(AT_FDCWD, "/etc/alsa/conf.d", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 3
newfstatat(3, "", {st_mode=S_IFDIR|0755, st_size=4096, ...}, AT_EMPTY_PATH) = 0
getdents64(3, 0x557e664326c0 /* 13 entries */, 32768) = 480
getdents64(3, 0x557e664326c0 /* 0 entries */, 32768) = 0
close(3)                                = 0
openat(AT_FDCWD, "/etc/alsa/conf.d/10-samplerate.conf", O_RDONLY) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=429, ...}, AT_EMPTY_PATH) = 0
read(3, "pcm.samplerate {\n\t@args [ SLAVE "..., 4096) = 429
read(3, "", 4096)                       = 0
close(3)                                = 0
openat(AT_FDCWD, "/etc/alsa/conf.d/10-speexrate.conf", O_RDONLY) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=424, ...}, AT_EMPTY_PATH) = 0
read(3, "pcm.speexrate {\n\t@args [ SLAVE R"..., 4096) = 424
read(3, "", 4096)                       = 0
close(3)                                = 0
openat(AT_FDCWD, "/etc/alsa/conf.d/50-arcam-av-ctl.conf", O_RDONLY) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=222, ...}, AT_EMPTY_PATH) = 0
read(3, "ctl.arcam_av {\n\t@args [ PORT ]\n\t"..., 4096) = 222
read(3, "", 4096)                       = 0
close(3)                                = 0
openat(AT_FDCWD, "/etc/alsa/conf.d/50-jack.conf", O_RDONLY) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=264, ...}, AT_EMPTY_PATH) = 0
read(3, "pcm.jack {\n\ttype jack\n\tplayback_"..., 4096) = 264
read(3, "", 4096)                       = 0
close(3)                                = 0
openat(AT_FDCWD, "/etc/alsa/conf.d/50-oss.conf", O_RDONLY) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=328, ...}, AT_EMPTY_PATH) = 0
read(3, "pcm.oss {\n\t@args [ DEVICE ]\n\t@ar"..., 4096) = 328
read(3, "", 4096)                       = 0
close(3)                                = 0
openat(AT_FDCWD, "/etc/alsa/conf.d/50-pipewire.conf", O_RDONLY) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=1031, ...}, AT_EMPTY_PATH) = 0
read(3, "# Add a specific named PipeWire "..., 4096) = 1031
read(3, "", 4096)                       = 0
close(3)                                = 0
openat(AT_FDCWD, "/etc/alsa/conf.d/50-pulseaudio.conf", O_RDONLY) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=402, ...}, AT_EMPTY_PATH) = 0
read(3, "# Add a specific named PulseAudi"..., 4096) = 402
read(3, "", 4096)                       = 0
close(3)                                = 0
openat(AT_FDCWD, "/etc/alsa/conf.d/60-speex.conf", O_RDONLY) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=1030, ...}, AT_EMPTY_PATH) = 0
read(3, "pcm.speex {\n\t@args [ SLAVE AGC A"..., 4096) = 1030
read(3, "", 4096)                       = 0
close(3)                                = 0
openat(AT_FDCWD, "/etc/alsa/conf.d/60-upmix.conf", O_RDONLY) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=389, ...}, AT_EMPTY_PATH) = 0
read(3, "pcm.upmix {\n\t@args [ SLAVE CHANN"..., 4096) = 389
read(3, "", 4096)                       = 0
close(3)                                = 0
openat(AT_FDCWD, "/etc/alsa/conf.d/60-vdownmix.conf", O_RDONLY) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=393, ...}, AT_EMPTY_PATH) = 0
read(3, "pcm.vdownmix {\n\t@args [ SLAVE CH"..., 4096) = 393
read(3, "", 4096)                       = 0
close(3)                                = 0
openat(AT_FDCWD, "/etc/alsa/conf.d/99-pipewire-default.conf", O_RDONLY) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=226, ...}, AT_EMPTY_PATH) = 0
read(3, "pcm.!default {\n    type pipewire"..., 4096) = 226
read(3, "", 4096)                       = 0
close(3)                                = 0
access("/etc/asound.conf", R_OK)        = -1 ENOENT (No such file or directory)
access("/usr/etc/asound.conf", R_OK)    = -1 ENOENT (No such file or directory)
access("/home/pi/.asoundrc", R_OK)      = 0
newfstatat(AT_FDCWD, "/home/pi/.asoundrc", {st_mode=S_IFREG|0644, st_size=0, ...}, 0) = 0
openat(AT_FDCWD, "/home/pi/.asoundrc", O_RDONLY) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=0, ...}, AT_EMPTY_PATH) = 0
read(3, "", 4096)                       = 0
close(3)                                = 0
access("/home/pi/.config/alsa/asoundrc", R_OK) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/dev/snd/controlC2", O_RDONLY|O_CLOEXEC) = 3
ioctl(3, SNDRV_CTL_IOCTL_CARD_INFO, 0x7fffc9580570) = 0
close(3)                                = 0
openat(AT_FDCWD, "/dev/snd/controlC2", O_RDWR|O_CLOEXEC) = 3
ioctl(3, SNDRV_CTL_IOCTL_PVERSION, 0x7fffc9580954) = 0
ioctl(3, SNDRV_CTL_IOCTL_CARD_INFO, 0x7fffc9580b10) = 0
access("/usr/share/alsa/ucm2/ucm.conf", R_OK) = 0
openat(AT_FDCWD, "/usr/share/alsa/ucm2/ucm.conf", O_RDONLY) = 10
newfstatat(10, "", {st_mode=S_IFREG|0644, st_size=3599, ...}, AT_EMPTY_PATH) = 0
read(10, "#\n# This is the toplevel file in"..., 4096) = 3599
read(10, "", 4096)                      = 0
close(10)                               = 0
openat(AT_FDCWD, "/usr/share/alsa/ucm2/lib/generic.conf", O_RDONLY) = 10
newfstatat(10, "", {st_mode=S_IFREG|0644, st_size=452, ...}, AT_EMPTY_PATH) = 0
read(10, "#\n# This is generic UCM configur"..., 4096) = 452
read(10, "", 4096)                      = 0
close(10)                               = 0
access("/usr/share/alsa/ucm2/conf.d/HDA-Intel/HDA ATI HDMI at 0xfcc20000 irq 75.conf", R_OK) = -1 ENOENT (No such file or directory)
access("/usr/share/alsa/ucm2/conf.d/HDA-Intel/HDA-Intel.conf", R_OK) = -1 ENOENT (No such file or directory)
close(3)                                = 0
write(2, "ALSA lib main.c:1412:(snd_use_ca"..., 45ALSA lib main.c:1412:(snd_use_case_mgr_open) ) = 45
write(2, "error: failed to import hw:2 use"..., 54error: failed to import hw:2 use case configuration -2) = 54
write(2, "\n", 1
)                       = 1
write(2, "alsaucm: error failed to open so"..., 73alsaucm: error failed to open sound card hw:2: No such file or directory
) = 73
exit_group(1)                           = ?
+++ exited with 1 +++

**Comment by perexg** [comment]
The `ucm2/conf.d/HDA-Intel/HDA-Intel.conf` should be symlink to `../../HDA/HDA.conf` :

```
$ ls -l ucm2/conf.d/HDA-Intel/HDA-Intel.conf 
... ucm2/conf.d/HDA-Intel/HDA-Intel.conf -> ../../HDA/HDA.conf
```

It looks like bad packaing or so...
See https://github.com/alsa-project/alsa-ucm-conf/blob/master/ucm2/conf.d/HDA-Intel/HDA-Intel.conf

Which distribution are you using?

**Comment by SirFooOfBar** [comment]
Arch linux, like I said in the initial comment

**Comment by perexg** [comment]
I overlooked this info, apologize. You may try unpack http://www.alsa-project.org/files/pub/lib/alsa-ucm-conf-1.2.6.2.tar.bz2 tar ball directly in /usr/share/alsa for a test. If things work, report the problem to your distribution.

```
tar xzjf alsa-ucm-conf-1.2.6.2.tar.bz2 -C /usr/share/alsa --strip-components=1 "*/ucm" "*/ucm2"
```

**Comment by SirFooOfBar** [comment]
alsaucm -c hw:3 dump text
Verb.HiFi {
        Comment Default
        Device.Line1 {
                Comment "Line Out"
                Values {
                        CaptureCTL "_ucm0001.hw:Generic"
                        JackControl "Line Out Front Jack"
                        PlaybackCTL "_ucm0001.hw:Generic"
                        PlaybackMixerElem Front
                        PlaybackPCM "_ucm0001.hw:Generic"
                        PlaybackPriority 200
                        TQ HiFi
                }
        }
        Device.Headphones {
                Comment Headphones
                Values {
                        CaptureCTL "_ucm0001.hw:Generic"
                        JackControl "Front Headphone Jack"
                        PlaybackCTL "_ucm0001.hw:Generic"
                        PlaybackMixerElem Headphone
                        PlaybackPCM "_ucm0001.hw:Generic,4"
                        PlaybackPriority 300
                        TQ HiFi
                }
        }
        Device.Line2 {
                Comment "Rear Line In"
                ConflictingDevices [
                        Mic2
                ]
                Values {
                        CaptureCTL "_ucm0001.hw:Generic"
                        CaptureMasterElem "Line Boost"
                        CaptureMixerElem Rear-Panel
                        CapturePCM "_ucm0001.hw:Generic"
                        CapturePriority 200
                        JackControl "Line Jack"
                        PlaybackCTL "_ucm0001.hw:Generic"
                        TQ HiFi
                }
        }
        Device.Mic2 {
                Comment "Rear Microphone"
                ConflictingDevices [
                        Line2
                ]
                Values {
                        CaptureCTL "_ucm0001.hw:Generic"
                        CaptureMasterElem "Rear Mic Boost"
                        CaptureMixerElem Rear-Panel
                        CapturePCM "_ucm0001.hw:Generic"
                        CapturePriority 300
                        JackControl "Rear Mic Jack"
                        JackHWMute Line2
                        PlaybackCTL "_ucm0001.hw:Generic"
                        TQ HiFi
                }
        }
        Device.Mic1 {
                Comment "Front Microphone"
                Values {
                        CaptureCTL "_ucm0001.hw:Generic"
                        CaptureMasterElem "Front Mic Boost"
                        CaptureMixerElem Front-Panel
                        CapturePCM "_ucm0001.hw:Generic,4"
                        CapturePriority 100
                        JackControl "Front Mic Jack"
                        PlaybackCTL "_ucm0001.hw:Generic"
                        TQ HiFi
                }
        }
}

Still no audio

**Comment by perexg** [comment]
Reboot or restart pulseaudio / pipewire? Do you see the audio devices there ?

**Comment by SirFooOfBar** [comment]
The device is always there, and I only lose it after rebooting
In version 1.2.6.1-1 it has the profiles seen in this image: https://ibb.co/S3Qnrh2
In version 1.2.6.2-2 it has only one profile called "unavailable"

**Comment by perexg** [comment]
It seems that the jack detection is not working properly on your hardware - if you look to the alsa-info.sh you provided - all Jack controls (like 'Front Headphone Jack' are false). It seems like the driver bug. I think that you can select manually the profile even if it's unavailable (driver reports that nothing is inserted to the jack) in PA.

**Comment by SirFooOfBar** [comment]
If it's a driver bug, why does it work with 1.2.6.1 but not 1.2.6.2? This is some sort of config package right? wheras when I hear driver I think kernel module. Or does that have some other meaning? And yes, the profile can be selected, but no sound comes out. Well that's not quite true. I can hear very faint radio static, though I have no idea what that implies

**Comment by perexg** [comment]
The PA fall back to the legacy device management in 1.2.6.1-1 . UCM is different, it should add the extra devices for your system (front panel - 'Headphones' and 'Mic1').

If you look to the UCM config dump, you can see all ALSA controls there:

- PCM devices (PlaybackPCM, CapturePCM)
- Mixer controls (PlaybackMixerElem, CaptureMixerElem)
- Jack controls (JackControl)

You can check all paths using the ALSA commands like 'alsamixer', 'speaker-test', 'aplay', 'amixer -c <CARDNO> controls' or so..

**Comment by perexg** [comment]
Do you use SPDIF output ?

**Comment by SirFooOfBar** [comment]
I do not. I use rear line out.

**Comment by perexg** [comment]
Apologize again, 'Line Out Front Jack' is true, so the config bellow should be picked from PA:

```
        Device.Line1 {
                Comment "Line Out"
                Values {
                        CaptureCTL "_ucm0001.hw:Generic"
                        JackControl "Line Out Front Jack"
                        PlaybackCTL "_ucm0001.hw:Generic"
                        PlaybackMixerElem Front
                        PlaybackPCM "_ucm0001.hw:Generic"
                        PlaybackPriority 200
                        TQ HiFi
                }
        }
```

Could you show the PA log ? (please, only URL or attach it)

https://fedoraproject.org/wiki/How_to_debug_PulseAudio_problems

Does `pasuspender -- speaker-test -D plughw:Generic` command work on your system? If you, try to fiddle the mixer settings using `alsamixer -c Generic` command.

**Comment by SirFooOfBar** [comment]
I use pipewire not pulseaudio

**Comment by perexg** [comment]
You can use speaker-test if you stop pipewire (just remove `pasuspender --` prefix).

**Comment by SirFooOfBar** [comment]
running speaker-test -D plughw:Generic:
very quiet crackling sounds. Nothing else

**Comment by perexg** [comment]
Ok, could you try the mixer settings (`alsamixer -c Generic` in the terminal - playback view)?

**Comment by SirFooOfBar** [comment]
https://ibb.co/gR7NJh9

**Comment by perexg** [comment]
Also, you may test `speaker-test -D plughw:Generic,4` command, but this device should be for the front jack.

**Comment by SirFooOfBar** [comment]
As it turns out, toggling mute is the M key and space does nothing. However, unmuting did not make the audio start working. I heard that faint radio static again, but nothing usable

**Comment by perexg** [comment]
Yes, M is for playback, Space for capture. I am tired. Anyway, we can compare `alsa-info.sh` output from working / non-working case (speaker-test when pipewire works with the old alsa-lib version), if you can grab it. You're testing the driver directly now (without UCM), so I'm curious where's the problem.

**Comment by SirFooOfBar** [comment]
Both a working and non working dump from alsa-info.sh were attached to the original gist, which I'm going to repost here. Happy bug hunting, remember to sleep at some point please. https://gist.github.com/SirFooOfBar/c5d5e4358da417902e97e37258b02677

**Comment by perexg** [comment]
It seems that the only difference is for the `Front` control:

```
@@ -3866,8 +3877,8 @@
 	control.2 {
 		iface MIXER
 		name 'Front Playback Switch'
-		value.0 false
-		value.1 false
+		value.0 true
+		value.1 true
 		comment {
 			access 'read write'
 			type BOOLEAN
```

**Comment by ljmc2000** [comment]
Just upgraded to 1.2.8-1and the line out audio seems to be working so I'm gonna call this issue closed

**Comment by Lensters** [comment]
I'm having the same issue, but I can't find a version 1.2.8-1 to upgrade to???

**Comment by ljmc2000** [comment]
> I'm having the same issue, but I can't find a version 1.2.8-1 to upgrade to???

What distro do you use? For archlinux, 1.2.8-1 is a very old version at this point and can be found [here](https://archive.archlinux.org/packages/a/alsa-ucm-conf/)

If you use an apt distro like ubuntu, you may find it [here](https://packages.debian.org/bookworm/all/alsa-ucm-conf/download)

If rpm is your jam, [this](https://kojipkgs.fedoraproject.org//packages/alsa-lib/1.2.8/1.fc36/x86_64/alsa-lib-1.2.8-1.fc36.x86_64.rpm) appears to be the equivalent fedora package

**Comment by Lensters** [comment]
Thanks!
