### ISSUE TITLE
Support for TC-Helicon GoXLR Mini

### ISSUE THREAD

**Issue by lm41** [alsa-project/alsa-ucm-conf#133]
Hi, many in the community had noticed that the Configuration for the GoXLR does not work for the GoXLR mini. https://www.tc-helicon.com/product.html?modelCode=P0DI7 Any ideas to get this to work as well? ref: #121

**Comment by lm41** [comment]
You only get a `GoXLRMini Multichannel` where no audio comes through.

`aplay -l` gives:

`card 1: GoXLRMini [GoXLRMini], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0`
  
  and `aplay -L` gives:
  `hw:CARD=GoXLRMini,DEV=0
    GoXLRMini, USB Audio
    Direct hardware device without any conversions
plughw:CARD=GoXLRMini,DEV=0
    GoXLRMini, USB Audio
    Hardware device with all software conversions
sysdefault:CARD=GoXLRMini
    GoXLRMini, USB Audio
    Default Audio Device
front:CARD=GoXLRMini,DEV=0
    GoXLRMini, USB Audio
    Front output / input
surround21:CARD=GoXLRMini,DEV=0
    GoXLRMini, USB Audio
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=GoXLRMini,DEV=0
    GoXLRMini, USB Audio
    4.0 Surround output to Front and Rear speakers
surround41:CARD=GoXLRMini,DEV=0
    GoXLRMini, USB Audio
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=GoXLRMini,DEV=0
    GoXLRMini, USB Audio
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=GoXLRMini,DEV=0
    GoXLRMini, USB Audio
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=GoXLRMini,DEV=0
    GoXLRMini, USB Audio
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
iec958:CARD=GoXLRMini,DEV=0
    GoXLRMini, USB Audio
    IEC958 (S/PDIF) Digital Audio Output
dmix:CARD=GoXLRMini,DEV=0
    GoXLRMini, USB Audio
    Direct sample mixing device
usbstream:CARD=GoXLRMini
    GoXLRMini
    USB Stream Output`

**Comment by perexg** [comment]
Use `speaker-test` or `aplay` to determine the number of channels and location of channel routing like in https://github.com/alsa-project/alsa-ucm-conf/issues/121 . Also, provide the dump of `alsa-info.sh --no-upload` (attach or put URL only here).

**Comment by Dinnerbone** [comment]
alsa-info available at https://gist.github.com/Dinnerbone/92507df307803cd081fbf733287b42e1

Playing around with speaker-test will need a bit more time so I'll do that later today and post the results.

**Comment by FrostyCoolSlug** [comment]
For completions sake, this issue can be closed. Excluding the issue solved by 2cc5a68, the GoXLR Mini works correctly under UCM.

I mentioned this in #175, but could we get a .2 release to solve the issues on almost every card that has a direct profile?

Thanks,
