### ISSUE TITLE
HP Spectre X360 fails to find soundcard

### ISSUE THREAD

**Issue by bornmw** [alsa-project/alsa-ucm-conf#135]
HP Spectre x360 Convertible 13t-aw200

Vanilla kernel 5.16.2
alsa-ucm-conf-1.2.6.3
alsa-lib-1.2.6.1
alsa-utils-1.2.6
pulseaudio-15.0

[pulseverbose.log](https://github.com/alsa-project/alsa-ucm-conf/files/7919861/pulseverbose.log)

A combination of these commands plays noise successfully:
alsaucm -c sof-soundwire set _verb HiFi set _enadev Speaker
speaker-test -Dhw:0,2 -c2 -r48000

$ aplay -Ll
null
    Discard all samples (playback) or generate zero samples (capture)
pulse
    PulseAudio Sound Server
upmix
    Plugin for channel upmix (4,6,8)
vdownmix
    Plugin for channel downmix (stereo) with a simple spacialization
sysdefault:CARD=sofsoundwire
    sof-soundwire, 
    Default Audio Device
usbstream:CARD=sofsoundwire
    sof-soundwire
    USB Stream Output
**** List of PLAYBACK Hardware Devices ****
card 0: sofsoundwire [sof-soundwire], device 0: Headphone (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofsoundwire [sof-soundwire], device 2: SDW1-speakers (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofsoundwire [sof-soundwire], device 5: HDMI1 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofsoundwire [sof-soundwire], device 6: HDMI2 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofsoundwire [sof-soundwire], device 7: HDMI3 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofsoundwire [sof-soundwire], device 8: HDMI4 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0

**Comment by bornmw** [comment]
Indeed, Gentoo has sys-firmware/sof-firmware-1.6.1 as latest stable.
After unmasking 1.9.3-r1 everything works
Thanks!

**Comment by plbossart** [comment]
@bornmw 2.0 is available since December :-)
