### ISSUE TITLE
Assertion 'jack' failed at modules/alsa/alsa-ucm.c:2158

### ISSUE THREAD

**Issue by JeremyFiggins** [alsa-project/alsa-ucm-conf#14]
Hi, I have the following hardware:

> ~> cat /proc/asound/cards
>  0 [NVidia         ]: HDA-Intel - HDA NVidia
>                       HDA NVidia at 0xf7080000 irq 90
>  1 [Generic        ]: HDA-Intel - HD-Audio Generic
>                       HDAudio-Gigabyte-ALC1220DualCodecs

and I'm running:

> ~> cat /etc/os-release 
> NAME="openSUSE Tumbleweed"
> VERSION="20200228"
> ID="opensuse-tumbleweed"
> ID_LIKE="opensuse suse"
> VERSION_ID="20200228"
> PRETTY_NAME="openSUSE Tumbleweed"
> ANSI_COLOR="0;32"
> CPE_NAME="cpe:/o:opensuse:tumbleweed:20200228"
> BUG_REPORT_URL="https://bugs.opensuse.org"
> HOME_URL="https://www.opensuse.org/"
> LOGO="distributor-logo"

Audio was working until a recent update. Now, I have no audio and when starting PulseAudio, I get:

> ~> pulseaudio 
> W: [pulseaudio] pid.c: Stale PID file, overwriting.
> W: [pulseaudio] alsa-ucm.c: UCM file does not specify 'PlaybackChannels' or 'CaptureChannels'for device Mic1, assuming stereo duplex.
> W: [pulseaudio] alsa-ucm.c: UCM file does not specify 'PlaybackChannels' or 'CaptureChannels'for device Mic2, assuming stereo duplex.
> W: [pulseaudio] alsa-ucm.c: UCM file does not specify 'PlaybackChannels' or 'CaptureChannels'for device Line2, assuming stereo duplex.
> W: [pulseaudio] alsa-ucm.c: UCM file does not specify 'PlaybackChannels' or 'CaptureChannels'for device Headphones, assuming stereo duplex.
> W: [pulseaudio] alsa-ucm.c: UCM file does not specify 'PlaybackChannels' or 'CaptureChannels'for device Line1, assuming stereo duplex.
> W: [pulseaudio] alsa-ucm.c: UCM file does not specify 'PlaybackChannels' or 'CaptureChannels'for device Speaker, assuming stereo duplex.
> E: [pulseaudio] alsa-ucm.c: Assertion 'jack' failed at modules/alsa/alsa-ucm.c:2158, function device_add_hw_mute_jack(). Aborting.
> Aborted (core dumped)

I tracked it down to /usr/share/alsa/ucm2/HDA-Intel/HiFi-dual.conf. If I revert the two commits here (https://github.com/alsa-project/alsa-ucm-conf/commits/master/ucm2/HDA-Intel/HiFi-dual.conf) and then use the version of HiFi-dual.conf before it was moved, then PulseAudio starts normally and I have sound.

**Comment by perexg** [comment]
https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/258

**Comment by perexg** [comment]
Thanks. Fixed in the above commit (da45a07c756308b57facf1a97c4842274ff04fe3). I extended the ucm-validator (https://github.com/alsa-project/alsa-tests/tree/master/python/ucm-validator) to catch those configuration inconsistencies.

Also, the pulseaudio fix was pushed for the merge to not crash the pulseaudio: https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/258
