### ISSUE TITLE
Realtek ALC886: missing analog output sink in PulseAudio since alsa-ucm-conf v1.2.6

### ISSUE THREAD

**Issue by mbey-mw** [alsa-project/alsa-ucm-conf#141]
Running a small system with NixOS resulted in a missing analog output sink in PulseAudio after upgrading the system. When using an older version (1.2.5.1) of alsa-ucm-conf and leaving all other packets identical everything is ok again. Switching to version 1.2.6.3 brings back the missing analog audio sink in PulseAudio. Seems like something changed in alsa-ucm-conf.

[alsa-info and more for v1.2.5.1](https://gist.github.com/mbey-mw/53a1911a16277f10778df8e2ea2b8960)
[alsa-info and more for v1.2.6.3](https://gist.github.com/mbey-mw/79ecbcd564236e661b05d30212e10330)

**Comment by perexg** [comment]
Show also `alsaucm -c 0 dump text` output, please.

**Comment by mbey-mw** [comment]
listcards run in alsaucm returns an empty list, so I added the output of `alsaucm dump text` to both gists in the first posting, there is one MIC more with the newer alsa-ucm-conf

**Comment by perexg** [comment]
```
--- 1.5.txt	2022-03-17 11:43:33.073318803 +0100
+++ 1.6.txt	2022-03-17 11:43:59.155372937 +0100
@@ -5,7 +5,7 @@
 		Comment Headphones
 		Values {
 			CaptureCTL "_ucm0001.hw:sofhdadsp"
-			JackControl "Headphone Jack"
+			JackControl "Front Headphone Jack"
 			PlaybackCTL "_ucm0001.hw:sofhdadsp"
 			PlaybackMasterElem Master
 			PlaybackMixerElem Headphone
@@ -46,8 +46,12 @@
 	}
 	Device.Mic2 {
 		Comment "Headphones Stereo Microphone"
+		ConflictingDevices [
+			Mic3
+		]
 		Values {
 			CaptureCTL "_ucm0001.hw:sofhdadsp"
+			CaptureMasterElem "Mic Boost"
 			CaptureMixerElem Capture
 			CapturePCM "_ucm0001.hw:sofhdadsp"
 			CapturePriority 200
@@ -57,6 +61,24 @@
 			PlaybackCTL "_ucm0001.hw:sofhdadsp"
 			TQ HiFi
 		}
+	}
+	Device.Mic3 {
+		Comment "Front Stereo Microphone"
+		ConflictingDevices [
+			Mic2
+		]
+		Values {
+			CaptureCTL "_ucm0001.hw:sofhdadsp"
+			CaptureMasterElem "Front Mic Boost"
+			CaptureMixerElem Capture
+			CapturePCM "_ucm0001.hw:sofhdadsp"
+			CapturePriority 400
+			CaptureSwitch "Capture Switch"
+			CaptureVolume "Capture Volume"
+			JackControl "Front Mic Jack"
+			PlaybackCTL "_ucm0001.hw:sofhdadsp"
+			TQ HiFi
+		}
 	}
 	Device.HDMI1 {
 		Comment "HDMI / DisplayPort 1 Output"
```

Could you also attach pulseaudio debug log ? https://fedoraproject.org/wiki/How_to_debug_PulseAudio_problems

**Comment by mbey-mw** [comment]
[pulseaudio debug log](https://gist.github.com/mbey-mw/ed8644c3c0617a042cfceadea7bd6eec)

**Comment by perexg** [comment]
Could you try to remove the whole `SectionDevice."Speaker"` block from `/usr/share/alsa/ucm2/HDA/HiFi-analog.conf` for a test ?

**Comment by mbey-mw** [comment]
After removal there is a sink for headphones only and it works, speaker/line out is not working
[pactl cards/sinks](https://gist.github.com/mbey-mw/41b53305ded1ebb6a913966d4dfa1a8a)

**Comment by perexg** [comment]
I did some changes (untested) to `HiFi-analog.conf` - https://raw.githubusercontent.com/perexg/alsa-ucm-conf/hda-line2/ucm2/HDA/HiFi-analog.conf . Could you test ? Just replace the file in `/usr/share/alsa/ucm2/HDA` directory.

**Comment by mbey-mw** [comment]
We are back to the missing analog output sink and PulseAudio reports `Failed to enable ucm device Line` on startup.
[pactl list cards and pulseaudio -vvvvv](https://gist.github.com/mbey-mw/f1776d9cbfad634fed6adfd802fa998e)

**Comment by mbey-mw** [comment]
Now ucm fails and PulseAudio resumes with default.conf
```
I: [pulseaudio] (alsa-lib)parser.c: error: unable to find device 'Line'
I: [pulseaudio] (alsa-lib)parser.c: error: device management error in verb 'HiFi'
I: [pulseaudio] (alsa-lib)main.c: error: failed to import hw:0 use case configuration -2
I: [pulseaudio] (alsa-lib)parser.c: error: unable to find device 'Line'
I: [pulseaudio] (alsa-lib)parser.c: error: device management error in verb 'HiFi'
I: [pulseaudio] (alsa-lib)main.c: error: failed to import sof-hda-dsp use case configuration -2
I: [pulseaudio] alsa-ucm.c: UCM not available for card sof-hda-dsp

```

**Comment by mbey-mw** [comment]
The analog output sink is now created and works. This hardware has only one output jack and I get sound - great and thank you very much.
[pactl output](https://gist.github.com/mbey-mw/1f9b60a97ac56e60631c2288b7b4e36e)

**Comment by mbey-mw** [comment]
@perexg Will this change be merged? Are there any other measures that need to be taken?

**Comment by perexg** [comment]
Merged.
