### ISSUE TITLE
Gigabyte Z590 Aorus Pro AX - No sound S/PDIF or front ports

### ISSUE THREAD

**Issue by quantumsized** [alsa-project/alsa-ucm-conf#147]
ID 0414:a00e Giga-Byte Technology Co., Ltd USB Audio
I do hope I can resolve this issue of no output from S/PDIF and also front audio jacks not working.
System is Debian 11 Latest Stable & rear analog audio output seems to be working fine.
I can get audio over HDMI too just fine.
I have been following this thread in my spare time: https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/issues/1337
Admittedly I am a bit lost at moments with the discussion but I'm not new to Linux or even BSD.
Kernel: 5.10.0-13-amd64
All things are standard system-wide as I've not gone outside the mainstream doing any core customization.
I understand at present that the issue stems from UCM ? Anyway, I would love to have my whole system working and am not quite sure what I missed in the threads I've been reading over.
Current UCM version: alsa-ucm-conf (1.2.4-2)
Thanks

**Comment by quantumsized** [comment]
Maybe worth noting too, this is my output when doing locate ucm2/USB-Audio
/usr/share/alsa/ucm2/USB-Audio
/usr/share/alsa/ucm2/USB-Audio/Dell-WD15-Dock-HiFi.conf
/usr/share/alsa/ucm2/USB-Audio/Dell-WD15-Dock.conf
/usr/share/alsa/ucm2/USB-Audio/Lenovo-ThinkStation-P620-Main-HiFi.conf
/usr/share/alsa/ucm2/USB-Audio/Lenovo-ThinkStation-P620-Main.conf
/usr/share/alsa/ucm2/USB-Audio/Lenovo-ThinkStation-P620-Rear-HiFi.conf
/usr/share/alsa/ucm2/USB-Audio/Lenovo-ThinkStation-P620-Rear.conf
/usr/share/alsa/ucm2/USB-Audio/Realtek-ALC1220-VB-Desktop-HiFi.conf
/usr/share/alsa/ucm2/USB-Audio/Realtek-ALC1220-VB-Desktop.conf

At the moment I'd guess (after looking in most of them) that the system is using the Realtek-ALC1220-VB-Desktop-HiFi.conf profile.

**Comment by geraldog** [comment]
Hi @quantumsized 

Could you please provide `lsusb -v -d 0414:a00e` and also `arecord -l` and `aplay -l` outputs?

The PR mentioned on the thread you've been following is here: https://github.com/alsa-project/alsa-ucm-conf/pull/143

Are you comfortable with patching your kernel, recompiling and booting it?

**Comment by quantumsized** [comment]
I can indeed patch and compile my kernel. I have each of the commands here in their attached files.
[lsusb.txt](https://github.com/alsa-project/alsa-ucm-conf/files/8459839/lsusb.txt)
[arecord.txt](https://github.com/alsa-project/alsa-ucm-conf/files/8459842/arecord.txt)
[aplay.txt](https://github.com/alsa-project/alsa-ucm-conf/files/8459843/aplay.txt)

**Comment by quantumsized** [comment]
I might mention I've made a small bit of progress by following this thread: https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/issues/1337

Now when I plug in my headphones to the front port, it says so and there is an option to select them in the KDE Plasma Audio Settings under Devices.  Still nothing on the S/PDIF.

What I've tried in order to get here is moving the /usr/share/alsa/ucm2 to /usr/share/alsa/ucm2-original 
Download and copy the latest alsa-ucm-conf ucm2 folder to where the original was and then restarting pulse audio.

**Comment by geraldog** [comment]
I read the thread you mentioned, but I think you're missing the point, you need the UCM configuration from PR #143 which is not yet merged. You'll need to manually copy the UCM configuration from #143 or do it using git. Notice that your package manager may later override these manual changes.

Look, in #143 it says clearly that you need kernel 5.17.1 at least. 5.17.2 at the time of this writing is already stable so you may go with that.

Then cd to /usr/src/linux/sound/usb and apply the following patch with `patch -up0 < alc4080-gigabyte-z590.txt`
[alc4080-gigabyte-z590.txt](https://github.com/alsa-project/alsa-ucm-conf/files/8459905/alc4080-gigabyte-z590.txt)

I checked you lsusb and it is safe to use the same msi_mpg_x570s_carbon_max_wifi_alc4080_map because the bSourceID's match.

So recompile the kernel with the patch, install and boot it according your distro documentation, and then lastly apply UCM configurations of #143 and hopefully it should work.

I'm not familiar enough with PulseAudio to tell you if

**Comment by quantumsized** [comment]
I had figured I'd missed something so thanks for being an extra set of eyes. I will go back over the #143 and then follow your suggestions. I will keep you posted.

**Comment by quantumsized** [comment]
Ran into one hurdle with module signing but once overcome, all seems to be compiling fine. I see it may take between an hour and two to do so but am around halfway in by the long estimate.

The main thing to alter to make it get passed the module signing I'd run into was to set this config flag thus: CONFIG_SYSTEM_TRUSTED_KEYS=""

**Comment by geraldog** [comment]
If you rely on Secure Boot you will surely run into trouble after setting CONFIG_SYSTEM_TRUSTED_KEYS=""

The aftermath could be being left with an unbootable system.

So remember to double check your UEFI BIOS to see if you're relying on Secure Boot, and if you are, and you can't turn it off for some reason, there's additional procedures for signing your kernel that you must follow, which are beyond the scope of ALSA help.

**Comment by quantumsized** [comment]
Um, Thanks but I am fairly sure I don't rely on Secure Boot.

I'd assume this setting would one of the menu options in GRUB? I seem to remember something about this but it's been years since I've looked at anything with Secure Boot (options etc.)

**Comment by geraldog** [comment]
No, Secure Boot can be disabled in the UEFI BIOS, before GRUB loads.

**Comment by quantumsized** [comment]
Oops, pardon me. I should know that.
I will check my BIOS settings but I am fairly sure Secure Boot is disabled.
This is a new machine and is also the reason I am currently investigating the ALC4080 driver issue with my Gigabyte board.
I will take a quick swing through the BIOS now and see before I install the newly compiled kernel.

**Comment by quantumsized** [comment]
For sake of due diligence, and cause I may as well know what there is to know about it, I am reading up on all things Secure Boot related to my MB and my distro (Debian) in order to compile a version that can use Secure Boot if needed or wanted.

**Comment by quantumsized** [comment]
So reading through the various things on Secure Boot and then for my distro, I found this command to see if Secure Boot is enabled or if the system has been booted using Secure boot: <code>$ sudo mokutil --sb-state</code>
Source on this: https://wiki.debian.org/SecureBoot

**Comment by geraldog** [comment]
Interesting.

After you boot the patched kernel, you can confirm with alsamixer if Mixer names have changed.

Then you can:

`git clone https://github.com/alsa-project/alsa-ucm-conf`
`cd alsa-ucm-conf/`
`git fetch origin pull/143/head:alc4080`
`git checkout alc4080`
`ls ucm2/USB-Audio/Realtek/`

You should see ALC4080.conf and ALC4080-HiFi.conf.

Copy ucm2 directory to /usr/share/alsa/ucm2 like you did before (risky because it could be messed up anytime by apt) and restart PulseAudio. It should work.

**Comment by geraldog** [comment]
> So just for note, the original CONFIG_SYSTEM_TRUSTED_KEYS was set like this: `CONFIG_SYSTEM_TRUSTED_KEYS="debian/certs/debian-uefi-certs.pem"`
> 
> That is interesting Alsamixer.

alsamixer is just for confirming everything went well with the patch I sent you and that Mixer names are correctly applied.

The rest of those are git commands to fetch the UCM config from #143 you need

> I am seeing if I can get a SB version on the kernel to compile now.

Yes, please be careful.

**Comment by quantumsized** [comment]
Careful indeed.
I figured out that there are two ways to get the .pem file set right.
**Number one:** copy the file <code>debian/certs/debian-uefi-certs.pem</code> from a previous but current stable source in your distro or >
**Number two:** following the method of creating your own MOK.pem I found in the guide https://wiki.debian.org/SecureBoot and then copy that key after following all the steps including enrolling your Machine Owner Key (MOK) to the debian/certs/ folder and creating the certs folder if needed.
This way you can compile a version with UEFI SB capable.
That said, I like option one best and went with that as it's Debian signed and so is in keeping with my distro.

There are a few things to keep in mind for anyone whom may later read this I'd learned from previous times compiling kernels. The biggest one is, by all means look through the configuration in whatever way preferred when doing a <code>make config</code> or <code>make menuconfig</code> (or others) but if it is set for your distro ahead of time, many of the settings should be set correctly already. There may be a few specifics you want to change from being modules to built-in or maybe even add support to via module but generally, it should be a clean run doing little to nothing and especially if you are copying a previous .config file.
