### ISSUE TITLE
Complete support for "Pro" USB multichannel cards

### ISSUE THREAD

**Issue by perexg** [alsa-project/alsa-ucm-conf#154]
- [x] channel split using alsa-lib
- [x] channel split inside app
- [x] channel split hide the specific configs (alsa-lib, app side support)
- [x] mixer control remap using alsa-lib
- [x] simplify the mixer control remap

**Comment by perexg** [comment]
Guide from Peter Wedder: https://gist.github.com/brndd/ccec98a575f7c0422d50402937439227

Related commits:
- 9d16a3bfaae45cf9518d832461918c1d1cf0688e Add profile for Behringer UMC204HD
- 701775d52b1b53b7aad89ef5aa78ef04401ca4bd Behringer UMC204HD - change the default mixer profile
- f4330c22c3e5333e78a3680ee411d98ad3115eab Add direct hardware profile for UMC204HD

**Comment by brndd** [comment]
It does look simpler, yes, and most importantly more copy-pasteable.

I will test it, but it will take me until next week to find the time to do so. I haven't compiled and set up alsa-lib before, so it'll probably take me some time to figure it out.

**Comment by perexg** [comment]
Merged branch with multiple changes for the recent alsa-lib: https://github.com/alsa-project/alsa-ucm-conf/compare/master...perexg:macro / https://github.com/perexg/alsa-ucm-conf/tree/macro .

**Comment by perexg** [comment]
I've applied all my changes to the main repository. Open separate issue / pull requests to resolve possible regressions.
