### ISSUE TITLE
Asus Z690-E: No Profiles Available in alsa-lib 1.2.7-2

### ISSUE THREAD

**Issue by BrothersRM** [alsa-project/alsa-ucm-conf#168]
Upgrading alsa-lib from 1.2.6.1-1 to 1.2.7-2 seems to have broken support for my motherboard's sound card. 
Downgrading the package did resolve the issue.

Device is listed in `lsusb -v` as : `Bus 001 Device 002: ID 0b05:1996 ASUSTek Computer, Inc. USB Audio`

My hardware configuration uses speakers attached to the front, surround and subwoofer ports on my motherboard.

Some interesting things I noticed while it was broken:
- Plugging headphones into the front-panel headphone port allowed me to turn on the rear speakers, though they didn't seem to use the correct profile. Max volume was far lower
- Though the device was listed as unavailable, I could manually enable the rear speakers using pavucontrol when front headphones weren't plugged in
- Trying to run speaker-test on the device failed with 'no valid configuration'

Please let me know if I can provide more information / do any testing.

**Comment by perexg** [comment]
Could you attach (no copy-and-paste) the output from `alsa-info.sh --no-upload` ?

**Comment by BrothersRM** [comment]
Yeah absolutely. Attached below:

[alsa-info.txt.ZHKg0oNeW7.tar.gz](https://github.com/alsa-project/alsa-ucm-conf/files/8892099/alsa-info.txt.ZHKg0oNeW7.tar.gz)

**Comment by pinkflames** [comment]
Considering that PipeWire mostly works with the generic ACP profiles, when UCM is intentionally disabled, I'm not sure it's really the driver that should be faulted. And when using the Pro Audio profile to disable the fancy jack detection logic, all analog outputs seem to be usable. Surely if controls break with UCM, that's a UCM bug.

**Comment by perexg** [comment]
> Considering that PipeWire mostly works with the generic ACP profiles, when UCM is intentionally disabled, I'm not sure it's really the driver that should be faulted. And when using the Pro Audio profile to disable the fancy jack detection logic, all analog outputs seem to be usable. Surely if controls break with UCM, that's a UCM bug.

I am afraid, but the availability logic is part of the pulseaudio UCM code (pipewire use this code, too). I'm not saying that the driver is faulty, but there are several models for ALC4080 and apparently the control names (defined by the driver) are different.

ACP code is not same code as UCM code in pulseaudio / pipewire. We need to resolve all those nuances. If the `JackControl` is present and enabled (true), the pulseaudio should handle the device like available.

You can list all jack names, mixer control names and PCM device names for UCM using `alsaucm -c 0 dump text` command (replace zero with the proper ALSA card number) to verify, if all information are correct for your specific harware.

**Comment by perexg** [comment]
> I just get nothing ("list is empty" to be exact)) for `alsaucm listcards` and similarly no number works for the -c value. This is with UCM enabled for the particular device in WirePlumber, though I'm not sure if that should even matter or not.

Use `aplay -l` to list ALSA soundcards. The `listcards` command does not work for `alsaucm`. If UCM does not work, there should be an error message.

**Comment by pinkflames** [comment]
Here's the output and nothing jumps out at me as immediately wrong, in fact, it looks exactly what I get with ACP when using the PipeWire's Pro Audio profile. I'd have added a collapsible section but at least the GitHub GUI does not offer it.

```
Verb.HiFi {
        Comment "Play HiFi quality Music"
        Device.Speaker {
                Comment Speakers
                Values {
                        CaptureCTL "_ucm0001.hw:Audio"
                        JackControl "Speaker - Output Jack"
                        PlaybackCTL "_ucm0001.hw:Audio"
                        PlaybackChannels 8
                        PlaybackMixerElem Speaker
                        PlaybackPCM "_ucm0001.hw:Audio"
                        PlaybackPriority 200
                }
        }
        Device.Headphones {
                Comment "Front Headphones"
                Values {
                        CaptureCTL "_ucm0001.hw:Audio"
                        JackControl "Headphone - Output Jack"
                        PlaybackCTL "_ucm0001.hw:Audio"
                        PlaybackMixerElem "Front Headphone"
                        PlaybackPCM "_ucm0001.hw:Audio,1"
                        PlaybackPriority 300
                }
        }
        Device.SPDIF {
                Comment "S/PDIF Out"
                Values {
                        CaptureCTL "_ucm0001.hw:Audio"
                        PlaybackCTL "_ucm0001.hw:Audio"
                        PlaybackMixerElem IEC958
                        PlaybackPCM "_ucm0001.hw:Audio,2"
                        PlaybackPriority 100
                }
        }
        Device.Line {
                Comment "Line In"
                Values {
                        CaptureCTL "_ucm0001.hw:Audio"
                        CaptureMixerElem Line
                        CapturePCM "_ucm0001.hw:Audio,1"
                        CapturePriority 100
                        JackControl "Line - Input Jack"
                        PlaybackCTL "_ucm0001.hw:Audio"
                }
        }
        Device.Mic1 {
                Comment "Front Microphone"
                Values {
                        CaptureCTL "_ucm0001.hw:Audio"
                        CaptureMixerElem Mic
                        CapturePCM "_ucm0001.hw:Audio,2"
                        CapturePriority 200
                        JackControl "Mic - Input Jack"
                        PlaybackCTL "_ucm0001.hw:Audio"
                }
        }
        Device.Mic2 {
                Comment Microphone
                Values {
                        CaptureCTL "_ucm0001.hw:Audio"
                        CaptureMixerElem Mic
                        CapturePCM "_ucm0001.hw:Audio"
                        CapturePriority 300
                        JackControl "Mic - Input Jack"
                        PlaybackCTL "_ucm0001.hw:Audio"
                }
        }
}
```

**Comment by perexg** [comment]
> Perhaps there's a bug then, because `alsaucm -h` does in fact offer listcards as a viable command (and it didn't explicitly error as unsupported when I did try it).

It's implemented, but it does not list the hardware UCM cards. I've fixed this in https://github.com/alsa-project/alsa-lib/commit/2d56ff8ded18d387c094e0e3b83d68ae3a133101 right now.

> Here's the output and nothing jumps out at me as immediately wrong, in fact, it looks exactly like what I get with ACP when using the PipeWire's Pro Audio profile. I'd have added a collapsible section but at least the GitHub GUI does not offer it.

You need to work with `amixer` or `alsamixer` tools to compare the mixer and card controls with the UCM device values. For example:

```
!-------Mixer controls for card Audio

Card sysdefault:3 'Audio'/'Generic USB Audio at usb-0000:00:14.0-4, high speed'
  Mixer name	: 'USB Mixer'
  Components	: 'USB0b05:1996'
  Controls      : 29
  Simple ctrls  : 6
Simple mixer control 'PCM',0
  Capabilities: pvolume pswitch pswitch-joined
  Playback channels: Front Left - Front Right - Rear Left - Rear Right - Front Center - Woofer - Side Left - Side Right
  Limits: Playback 0 - 87
  Mono:
  Front Left: Playback 61 [70%] [-19.50dB] [on]
  Front Right: Playback 61 [70%] [-19.50dB] [on]
  Rear Left: Playback 61 [70%] [-19.50dB] [on]
  Rear Right: Playback 61 [70%] [-19.50dB] [on]
  Front Center: Playback 61 [70%] [-19.50dB] [on]
  Woofer: Playback 61 [70%] [-19.50dB] [on]
  Side Left: Playback 61 [70%] [-19.50dB] [on]
  Side Right: Playback 61 [70%] [-19.50dB] [on]
Simple mixer control 'PCM',1
  Capabilities: pvolume pswitch pswitch-joined
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 87
  Mono:
  Front Left: Playback 87 [100%] [0.00dB] [on]
  Front Right: Playback 87 [100%] [0.00dB] [on]
Simple mixer control 'PCM',2
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [on]
Simple mixer control 'Line',0
  Capabilities: cvolume cswitch cswitch-joined
  Capture channels: Front Left - Front Right
  Limits: Capture 0 - 39
  Front Left: Capture 0 [0%] [-17.25dB] [off]
  Front Right: Capture 0 [0%] [-17.25dB] [off]
Simple mixer control 'Mic',0
  Capabilities: cvolume cswitch cswitch-joined
  Capture channels: Front Left - Front Right
  Limits: Capture 0 - 39
  Front Left: Capture 24 [62%] [0.75dB] [on]
  Front Right: Capture 24 [62%] [0.75dB] [on]
Simple mixer control 'Analog In',0
  Capabilities: cvolume cswitch cswitch-joined
  Capture channels: Front Left - Front Right
  Limits: Capture 0 - 39
  Front Left: Capture 23 [59%] [0.00dB] [on]
  Front Right: Capture 23 [59%] [0.00dB] [on]
```

shows that there's no "Speaker" mixer control element, but probably "PCM":

```
Device.Speaker { 
   Comment Speakers
   Values { 
      CaptureCTL "_ucm0001.hw:Audio" 
      JackControl "Speaker - Output Jack"
      PlaybackCTL "_ucm0001.hw:Audio"
      PlaybackChannels 8
      PlaybackMixerElem Speaker
      PlaybackPCM "_ucm0001.hw:Audio"
      PlaybackPriority 200
   }
} 
```

See `PlaybackMixerElem` value.

**Comment by perexg** [comment]
Those motherboards with ALC4080 codecs should be supported now. Please, create another issue, if you have a problem.
