### ISSUE TITLE
MSI MPG X570S EDGE MAX WIFI compatibility

### ISSUE THREAD

**Issue by yhojann-cl** [alsa-project/alsa-ucm-conf#172]
Please, add `0db0:151f` to `realtek-alc4080` chip compatibility in MPG X570S EDGE MAX WIFI motherboard in https://github.com/alsa-project/alsa-ucm-conf/blob/master/ucm2/USB-Audio/USB-Audio.conf#L45 :

```
$ lsusb | grep 0db0
Bus 001 Device 003: ID 0db0:151f Micro Star International USB Audio
```

In `ucm2/USB-Audio/USB-Audio.conf` add `151f` to regex of `0db0`:

```
Regex "USB((0b05:(1996|1a2[07]))|(0db0:(1feb|419c|a073|151f)))"
```

My Motherboard is MSI X570S and output audio works fine but:

- Motherboard microphone plug is not work.
- Frontal microphone plug is not work.
- When change output from gnome settings to hdmi audio does not work, the audio continues to play in the plug and not in the monitor.
- When I change the input or output from digital to analog or sinput it does not change at all.
- The strangest thing is that the microphone input captures the audio that is heard in the system as if it were the output, audacious records the audio from the desktop when it tries to monitor the microphone.
- When plugging or unplugging the microphone, the system detects this change and tries to change the audio input automatically, but it does not capture the microphone and the desktop continues to be heard.
- When plug headphone in frontal plug the gnome setting change automaticaly to the headphone item, but the sound play in speakers, not in headphone.
- On Audacity when capture Alsa + `USB Audio: #2 (hw: 1,2)` works fine!, but can not set on gnome settings.

My alsa data: http://alsa-project.org/db/?f=e29a6593e48350efeba75f69d5ece62379973c35

**Comment by yhojann-cl** [comment]
Have apply the change in mi pc but can not dettect the hardware:

```
$ pactl list
...
Placa #1
	Nombre: alsa_card.usb-Generic_USB_Audio-00
	Controlador: module-alsa-card.c
	Módulo propietario: 24
	Propiedades:
		alsa.card = "1"
		alsa.card_name = "USB Audio"
		alsa.long_card_name = "Generic USB Audio at usb-0000:2a:00.1-2, high speed"
		alsa.driver_name = "snd_usb_audio"
		device.bus_path = "pci-0000:2a:00.1-usb-0:2:1.0"
		sysfs.path = "/devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:08.0/0000:2a:00.1/usb1/1-2/1-2:1.0/sound/card1"
		udev.id = "usb-Generic_USB_Audio-00"
		device.bus = "usb"
		device.vendor.id = "0db0"
		device.vendor.name = "Micro Star International"
		device.product.id = "151f"
		device.product.name = "USB Audio"
		device.serial = "Generic_USB_Audio"
		device.string = "1"
		device.description = "USB Audio"
		module-udev-detect.discovered = "1"
		device.icon_name = "audio-card-usb"
...
```

The microphone and headphone does not work when plug, but when aplay and arecord dettect this interfaces:

- Rear headphone : hw:1,0
- Front headphone : hw:1,1
- Front microphone : hw:1,2
- Rear microphone : hw:1,3

I try change manualy in the /etc/pulse/default.pa and works but not by default in applications and need change manualy from gnome settings, when plug microphone select a bad hardware id and need change this.

**Comment by yhojann-cl** [comment]
Ok i have a legacy settings problem:

```
# alsaucm reload
ALSA lib parser.c:2021:(parse_master_file) Incompatible syntax 6 in HDA-Intel.conf
ALSA lib main.c:1412:(snd_use_case_mgr_open) error: failed to import hw:0 use case configuration -22
alsaucm: error failed to open sound card hw:0: Invalid argument
```

Need upgrade all alsa and pulse packages?

**Comment by perexg** [comment]
I added your USB ID in 1f8b99dcec93e8b76e0ea0ec4d94874006d39033 . It would be nice, if you can test the latest ucm configuration.

**Comment by yhojann-cl** [comment]
Thanks to add the id to settings but has same results, input and output does not works.

```bash
$ git clone https://github.com/alsa-project/alsa-ucm-conf;
$ sudo rsync -tvrz --progress --links --delete ./alsa-ucm-conf/ucm/ /usr/share/alsa/ucm/;
$ sudo rsync -tvrz --progress --links --delete ./alsa-ucm-conf/ucm2/ /usr/share/alsa/ucm2/;
$ sudo alsaucm reload;
ALSA lib parser.c:2021:(parse_master_file) Incompatible syntax 6 in HDA-Intel.conf
ALSA lib main.c:1412:(snd_use_case_mgr_open) error: failed to import hw:0 use case configuration -22
alsaucm: error failed to open sound card hw:0: Invalid argument
```

When I connect the headphones to the front connector (motherboard usb) it is not heard but the audio comes out through the speakers of the rear connector. The microphone does not work in either the rear or the front connector.

I buy a simple connector: https://articulo.mercadolibre.cl/MLC-954412749-tarjeta-adaptador-doble-sonido-usb-stereo-audio-microfono-_JM and works very fine, but when need use microphone can not use speakers, need connect the plug to the frontal connector.

**Comment by upmangaurav** [comment]
Same issue on MSI B650M Mortar Wifi for Ubuntu.

**Comment by perexg** [comment]
All USB IDs from the issue were added to https://github.com/alsa-project/alsa-ucm-conf/blob/master/ucm2/USB-Audio/USB-Audio.conf . Create another issue for your hardware with a full _description_  of your problem.

**Comment by abhisas** [comment]
> > All USB IDs from the issue were added to https://github.com/alsa-project/alsa-ucm-conf/blob/master/ucm2/USB-Audio/USB-Audio.conf . Create another issue for your hardware with a full _description_ of your problem.
> 
> I am very new to this subject. I recently switched from Win10 to Linux, so please be patient with my lack of knowledge. I am using a MS690 Unify. Despite the fact, that I can find one in the USB-Audio.conf on line 83 "# 0db0:82c7 MSI MEG Z690I Unify", I still can't get my optical SPDIF working. If i choose digital out, the digital signal is routed to the analog output, which is very ugly to listen to. Also my microphone isn't working. It seems, as if the mic in is configured as sink for monitor out of any other source. sudo dmidecode -t 2 answers
> # dmidecode 3.6
> 
> Getting SMBIOS data from sysfs. SMBIOS 3.6.0 present.
> 
> Handle 0x0002, DMI type 2, 15 bytes Base Board Information Manufacturer: Micro-Star International Co., Ltd. Product Name: MEG Z690 UNIFY (MS-7D28) Version: 1.0 Serial Number: 07D2810_N81E356737 Asset Tag: Default string Features: Board is a hosting board Board is replaceable Location In Chassis: Default string Chassis Handle: 0x0003 Type: Motherboard Contained Object Handles: 0
> 
> Hope this is usefull. Please let me know, if you need more information. Of course I have an ALC4080 built in, but it's also recognised as USB-Audio.

Hi, my microphone and front-panel audio is not working either. I do not have the exact device ID but we have the same ALC4080 and MSI motherboards. I made this [issue](https://github.com/alsa-project/alsa-ucm-conf/issues/664#issuecomment-3684655153)  for this. Which distro are you on? I am on fedora

**Comment by Ralfpf** [comment]
My board is a MSI690 Unifiy, not 790, but I guess the problem is the same.
