### ISSUE TITLE
GoXLR Broken in 1.2.7.1

### ISSUE THREAD

**Issue by FrostyCoolSlug** [alsa-project/alsa-ucm-conf#175]
The alsa profiles no longer set correctly for the GoXLR or GoXLR Mini since 5dcd69.

From what I can tell with some quick tests, if the DirectCardName isn't set, the profile doesn't seem to apply anymore. Removing the direct config, or adding a DirectCardName seems to solve the issue (although obviously, neither are ideal).

Thanks.

**Comment by FrostyCoolSlug** [comment]
I've done some extra testing, if I place:

`Define.DirectCardName ""`

Into the goxlr.conf file, it works correctly (Direct GoXLR appears, and the profile loads), so I'm guessing it's an issue with the variable being completely undefined?

**Comment by perexg** [comment]
Oops. Yes, the undefined case should be ignored. Fixed in 2cc5a68e9798bc3226e2349fad5d3faa886368c1 .

**Comment by FrostyCoolSlug** [comment]
Apologies, I know this is closed, but given that this issue is likely to effect almost every device supported by UCM currently, would it warrant a .2 release to fix?

**Comment by rjahanbakhshi** [comment]
> Apologies, I know this is closed, but given that this issue is likely to effect almost every device supported by UCM currently, would it warrant a .2 release to fix?

+1
