### ISSUE TITLE
UCM for Behringer UMC204HD not working

### ISSUE THREAD

**Issue by maru-sama** [alsa-project/alsa-ucm-conf#178]
Similar to #177 I have problem with the ucm setting for the UMC204HD. The problem is that apparently no mixer is being created for the device, when trying to open the card with alsamixer it just fails with cannot load mixer controls. the mixer has been created though if I do not missread the output from alsa-info.sh (attached)
[alsa-info.txt](https://github.com/alsa-project/alsa-ucm-conf/files/8977069/alsa-info.txt)

I am using alsa-libs 2.0.7 and the latest ucm from master on ubuntu 22.04 to make sure that I have all the minimum requirements.

**Comment by perexg** [comment]
Closing as dup of #177. Let continue there.
