### ISSUE TITLE
sof-soundwire: broken settings for RT711 and RT711-SDCA

### ISSUE THREAD

**Issue by plbossart** [alsa-project/alsa-ucm-conf#179]
[plb@fedora ~]$ alsaucm -c sof-soundwire set _verb HiFi
ALSA lib main.c:826:(execute_sequence) unable to execute cset 'name='PGA2.0 2 Master Capture Switch' 0'
ALSA lib main.c:2573:(set_verb_user) error: failed to initialize new use case: HiFi

There's not such thing as a switch here:

amixer -Dhw:0 sget 'PGA2.0 2 Master',0 
Simple mixer control 'PGA2.0 2 Master',0
  Capabilities: cvolume
  Capture channels: Front Left - Front Right
  Limits: Capture 0 - 80
  Front Left: Capture 80 [100%] [30.00dB]
  Front Right: Capture 80 [100%] [30.00dB]

In addition, it makes no sense to use an SOF control to set the volume/switch on the headset codec side. The volume control should be done in the codec, not in the SOF firmware.

**Comment by plbossart** [comment]
@shumingfan what controls would you recommend we used for volume and switch on both RT711 and RT711-sdca? Thanks!

**Comment by shumingfan** [comment]
@plbossart 
R711 - capture volume/switch
amixer "ADC 08 Capture Volume"
amixer "ADC 08 Capture Switch"

R711-sdca - capture volume/switch
amixer "FU0F Capture Volume"
amixer "FU0F Capture Switch"

**Comment by plbossart** [comment]
Thanks @shumingfan.

@perexg I am still in the dark on the difference between capture and playback. The former has 'Capture Switch' and 'Capture Volume', shouldn't there be a moral equivalent for playback, e.g. 'Playback Switch' and 'Playback Capture'.

Likewise some devices expose "CaptureMixerElem", is it not required to have a 'PlaybackMixerElem".  I never quite understood what those 'MixerElem' things might be.

**Comment by perexg** [comment]
@plbossart : The volume control direction are tied with the PCM devices (capture - input, playback - output). I merged #180, so I think that this problem was resolved.
