### ISSUE TITLE
Crackling on playback - Mackie ProFX6v3

### ISSUE THREAD

**Issue by emaxoda** [alsa-project/alsa-ucm-conf#182]
Hi. I tried to add support for the Mackie ProFX6 and while it technically works (before I was getting one a 4.0 surround profile instead of the two output devices it should show) I get this crackling sound on playback whenever I try to play any sound, the craclking or distortion can be heared alonside whatever is on playback. I tried playing sound with aplay and paplay and got the same craclking noise alongside with the played track. 

[alsa-info](https://github.com/alsa-project/alsa-ucm-conf/files/9032058/profx.txt)

https://github.com/emaxoda/alsa-ucm-conf/commit/51b9b6f1a81ab55e16bba12a370afc518d961550

^ my commit

**Comment by emaxoda** [comment]
Also, on the Direct profile I don't get craclking sound but everything sound on a lower pitch.

**Comment by perexg** [comment]
It seems that the wrong sample rate is used. It should be the driver responsibility to not allow a wrong sample rate on a PCM device. You may check the used sample rate using the procfs - `cat /proc/asound/card0/pcm0p/sub0/*` . Use the right ALSA card number (`aplay -l` may help).

**Comment by emaxoda** [comment]
Yeah seem like its a driver problem, I tried without modifying anything and yeah, if I listen to spotify the before opening anything then it seem to work correctly spotify sample rate is 44.1 kHz and it seems like it's "upsampling" correctly since the driver it's working at 48 kHz but as soon as I open, let's say discord and I join a voice channel, which is working at 48 kHz natively then every sound in playback changes the pitch and slows down, including Discord itself. The thing is this doesn't get solved if I just close discord, sometimes it takes restarting pipewire completly to fix it but then it doesn't make sense since it's going to be borked as soon as anything changes the sample rate. 
The craclking when using the created profile I made for the device seems to be related to the sound format being changed to 16 bits instead of the default 32 bits pipewire uses normally. Sorry if I made any wrong assumptions since I'm don't know much about how pipewire/sound works.

But yeah it seems like a driver problem. Where should I take this to?

**Comment by emaxoda** [comment]
Okay so I solved craclking by using the new way to stablish the sound format you added to the behringer audio interface, adding Format S32_LE made the trick since before sound was working on S16_LE and that seemed to make the craclking noise on the split interfaces appear. The new problem is that I cannot change the sample rate on through pipewire anymore, at least on the split profiles, on the direct profile the pipewire sample rate actually works.

**Comment by perexg** [comment]
It's unclear, if this issue is UCM related now.
