### ISSUE TITLE
direct.conf fails to work if DirectCardName is not specified

### ISSUE THREAD

**Issue by brndd** [alsa-project/alsa-ucm-conf#183]
The following error is produced when a card uses direct.conf but DirectCardName is not specified (with e.g. `Define { DirectCardName "UMC204HD" }`

```
$ spa-acp-tool -c 1 -vvvv info
variable '${var:DirectCardName}' is not defined in this context!
```

**Comment by perexg** [comment]
Already fixed in 2cc5a68e9798bc3226e2349fad5d3faa886368c1 .
