### ISSUE TITLE
failed to import acp5x use case configuration -2

### ISSUE THREAD

**Issue by DocMAX** [alsa-project/alsa-ucm-conf#184]
docmax@steamdeck: ~ $ ALSA_CONFIG_UCM=/usr/share/alsa/ucm2/ alsaucm -c acp5x set _verb HiFi
ALSA lib main.c:1541:(snd_use_case_mgr_open) error: failed to import acp5x use case configuration -2
alsaucm: error failed to open sound card acp5x: No such file or directory

Why does it fail? I have the following directory set up:

/usr/share/alsa/ucm2/conf.d/acp5x/HiFi.conf
/usr/share/alsa/ucm2/conf.d/acp5x/acp5x.conf

**Comment by perexg** [comment]
Try `alsaucm -c hw:acp5x` (you may check the card string identifier using `aplay -l` - it's the string right after `card <no>:` prefix).

**Comment by DocMAX** [comment]
Thanks, its the same:
```

docmax@steamdeck: ~ $ alsaucm -c hw:acp5x set _verb HiFi
ALSA lib main.c:1541:(snd_use_case_mgr_open) error: failed to import hw:acp5x use case configuration -2
alsaucm: error failed to open sound card hw:acp5x: No such file or directory

docmax@steamdeck: ~ $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: Generic [HD-Audio Generic], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: Generic [HD-Audio Generic], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: Generic [HD-Audio Generic], device 8: HDMI 2 [HDMI 2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: Generic [HD-Audio Generic], device 9: HDMI 3 [HDMI 3]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: acp5x [acp5x], device 0: Playback/Capture nau8821-hifi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: acp5x [acp5x], device 1: CS35L41 Stereo Playback multicodec-1 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

**Comment by DocMAX** [comment]
Nevermind. I fixed this creating a symlink to the UCM2 root.
-> /usr/share/alsa/ucm2/Cirrus/CS35L41
