### ISSUE TITLE
sof-hda-dsp: microphone device named "Headphones2"

### ISSUE THREAD

**Issue by tanuk** [alsa-project/alsa-ucm-conf#19]
I was looking at the sof-hda-dsp UCM config, and I noticed that it defines a device named "Headphones2" which seems to actually represent a microphone.

**Comment by perexg** [comment]
Usually, there's a shared jack in the system for headphones with mic so what's the issue? It's input from headphones.

**Comment by tanuk** [comment]
"Headphones with mic" is a headset, isn't it? But I assume you're not talking about a headset, since this configuration has a separate "Headset" device.

I have hard time understanding your thinking, maybe your logic is that if a jack can be used to connect either headphones or a mic, its name is always "headphone jack". In my mind it's "headphone/mic jack". I don't see the logic behind deciding that a jack is always a headphone jack if it can accept headphones. It seems arbitrary. I could as well declare that a jack should always be called a "mic jack" if it can accept a mic, and if headphones can be connected to it too, then there should be a playback device called "Mic"...

As a user, I would find it strange to see "headphones" in a recording device list. If I have a mic connected to a headphone/mic jack, I'm recording from a mic, not headphones. Therefore I think UCM should use "Mic" as the name for this device.

**Comment by perexg** [comment]
The discussion continue here:

https://gitlab.gnome.org/GNOME/libgnome-volume-control/-/merge_requests/10
