### ISSUE TITLE
USB-Audio: Motu M2: Audio interface unable to be loaded in 1.2.7.2

### ISSUE THREAD

**Issue by KevHg** [alsa-project/alsa-ucm-conf#190]
I upgraded from 1.2.6.1 to 1.2.7.2 and found that pulseaudio no longer detects my Motu M2 interface.

Main error log seems to be:
`module-alsa-card.c: Failed to find a working profile.`
`failed to load module module-alsa-card`

I'm new to debugging Linux issues, let me know what other info I can provide to help out on this topic.

**Comment by perexg** [comment]
It looks like that Motu M2 has similar USB ID 07fd:000b like Motu M4: https://github.com/alsa-project/alsa-ucm-conf/pull/158/ .

Could someone attach output from `alsa-info.sh --no-upload` ?

**Comment by sreich** [comment]
Here's mine. This is with the working 1.2.7.1, lemme know if you actually want the broken version's output instead

[alsa-info.txt](https://github.com/alsa-project/alsa-ucm-conf/files/9128478/alsa-info.txt)

**Comment by atomGit** [comment]
> Downgrading alsa-lib, alsa-ucm-conf, and lib32-alsa-lib to 1.2.7.1-1 ...

...worked for me also on Manjaro - i used the downgrade package from the AUR to get around the "Downgrading from A.L.A. is disabled on the stable branch." issue

no reboot necessary, i just power-cycled the DAC

**Comment by kiosion** [comment]
Running into this as well, thankfully downgrading worked for me as well. I've always had intermittent issues with the M2 but it seems totally borked on the latest update.

**Comment by domsch1988** [comment]
Same on my Fresh Fedora 36 Install. alsa-lib 1.2.7.2-1
Downgrade on my fresh install doesn't seem to be so easy, as there are some file collisions between the versions. If i can provide anything to help this issue, let me know.

**Comment by atomGit** [comment]
did you try downgrading only alsa-ucm-conf? that alone worked for me (as i later figured out)

**Comment by domsch1988** [comment]
Yeah i was able to downgrade alsa-ucm to 1.2.7.1-1 through a direct link rather than getting it from the repo. This worked fine. Just need to watch my updates a bit until this is getting fixed.

**Comment by sreich** [comment]
@domsch1988 been a while since i used fedora but in your /etc/dnf/dnf.conf you can add exclude=packagename

i did the same for arch so i don't have to bother with it each time until this gets fixed.

we are currently pending on someone to merge in https://github.com/alsa-project/alsa-ucm-conf/pull/191 in order to fix this. Would like to see this sooner than later, so distros can start shipping

**Comment by mrusme** [comment]
Any information on when this will land in an official release? Thank you!

**Comment by Slackadays** [comment]
This issue has made its way into Ubuntu/Pop_OS, so a release with the fix would be nice!

**Comment by devinrsmith** [comment]
I suspect I'm hitting this in Fedora now too.

**Comment by Slackadays** [comment]
Also, a quick fix I found without downgrading ALSA is this repo: [kiosion/alsa-motu-m2](https://github.com/kiosion/alsa-motu-m2)

**Comment by leonlag** [comment]
While I can get the playback to work again using either @Slackadays method or the lastest upstream patches, I'm unable to get anything from the mic input even though it does show up in pipewire.

**Comment by leonlag** [comment]
my issue seems to be an unrelated [kernel bug](https://bugzilla.kernel.org/show_bug.cgi?id=216500). Different interface but this also applies to the M2

**Comment by MartinPotierDH** [comment]
On a fresh fedora 37, downgraded alas-ucm to 1.2.7.1-1 and worked directly.
You can find the right package on the [alsa-lib-1.2.7.1-1.fc37](https://koji.fedoraproject.org/koji/buildinfo?buildID=1986294) page and go to ¨noarch¨. 

Download alsa-ucm-1.2.7.1-1.fc37.noarch.rpm`
Run `sudo dnf downgrade path/to/downloaded/rpm`
