### ISSUE TITLE
HDA ATI HDMI not supported

### ISSUE THREAD

**Issue by yangxiaohua2009** [alsa-project/alsa-ucm-conf#194]
I am using the latest ucm2 file and alsalib 

alsainfo [http://alsa-project.org/db/?f=92c58f3a6b72fee05b678386858dbc816d25dbf3](http:)

The `alsaucm reload` command returns error saying:

`ALSA lib parser.c:244:(error_node) UCM is not supported for this HDA model (HDA ATI HDMI at 0xfeb60000 irq 28)`

the HDMI works but the I2S and HDMI all use fallback ucm config.

despite the fact that I already added the acpes8336.conf in conf.d and acpes8336 folder.

**Comment by vijendarmukunda** [comment]
You should not implement UCM changes similar to acp and acp6x folders.
These changes intended for DMIC soundcard which doesn't have volume control support.
Could you try with acpes8336 card changes and attach error log?

**Comment by yangxiaohua2009** [comment]
I reverted the changes to HDA and here is the log.
by pulseaudio -vvvv I see

>I: [pulseaudio] (alsa-lib)parser.c: UCM is not supported for this HDA model (HDA ATI HDMI at 0xfeb60000 irq 28)
I: [pulseaudio] (alsa-lib)main.c: error: failed to import hw:0 use case configuration -6
I: [pulseaudio] (alsa-lib)parser.c: UCM is not supported for this HDA model (HDA ATI HDMI at 0xfeb60000 irq 28)
I: [pulseaudio] (alsa-lib)main.c: error: failed to import HDA ATI HDMI use case configuration -6
I: [pulseaudio] alsa-ucm.c: UCM not available for card HDA ATI HDMI

@vijendarmukunda 
[error.zip](https://github.com/alsa-project/alsa-ucm-conf/files/9195166/error.zip)

**Comment by vijendarmukunda** [comment]
Hi Jaroslav,

Need your help. This is blocking our driver release. we are trying to create UCM entries for I2S based sound card.

Thanks,
Vijendar

**Comment by perexg** [comment]
If the card is not covered in the UCM configuration, pulseaudio should use the legacy code. The above error should be ignored - you should check the pulseaudio log and/or use the direct ALSA tools like `aplay` to analyze the issue.

**Comment by vijendarmukunda** [comment]
@perexg : didn't get your comment. If the card is not covered in the UCM configuration .
We have created UCM files (please refer attachment acpes8336.zip) in the ticket. It should pick UCM files right?

@yangxiaohua2009 : are you able to evaluate UCM changes even though its throwing error. we have used "alsa reload" to reload cards or else you can reboot the target and give a try?

**Comment by perexg** [comment]
> @perexg : didn't get your comment. If the card is not covered in the UCM configuration . We have created UCM files (please refer attachment acpes8336.zip) in the ticket. It should pick UCM files right?

The bug report is about the HDMI issue. The HDMI outputs are driven by the different soundcard (see card 0 and card 1):

```
PLAY

**** List of PLAYBACK Hardware Devices ****
card 0: HDMI [HDA ATI HDMI], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: HDMI [HDA ATI HDMI], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: acpes8336 [acpes8336], device 0: ES8336 HiFi Play ES8316 HiFi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

This issue seems not UCM related at all. I recommend to use standard ALSA tools (aplay, speaker-test) to test the HDMI output. If it does not work - it's a driver related issue.

**Comment by vijendarmukunda** [comment]
@perexg : Card 0 related to HDMI sound card (which uses HD audio driver - sound/pci/hda) where as Card 1 is related to I2S based endpoint(driver path: sound/soc/amd). Nothing to do with HD Audio driver.

This is really old model. 
@yangxiaohua2009 : with out adding any UCM changes, could you please confirm HDMI audio works or not at your end?

**Comment by yangxiaohua2009** [comment]
@vijendarmukunda 
The HDMI works well with speaker-test
Have seem similar errors in [alsa-utils](https://github.com/alsa-project/alsa-utils/issues/101) and [here](https://bugs.gentoo.org/796536)

**Comment by vijendarmukunda** [comment]
@yangxiaohua2009 : As per logs, this platform HDMI sound card is not using UCM files. Falling back on PA profiles.
Then we can add our UCM files in /alsa/ucm2/ path and cross check the result right?

**Comment by vijendarmukunda** [comment]
@yangxiaohua2009 : When we add our UCM changes, if HDMI audio works well then we can ignore the warning. i.e. we need to select HDMI endpoint from audio settings explicitly .

Then we need to verify our I2S endpoint use cases selecting I2S endpoints .(speaker playback, Headphone playback, Headset Mic capture)

**Comment by yangxiaohua2009** [comment]
@vijendarmukunda I don't know whether this problem is related to ucm or  alsa-lib.
I can test your ucm for HDMI if you can provide one.

**Comment by yangxiaohua2009** [comment]
Also, I don't know if there would be an audio endpoint for HDMI if it's not in the ucm.

**Comment by vijendarmukunda** [comment]
@yangxiaohua2009 : this is quite older model. it seems it doesn't use UCM files for HDMI endpoint.  We tested HDMI audio endpoint by selecting HDMI audio endpoint explicitly from sound settings. we are able to hear audio on HDMI endpoint.

Please add UCM files for I2S sound card and test and confirm I2S based audio endpoint use cases.
You can ignore the warning mentioned in PA log.

**Comment by vijendarmukunda** [comment]
Earlier we supported I2S based UCM configs for Stoney platform for Chrome book platforms.
Only delta we see , we need to implement new UCM files based on Codec mixer controls.

**Comment by yangxiaohua2009** [comment]
> @yangxiaohua2009 : if all I2S endpoints based audio use cases working fine, then upstream the UCM config files.

@vijendarmukunda The problem is that when the failure of HDMI ucm (hw:0) is blocking the loading of I2S ucm (hw:1).
I already copied the right .conf and HiFi to folder ucm2/acpes8336 and ucm2/conf.d/acpes8336, but they are not working.
I can create a pr but it would be untested.
If the ucm can work well on lower Ubuntu version such as 20.04 than I may write a ucm for it.

**Comment by perexg** [comment]
@yangxiaohua2009 : Attach the full pulseaudio debug log to analyze your issue. One card should not block another.

**Comment by yangxiaohua2009** [comment]
@perexg : log here. 
[error_2.zip](https://github.com/alsa-project/alsa-ucm-conf/files/9258013/error_2.zip)
 
I use pulseaudio -vvvv to get the log. I see no log from the command `alsaucm reload`
Do you know how to get the log of `alsaucm reload` ?

**Comment by perexg** [comment]
Both HDMI devices were detected:

```
: [pulseaudio] (alsa-lib)parser.c: UCM is not supported for this HDA model (HDA ATI HDMI at 0xfeb60000 irq 31)
I: [pulseaudio] (alsa-lib)main.c: error: failed to import hw:0 use case configuration -6
I: [pulseaudio] (alsa-lib)parser.c: UCM is not supported for this HDA model (HDA ATI HDMI at 0xfeb60000 irq 31)
I: [pulseaudio] (alsa-lib)main.c: error: failed to import HDA ATI HDMI use case configuration -6
I: [pulseaudio] alsa-ucm.c: UCM not available for card HDA ATI HDMI
....
D: [pulseaudio] alsa-util.c: Trying hdmi:0 with SND_PCM_NO_AUTO_FORMAT ...
D: [pulseaudio] alsa-util.c: Managed to open hdmi:0
D: [pulseaudio] alsa-util.c: Maximum hw buffer size is 23777 ms
...
Trying hdmi:0,1 with SND_PCM_NO_AUTO_FORMAT ...
D: [pulseaudio] alsa-util.c: Managed to open hdmi:0,1
D: [pulseaudio] alsa-util.c: Maximum hw buffer size is 23777 ms
```

The I2S UCM config was not found, so legacy code is used:

```
I: [pulseaudio] (alsa-lib)main.c: error: failed to import hw:1 use case configuration -2
I: [pulseaudio] (alsa-lib)main.c: error: failed to import acpes8336 use case configuration -2
I: [pulseaudio] alsa-ucm.c: UCM not available for card acpes8336
D: [pulseaudio] conf-parser.c: Parsing configuration file '/usr/share/pulseaudio/alsa-mixer/profile-sets/default.conf'
```

You should check HDMI sinks using `pactl list sinks` commands. Also, if you are able to use `pavucontrol` utility, it will show you all available output and input streams.

**Comment by yangxiaohua2009** [comment]
> The I2S UCM config was not found, so legacy code is used:

Yes the problem is that the config is not found, despite that there is conf.d/acpes8336/acpes8336.conf in ucm2 folder.
I don't know if this is a ucm error or an alsalib error.

The streams (HDMI I2S) work well but the ucm is not working.

**Comment by vijendarmukunda** [comment]
@perexg : please suggest possible solution. By including Legacy UCM files for HDMI endpoint , on top of it adding I2S UCM files will resolve the issue?

**Comment by perexg** [comment]
Pulseaudio uses the outputs only when they are present. It seems that the HDMI driver does not detect the presence of the monitor with the audio output (using the alsa-info output from the issue description):

```
control.1 {
		iface CARD
		name 'HDMI/DP,pcm=3 Jack'
		value false                        # <<<<<<<<<<<< HERE
		comment {
			access read
			type BOOLEAN
			count 1
		}
}
control.7 {
		iface CARD
		name 'HDMI/DP,pcm=7 Jack'
		value false                        # <<<<<<<<<<<< HERE
		comment {
			access read
			type BOOLEAN
			count 1
		}
}
```

**Comment by vijendarmukunda** [comment]
@perexg : We have verified HDMI playback on this platform. We are able to get audio out. 
Attaching alsa info and Codec ELD dump for your reference.
[ELD-info.txt](https://github.com/alsa-project/alsa-ucm-conf/files/9356672/ELD-info.txt)
[alsa-info.txt](https://github.com/alsa-project/alsa-ucm-conf/files/9356674/alsa-info.txt)



@yangxiaohua2009 : Did you verified HDMI playback at your end? Did you connected Headphone jack to HDMI monitor and verified HDMI use case?
Please note , we have copied I2S UCM profiles to /usr/share/alsa/ucm2/conf.d path and rebooted target and tested HDMI playback. Its working fine at our end.
.

**Comment by perexg** [comment]
> @perexg : We have verified HDMI playback on this platform. We are able to get audio out. Attaching alsa info and Codec ELD dump for your reference. [ELD-info.txt](https://github.com/alsa-project/alsa-ucm-conf/files/9356672/ELD-info.txt) [alsa-info.txt](https://github.com/alsa-project/alsa-ucm-conf/files/9356674/alsa-info.txt)

Note that even alsactl dump in alsa-info output (line 521 to  688) does not have `HDMI/DP,pcm=? Jack` controls set to true (present) and ELD controls are empty (zero).

**Comment by vijendarmukunda** [comment]
@perexg : HDMI playback is working fine with out any issues at our end even though mentioned controls not reflected.

**Comment by vijendarmukunda** [comment]
HDMI playback is working from long time.  I2S audio endpoint support newly introduced for this platform.

**Comment by perexg** [comment]
Yes, but from my knowledge, the pulseaudio looks to the state of those controls and if the Jack controls are false, the output must be selected manually. See `pactl list cards` to get the card/port avaialbility state.

**Comment by vijendarmukunda** [comment]
[pactl_cards.txt](https://github.com/alsa-project/alsa-ucm-conf/files/9356939/pactl_cards.txt)
@perexg : I guess here we are dealing with two issues. As per issue description, HDMI audio is not working.
From pactl listing ,we can see port listing for HDMI sound card and we are not observing any issue with HDMI playback.
Other issue is adding UCM support for I2S sound card. 
As per @yangxiaohua2009 , when he add UCM files for I2S sound card in conf.d path , I2S related endpoint use cases (headphone playback/headset Mic capture/Speaker playback) are not working.

Need your inputs on adding support for I2S sound card UCM files .
As per issue description, PA is using legacy fallback method as UCM files are missing for HDMI sound card.

**Comment by vijendarmukunda** [comment]
Missing UCM files support for I2S sound card , blocking the UI based validation for production release.

**Comment by perexg** [comment]
> [pactl_cards.txt](https://github.com/alsa-project/alsa-ucm-conf/files/9356939/pactl_cards.txt) @perexg : I guess here we are dealing with two issues. As per issue description, HDMI audio is not working. From pactl listing ,we can see port listing for HDMI sound card and we are not observing any issue with HDMI playback.

Again, Jack and ELD controls should reflect the monitor state. From the pulseaudio cards dump, it seems that the controls are working for you (not sure why `alsa-info/alsactl` output is different - probably the command was ran before the monitor was connected?):

```
		hdmi-output-1: HDMI / DisplayPort 2 (type: HDMI, priority: 5800, latency offset: 0 usec, available)
			Properties:
				device.icon_name = "video-display"
				device.product.name = "LG HDR 4K"
			Part of profile(s): output:hdmi-stereo-extra1
```

The monitor name is extracted from the ELD control in pulseaudio.

> Other issue is adding UCM support for I2S sound card. As per @yangxiaohua2009 , when he add UCM files for I2S sound card in conf.d path , I2S related endpoint use cases (headphone playback/headset Mic capture/Speaker playback) are not working.
> 
> Need your inputs on adding support for I2S sound card UCM files . As per issue description, PA is using legacy fallback method as UCM files are missing for HDMI sound card.

The best way to debug UCM is to use `alsactl -c hw:0 dump text` command. Replace zero with the alsa card number (see `aplay -l`) if different. This command should dump the UCM configuration and you can verify, if all paths are fine. The `strace` output may help to see which files are touched.

**Comment by yangxiaohua2009** [comment]
@vijendarmukunda The HDMI sound works fine when the HDMI is detected. Need to edit the problem.

**Comment by perexg** [comment]
Stale. Closing.
