### ISSUE TITLE
Behringer UMC204HD audio delay

### ISSUE THREAD

**Issue by vostok01** [alsa-project/alsa-ucm-conf#198]
After update from 1.2.6.3 to 1.2.7.2, there was a desynchronization of audio and video. The sound is delayed by about 400 ms. Sometimes the out-of-sync disappears, but then it reappears. The sound is output via pulseaudio.

**Comment by perexg** [comment]
Could you test the above fix ?

**Comment by brndd** [comment]
I believe this is a PulseAudio bug, as I've heard complaints about audio delay from other people as well specifically under PulseAudio.

**Comment by vostok01** [comment]
The delay appeared after configuration files for UMC204HD were added to alsa-ucm-conf, before that everything with PulseAudio worked fine.

**Comment by perexg** [comment]
The fix should work. At least it works with my UMC204HD. PipeWire use the PCM device diffferently, so the problem is not visible.

**Comment by vostok01** [comment]
I still have a delay problem with this fix.

**Comment by brndd** [comment]
> The delay appeared after configuration files for UMC204HD were added to alsa-ucm-conf, before that everything with PulseAudio worked fine. Now I am using alsa-ucm-conf-1.2.6.3 and PulseAudio works without any delays.

That does not mean it cannot be a PulseAudio bug. It could just mean that the UCM configuration for the card triggers the PulseAudio bug.

The configuration adjusts the apparent channel layout of the device which involves some software mixing, which can apparently cause audio delay on PulseAudio if PA loopback modules become involved (possibly related bug: https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/issues/1365).

**Comment by vostok01** [comment]
> The fix should work. At least it works with my UMC204HD. PipeWire uses the PCM device diffferently, so the problem is not visible.

I replaced PulseAudio with PipeWire and the delay disappeared.

**Comment by vostok01** [comment]
I experimented a little. If the profile "Direct UMC204HD 192k" is used, then there is no delay on both PipeWire and PulseAudio. If the "Default" profile is used, then there is no delay on PipeWire, and there is a delay on PulseAudio and the sound is played with distortion - as if it is slightly accelerated.

**Comment by perexg** [comment]
Could you retest with alsa-lib 1.2.8 ?

**Comment by perexg** [comment]
Stale, closing.

**Comment by Zelaf** [comment]
I had the same issue but restarting my computer solved it for me.

```
$ alsactl -v
alsactl version 1.2.10
$ pw-cli --version
pw-cli
Compiled with libpipewire 0.3.85
Linked with libpipewire 0.3.85
```
Running on uBlue Bazzite, an image for Fedora Silverblue with Fedora 39.
