### ISSUE TITLE
Have I got a missing ucm files problem ?

### ISSUE THREAD

**Issue by xevilstar** [alsa-project/alsa-ucm-conf#204]
Hello,

this is my alsa-info
http://alsa-project.org/db/?f=cc1f9ff2eb1e223ebf6024aa1605db1d737ff5fa

I am having problems with callaudiod not finding the headset and mic on my audio cards and one of the members on the callaudiod git suggested me I am missing some ucm files ....

This is a raspberrypi4

can you please help me ?

**Comment by xevilstar** [comment]
this is my usb soundcard Bus 001 Device 006: ID 0d8c:0014 C-Media Electronics, Inc. Audio Adapter (Unitek Y-247A)

**Comment by perexg** [comment]
It seems that callaudiod is using the pulseaudio API. Those standard USB sound card do not require UCM, they should work using the legacy probe. Check your pulseaudio or pipewire installation.
