### ISSUE TITLE
veyron-i2s no hdmi sound

### ISSUE THREAD

**Issue by kapouer** [alsa-project/alsa-ucm-conf#208]
Using linux 5.19.4, and alsa-ucm-conf 1.2.7.2-1 on debian/sid,

aplay -l gives:
```
carte 0 : VEYRONI2S [VEYRON-I2S], périphérique 0 : Analog HiFi-0 [Analog HiFi-0]
  Sous-périphériques : 1/1
  Sous-périphérique #0 : subdevice #0
carte 0 : VEYRONI2S [VEYRON-I2S], périphérique 1 : HDMI i2s-hifi-1 [HDMI i2s-hifi-1 *]
  Sous-périphériques : 1/1
  Sous-périphérique #0 : subdevice #0
```

hdmi video works all right, but there is no audio.
I tried manually loading snd-soc-rk3288-hdmi-analog, without success (same aplay output).
alsamixer has a toggle for HDMI, and it is ON.

Since max98090/HiFi.conf has no mention about hdmi, i suppose something is missing there, maybe ?

Also note that I compiled linux with [several](https://github.com/hexdump0815/linux-mainline-and-mali-generic-stable-kernel/tree/master/misc.av7/patches/rk3288-improved-hdmi-timing) [patches](https://github.com/Maccraft123/Cadmium/tree/master/kernel/patches) and took debian's kernel default config for armhf,
+ CONFIG_SND_SOC_RK3288_HDMI_ANALOG=m which looked needed, but loading it has no audible effect.

**Comment by kapouer** [comment]
Interestingly it looks related to
https://chromium.googlesource.com/chromiumos/overlays/board-overlays/+/refs/heads/release-R80-12739.B/overlay-variant-veyron-speedy/chromeos-base/chromeos-bsp-speedy/files/audio-config/ucm-config/VEYRON-I2S/HiFi.conf
but I don't know if it's okay to copy parts of it here.

**Comment by perexg** [comment]
Could you attach the output from `alsa-info.sh --no-upload` ?

**Comment by kapouer** [comment]
Here's the alsa-info output:
[alsa-info.txt](https://github.com/alsa-project/alsa-ucm-conf/files/9461808/alsa-info.txt)

Adding this to Rockchip/max98090/HiFi.conf improved a lot the situation,
now I can plug hdmi cable and the sound automatically switches to hdmi panel,
and cuts the speaker sound.
However it needs to be reviewed. For example i'm not sure if EDIDFile is actually needed,
(it doesn't work without it, but maybe there's a better way).

```
SectionDevice."HDMI" {
  Comment "HDMI Jack"
  Value {
    PlaybackPriority 300
    PlaybackPCM "hw:${CardId},1"
    JackControl "HDMI Jack"
    EDIDFile "/sys/class/drm/card0-HDMI-A-1/edid"
  }
  EnableSequence [
    cset "name='Speaker Left Switch' off"
    cset "name='Speaker Right Switch' off"
  ]
  DisableSequence [
    cset "name='Speaker Left Switch' on"
    cset "name='Speaker Right Switch' on"
  ]
}
```

**Comment by perexg** [comment]
EDIDFile is probably chromiumos sound server specific settings. 

The Enable/DisableSequence is wrong. Basically, it is _NOT_ allowed to control other I/O unless the devices are conflicting. The simple configuration like:

```
SectionDevice."HDMI" {
  Comment "HDMI Jack"
  Value {
    PlaybackPriority 300
    PlaybackPCM "hw:${CardId},1"
    JackControl "HDMI Jack"
  }
```

... should work, too. Pulseaudio should switch to another output based on the priority. Perhaps, the Speaker device sequences have  missing the setting of those two controls (the chromeos configs are a bit different than in this repo).

**Comment by perexg** [comment]
Note that there's also "HDMI Switch" control which may be used in the sequences.

**Comment by kapouer** [comment]
Okay, so I tried with
```
SectionDevice."HDMI" {
  Comment "HDMI Jack"
  Value {
    PlaybackPriority 300
    PlaybackPCM "hw:${CardId},1"
    JackControl "HDMI Jack"
  }
  EnableSequence [
    cset "name='HDMI Switch' on"
  ]
  DisableSequence [
    cset "name='HDMI Switch' off"
  ]
}
```
and it seems to be willing to work, however it's not easy to check because after plugging/unplugging (hdmi or headphones) once, the same message as in [#90](https://github.com/alsa-project/alsa-lib/issues/90) appears and sound is muted.
