### ISSUE TITLE
USB-Audio: Motu M4: no duplex profile

### ISSUE THREAD

**Issue by pisquaredover6** [alsa-project/alsa-ucm-conf#214]
I have compiled alsa-ucm-conf v1.2.7.2 with the patches [3a6acaa5090a0c5a0d29c8a4906b6a60378774e2](https://github.com/alsa-project/alsa-ucm-conf/commit/3a6acaa5090a0c5a0d29c8a4906b6a60378774e2) and [ad1618cdd33f5c78ee1a0a9d3db362ffcb9f2596](https://github.com/alsa-project/alsa-ucm-conf/commit/ad1618cdd33f5c78ee1a0a9d3db362ffcb9f2596). With this, I have simplex audio, but no duplex profiles any more.

Is there any chance we can add a duplex profile, as it used to be the case before alsa-ucm-conf introduced the M4?

**Comment by perexg** [comment]
No idea what you mean with simplex and duplex in this context. Do you see the appropriate output (sinks) and input (sources) paths ?

**Comment by pisquaredover6** [comment]
Sorry for the bad wording. At the moment, there is an output profile and an input profile, but no 'duplex' profile where where output and input work simultaneously without needing a pro audio setup.

**Comment by perexg** [comment]
The currrent UCM config does not split input and output devices to different profiles. There should be one profile named "Analog Stereo Outputs + Inputs" and second "Direct /cardname/" profile. Please, attach, `pactl list` output.

**Comment by pisquaredover6** [comment]
Thank you for looking into the issue! I am using pipewire v1:0.3.58-1. This is the output of `pactl list`:
[pactl_list.txt](https://github.com/alsa-project/alsa-ucm-conf/files/9597856/pactl_list.txt)

**Comment by perexg** [comment]
The UCM is not used in your case. PW tries to do the legacy probe. Do you see any error for the `alsaucm -c hw:0 set _verb HiFi` command ?

**Comment by pisquaredover6** [comment]
There is some error, but I guess it's not about the Motu M4 on ` hw:3`. On ` hw:0` there is some internal soundcard, that I cut out from the ` pactl list` output.

```
% alsaucm -c hw:0 set _verb HiFi
ALSA lib parser.c:244:(error_node) UCM is not supported for this HDA model (HDA Intel PCH at 0xb4430000 irq 181)
ALSA lib main.c:1541:(snd_use_case_mgr_open) error: failed to import hw:0 use case configuration -6
alsaucm: error failed to open sound card hw:0: No such device or address
```

**Comment by pisquaredover6** [comment]
For hw:3 I get:
```
alsaucm -c hw:3 set _verb HiFi
ALSA lib ucm_cond.c:155:(if_eval_regex_match) RegexMatch error (If.Condition.Regex)
ALSA lib main.c:1541:(snd_use_case_mgr_open) error: failed to import hw:3 use case configuration -22
alsaucm: error failed to open sound card hw:3: Invalid argument
```

**Comment by perexg** [comment]
Oops, there's a typo in ad1618cdd33f5c78ee1a0a9d3db362ffcb9f2596. Could you try the above fix bbacb3ff2037d37acf082ca039ff675ae447bb62 ?

**Comment by pisquaredover6** [comment]
I tried it.
The error in  `alsaucm -c hw:3 set _verb HiFi` is gone now, there is no output. But the output and input profile for the Motu M4 are also gone. Attaching output of  ` pactl list`.
[pactl_list_2.txt](https://github.com/alsa-project/alsa-ucm-conf/files/9599329/pactl_list_2.txt)

**Comment by perexg** [comment]
It's difficult to tell something without debug logs, but if you are using kernel 5.19.9+ then you are most likely hitting this bug:

https://bugzilla.kernel.org/show_bug.cgi?id=216500

PW deactivated this card completely for a reason.

**Comment by pisquaredover6** [comment]
You are right, I was using a 5.19.9 kernel. After downgrading to 5.19.8, I can see the 'Analog Stereo Outputs + Inputs' profile and it works.
Thank you for the debugging and patching, and for pointing me to the kernel bug. I will watch the kernel bug ticket and close this issue.
