### ISSUE TITLE
MSI MPG Z690 EDGE WIFI DDR4 (ALC4080) microphone partially broken

### ISSUE THREAD

**Issue by micimize** [alsa-project/alsa-ucm-conf#216]
Hi – I've got the same board as #210 and some bose with a mic. While I managed to get output working on `master`, I'm having some weird issues with the mic. They may not be related to alsa, but it is very hard to tell:
* Pulse Audio can detect when it's plugged in or not, but usually has no volume indication:
  ![image](https://user-images.githubusercontent.com/8343799/191613388-28911703-5335-4705-94a0-c340791e4656.png)
*`arecord -D hw:CARD=3,DEV=0 -f dat -vvv a.wav` yields an error after a bit of output: `arecord: pcm_read:2221: read error: Input/output error`
* `pactl load-module module-loopback latency_msec=1000` does work when the right fallback is selected, but it is very quiet, as is the case in all applications I've tested so far.
* Any applications I use seem to be dropping data in some way, so "The quick brown fox" becomes something like "the qui... rown fo.." 

I know the headphones are fine because I use them all the time with my macbook.
Let me know if this seems like a different issue (and if so, if you have any advice on troubleshooting)

**Comment by perexg** [comment]
The microphone device for ALC4080 is by default DEV=2. You may test this device with `arecord`.

**Comment by micimize** [comment]
I finally got good recordings with `ffmpeg -f pulse -i alsa_input.usb-Generic_USB_Audio-00.HiFi__hw_Audio_2__source test.wav`. There may be some other issue with my setup but alsa must be working with the `v1.2.7.2` and `master` configs.
