### ISSUE TITLE
MSI MPG Z690 CARBON WIFI DDR5 S/PDIF No Audio

### ISSUE THREAD

**Issue by nphil** [alsa-project/alsa-ucm-conf#219]
Hello,

This motherboard uses realtek-alc4080 chipset, going by some of the other related issues I found the USB ID as follows:

`$ lsusb | grep 0db0`
`Bus 001 Device 003: ID 0db0:005a Micro Star International USB Audio`

Added `005a` to my USB-Audio.conf (running Manjaro) and rebooted. 

I now have audio through my optical port working just fine. Not sure how to do a pull request properly, just thought I'd share this here.

**Comment by perexg** [comment]
Thanks, added in 8a286d16218013f42cf726aed7c25216b6124da8 .
