### ISSUE TITLE
Another ALC4080 hardware identifier to add...

### ISSUE THREAD

**Issue by ethereal-engineer** [alsa-project/alsa-ucm-conf#223]
Heyo,

I just expanded the regex in 
`/usr/share/alsa/ucm2/USB-Audio/USB-Audio.conf`
to include this guy
`ID 0b05:1a16 ASUSTek Computer, Inc. USB Audio`
which is onboard a
`ROG STRIX Z690-A GAMING WIFI D4`.

Finally, front panel microphone works. I will test the digital output and all other aspects soon. Just wanted to add this ID to the growing pool of identifiers that are not covered at present.

**Comment by perexg** [comment]
Already added in e10caceaf61f3673875f236d630514ad0e747496 . Thanks.
