### ISSUE TITLE
tgl dmic volume too low

### ISSUE THREAD

**Issue by yuvalk** [alsa-project/alsa-ucm-conf#224]
x1carbon gen 9 (tiger lake)
all capture devices at max volume (mic boost, capture, dmic0 front, dmic0 rear, dmic1 2nd front, dmic1 2nd rear, PGA2.0 2 M)
still reads from mic is ~5-7% (as can be seen in `arecord -vv --format=dat /dev/null` )

device is using sof-audio-pci-intel-tgl:
```
$ sudo lspci -vvv -s 00:1f.3
00:1f.3 Audio device: Intel Corporation Tiger Lake-LP Smart Sound Technology Audio Controller (rev 20) (prog-if 80)
	Subsystem: Lenovo Device 22d5
	Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
	Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
	Latency: 64
	Interrupt: pin A routed to IRQ 185
	IOMMU group: 13
	Region 0: Memory at 603d1c8000 (64-bit, non-prefetchable) [size=16K]
	Region 4: Memory at 603d000000 (64-bit, non-prefetchable) [size=1M]
	Capabilities: [50] Power Management version 3
		Flags: PMEClk- DSI- D1- D2- AuxCurrent=55mA PME(D0-,D1-,D2-,D3hot+,D3cold+)
		Status: D0 NoSoftRst+ PME-Enable- DSel=0 DScale=0 PME-
	Capabilities: [80] Vendor Specific Information: Len=14 <?>
	Capabilities: [60] MSI: Enable+ Count=1/1 Maskable- 64bit+
		Address: 00000000fee00998  Data: 0000
	Kernel driver in use: sof-audio-pci-intel-tgl
	Kernel modules: snd_hda_intel, snd_sof_pci_intel_tgl

```

this is with linux-5.19.11 on arch linux
sof-firmware 2.2.2-1
alsa-card-profiles 1:0.3.58-1
alsa-lib 1.2.7.2-1
alsa-topology-conf 1.2.5.1-1
alsa-ucm-conf 1.2.7.2-1
alsa-utils 1.2.7-1

**Comment by yuvalk** [comment]
not even sure if I'm submitting at the right repo

**Comment by perexg** [comment]
It's better to report this here: https://github.com/thesofproject/sof/issues

Note that this hw has 4 digital microphones (so it's better to check the raw 4 channel stream).
