### ISSUE TITLE
Software volume control has very little effect on Behringer UMC204HD

### ISSUE THREAD

**Issue by Spanfile** [alsa-project/alsa-ucm-conf#230]
I'm using a Behringer UMC204HD with its UCM profile and Pipewire. The profile works fine that it properly splits the interface's four output channels into two stereo line outputs, and Pipewire is properly using them. There aren't any issues with audio crackling, latency or the sort, but the software volume control is affecting the actual volume output very little. Only the first few "notches" from 0 to 10 change the volume noticeably, however the lowest volume it allows is still somewhat loud. From there on the rest of the range doesn't change the volume much at all.

Using the Direct UCM profile lets the software volume control have much better range, but I need the Line A/B split in my setup so that profile is not an option. I haven't tried disabling UCM and configuring pro audio in Pipewire directly, but that doesn't sound like a proper fix.

It may be intentional, however? [There has been a similar issue reported to Pipewire](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2643), but it's not exactly what I'm experiencing. [I've reported this issue to them as well.](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2765)

Of course I could set the software volume to something static and control it from the interface, but the interface is physically out of reach from my hands and the software volume is easily controlled from my keyboard ;)

Kernel: 6.0.1.arch1-1
Pipewire: 0.3.59
alsa-ucm-conf: 1.2.7.2
Desktop environment: GNOME (w/ GDM)

**Comment by perexg** [comment]
Does the `alsamixer` volume for Output Front (Line A) and Output Rear (Line B) follow the PW volume control?

**Comment by perexg** [comment]
Stale, closing.
