### ISSUE TITLE
lost sound output from MOTU M2 audio interface

### ISSUE THREAD

**Issue by atomGit** [alsa-project/alsa-ucm-conf#236]
lost all sound output from my MOTO M2 audio interface as a result of the alsa-ucm-conf upgrade from 1.2.7.1 to 1.2.8

reproduce:
Manjaro
KDE/Plasma
Firefox v106.*
[MOTU M2](https://motu.com/en-us/products/m-series/m2/)
alsa-ucm-conf 1.2.7.1 / 1.2.7.2
pipewire 0.3.59-2
wireplumber 0.4.12-1
EasyEffects (+ add some effect) 6.3.0-1

if Firefox audio output is routed through EasyEffects, sound is lost

solutions:
* disable Firefox in EasyEffects
* downgrading to 1.2.7.1 + reboot (1.2.7.2 doesn’t work either)

**Comment by ebluke** [comment]
This was an issue here https://github.com/alsa-project/alsa-ucm-conf/issues/190. I currently have audio working with my m2 with Arch 6.0.6-arch1-1. Although `journalctl -p 3 -b` results in:
`pulseaudio[1132]: Failed to enable ucm device Mic2`.
`pulseaudio[1132]: Failed to enable ucm device Mic1`
Alsa-ucm-conf 1.2.7.1 was fine. 1.2.7.2 was broken. 
Arch recently updated to 1.2.8.1 https://archlinux.org/packages/extra/any/alsa-ucm-conf/

**Comment by atomGit** [comment]
for me this issue is still present with 1.2.8 and kernel 6.0.8

**Comment by perexg** [comment]
Could you attach the debug dump from the pulseaudio ?

https://fedoraproject.org/wiki/How_to_debug_PulseAudio_problems

**Comment by ebluke** [comment]
After boot.

> journalctl -p 3 -b


`Dec 05 12:19:33 turing pulseaudio[1145]: Failed to enable ucm device Mic2 `
`Dec 05 12:19:33 turing pulseaudio[1145]: Failed to enable ucm device Mic1`

> pulseaudio -vvvvv

`I: [pulseaudio] main.c: setrlimit(RLIMIT_NICE, (31, 31)) failed: Operation not permitted`
`I: [pulseaudio] main.c: setrlimit(RLIMIT_RTPRIO, (9, 9)) failed: Operation not permitted`
`D: [pulseaudio] core-rtclock.c: Timer slack is set to 50 us.`
`D: [pulseaudio] core-util.c: RealtimeKit worked.`
`I: [pulseaudio] core-util.c: Successfully gained nice level -11.`
`I: [pulseaudio] main.c: This is PulseAudio 16.1`
`D: [pulseaudio] main.c: Compilation CFLAGS: Not yet supported on meson`
`D: [pulseaudio] main.c: Running on host: Linux x86_64 6.0.11-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 02 Dec 2022 17:25:31 +0000`
`D: [pulseaudio] main.c: Found 24 CPUs.`
`I: [pulseaudio] main.c: Page size is 4096 bytes`
`D: [pulseaudio] main.c: Compiled with Valgrind support: yes`
`D: [pulseaudio] main.c: Running in valgrind mode: no`
`D: [pulseaudio] main.c: Running in VM: no`
`D: [pulseaudio] main.c: Running from build tree: no`
`D: [pulseaudio] main.c: Optimized build: yes`
`D: [pulseaudio] main.c: All asserts enabled.`
`I: [pulseaudio] main.c: Machine ID is f3ed60b1776a4dbb82c3a14b9add6543.`
`I: [pulseaudio] main.c: Session ID is 1.`
`I: [pulseaudio] main.c: Using runtime directory /run/user/1000/pulse.`
`I: [pulseaudio] main.c: Using state directory /home/ebluke/.config/pulse.`
`I: [pulseaudio] main.c: Using modules directory /usr/lib/pulseaudio/modules.`
`I: [pulseaudio] main.c: Running in system mode: no`
`E: [pulseaudio] pid.c: Daemon already running.`
`E: [pulseaudio] main.c: pa_pid_file_create() failed.`

> systemctl --user stop pulseaudio.socket

> systemctl --user stop pulseaudio.service

(some kind of seemingly infinite loop of output)

After stopping those services -> no audio.
After starting those services -> no audio...

> pulseaudio -vvvvv

            
`: [pulseaudio] main.c: setrlimit(RLIMIT_NICE, (31, 31)) failed: Operation not permitted`
`I: [pulseaudio] main.c: setrlimit(RLIMIT_RTPRIO, (9, 9)) failed: Operation not permitted`
`D: [pulseaudio] core-rtclock.c: Timer slack is set to 50 us.`
`D: [pulseaudio] core-util.c: RealtimeKit worked.`
`I: [pulseaudio] core-util.c: Successfully gained nice level -11.`
`I: [pulseaudio] main.c: This is PulseAudio 16.1`
`D: [pulseaudio] main.c: Compilation CFLAGS: Not yet supported on meson`
`D: [pulseaudio] main.c: Running on host: Linux x86_64 6.0.11-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 02 Dec 2022 17:25:31 +0000`
`D: [pulseaudio] main.c: Found 24 CPUs.`
`I: [pulseaudio] main.c: Page size is 4096 bytes`
`D: [pulseaudio] main.c: Compiled with Valgrind support: yes`
`D: [pulseaudio] main.c: Running in valgrind mode: no`
`D: [pulseaudio] main.c: Running in VM: no`
`D: [pulseaudio] main.c: Running from build tree: no`
`D: [pulseaudio] main.c: Optimized build: yes`
`D: [pulseaudio] main.c: All asserts enabled.`
`I: [pulseaudio] main.c: Machine ID is f3ed60b1776a4dbb82c3a14b9add6543.`
`I: [pulseaudio] main.c: Session ID is 1.`
`I: [pulseaudio] main.c: Using runtime directory /run/user/1000/pulse.`
`I: [pulseaudio] main.c: Using state directory /home/ebluke/.config/pulse.`
`I: [pulseaudio] main.c: Using modules directory /usr/lib/pulseaudio/modules.`
`I: [pulseaudio] main.c: Running in system mode: no`
`E: [pulseaudio] pid.c: Daemon already running.`
`E: [pulseaudio] main.c: pa_pid_file_create() failed.`

> uname -a
Linux turing 6.0.11-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 02 Dec 2022 17:25:31 +0000 x86_64 GNU/Linux

> alsa-ucm-conf 1.2.8-1

I hope this helps.

**Comment by perexg** [comment]
It does not - the daemon is running:

```
E: [pulseaudio] pid.c: Daemon already running.
```

**Comment by perexg** [comment]
Stale. Closing, re-open if required.
