### ISSUE TITLE
[Digidesign Mbox 3] Does ucm SplitPCM add latency?

### ISSUE THREAD

**Issue by ManuLinares** [alsa-project/alsa-ucm-conf#238]
https://github.com/alsa-project/alsa-ucm-conf/pull/237

I've correctly configured ucm profile, but I notice a small latency added when using UCM **vs** not using it (having the default alsa analog-surround4.0 profile)

Is this the expected behavior of SplitPCM in UCM?

**Comment by perexg** [comment]
Do you use PA ? Have you installed alsa-lib version 1.2.8 ?

**Comment by ManuLinares** [comment]
pipewire 1:0.3.59-5 (pipewire-jack, pipewire-pulse)
alsa-lib 1.2.8-1

I noticed when using carla to connect my mic to output, using the same latency config, when using UCM a little more lag.

I'm going to measure the latency now.

**Comment by ManuLinares** [comment]
Tested latency. 
"speakers -> microphone", measured with "LSP Latency Meter" in carla (Buffer size 64, Sample rate 48000), Latency in ms.

Using UCM:

38.604
38.416
38.437
38.395

Without UCM:

14.312
14.395
13.916
14.375
13.979

**Comment by perexg** [comment]
The latency is configurable. For USB profiles, the 10ms period size is the default. You may lower this value in /usr/share/alsa/ucm2/USB-Audio/USB-Audio.conf.

**Comment by ManuLinares** [comment]
> The latency is configurable. For USB profiles, the 10ms period size is the default. You may lower this value in /usr/share/alsa/ucm2/USB-Audio/USB-Audio.conf.

Indeed, lowering that variable to 1 lowered the latency to 12ms

Put this below line 233 of USB-Audio.conf
`True.Define.SplitPCMPeriodTime 1        # 0.001ms  `

Gonna test it, and submit a patch if I have no issues.
Thanks.

**Comment by ManuLinares** [comment]
> 

| SplitPCMPeriodTime | Latency |
| ------------- | ------------- |
| 4000 | 28ms |
| 1000 | 18ms |
| 1 | 12ms |

And actually setting SplitPCMPeriodTime to 1 gives me the lowest cpu usage. 🤷 ¯\_(ツ)_/¯

**Comment by perexg** [comment]
Could you show output from `cat /proc/asound/card0/sub0/pcm0*/hw_params` files when the PW is running with value 1?

**Comment by ManuLinares** [comment]
I think the "sub0" comes first, pcm0* comes after

```
$ cat /proc/asound/card3/pcm0*/sub0/hw_params
closed
closed
```

**Comment by ManuLinares** [comment]
updated my comment

**Comment by perexg** [comment]
So the lowest possible value is 500 (0.5ms) -- 1000000/(48000/24). But this is too low value for the normal operation.

If you set the direct profile (or don't use UCM) which values do you see here?

**Comment by perexg** [comment]
So it's setup for 1000000/(48000/32) -- config value approx. 667 . It's really close to 500.

**Comment by ManuLinares** [comment]
I was testing always live with `PIPEWIRE_LATENCY="64/48000" carla`

So i have (Mic1_in -->  "LSP Latency Meter" --> speaker_out) in carla, my physical microphone at 5cm of my speaker.

Carla shows (Buffer size 64, Sample rate 48000)

PD: I really thank you for your help, not very much docs for alsaucm.
