### ISSUE TITLE
HDA ALC1220 DualCodec no optical out

### ISSUE THREAD

**Issue by Almoped** [alsa-project/alsa-ucm-conf#239]
With current pipewire and alsa-ucm 1.2.8 I am unable to select profiles which has iec958 output, actually I am unable to select any card profile at all in pavucontrol. This is possibly because all the electrical output jacks are disconnected and optical out does not have jackdetect. Or maybe DualCodecs/HiFi.conf does not configure optical out.

If I remove alsa/ucm2/HDA/DualCodecs/HiFi.conf it uses alsa-card-profile/mixer/profile-sets/default.conf, goes on a probing mission I get a working optical out and the possibility to select an array of other card profiles in pavucontrol.
Can anyone recommend a better way to solve this?

I've attached pactl list cards output with working and nonworking optical out.

[pactl_no_optical.txt](https://github.com/alsa-project/alsa-ucm-conf/files/9952236/pactl_no_optical.txt)
[pactl_working_optical.txt](https://github.com/alsa-project/alsa-ucm-conf/files/9952238/pactl_working_optical.txt)

**Comment by perexg** [comment]
Could you attach output from `alsa-info.sh --no-upload` or URL, if you uploaded the diagnostic information to the ALSA server.

**Comment by Almoped** [comment]
[alsa-info.txt](https://github.com/alsa-project/alsa-ucm-conf/files/10046825/alsa-info.txt)
Alsa-info with alsa/ucm2/HDA/DualCodecs/HiFi.conf removed.

**Comment by perexg** [comment]
Could you test the above patch? You may download the updated HiFi.conf file from https://raw.githubusercontent.com/perexg/alsa-ucm-conf/issue/239/ucm2/HDA/DualCodecs/HiFi.conf .

**Comment by Almoped** [comment]
The patch allows me to select 'Default' as a card profile in pavucontrol and have working optical out. Which is a massive improvement. Thanks.

Profiles for output:iec958-ac3-surround-51: Digital Surround 5.1 (IEC958/AC3) Output
  and pro-audio: Pro Audio are still missing.
Perhaps that is a PA or PW issue, but they do show up when no matching ucm is found.

I'll attach alsa-info with the patch applied.

[alsa-info_patch.txt](https://github.com/alsa-project/alsa-ucm-conf/files/10079703/alsa-info_patch.txt)
[pactl_patch.txt](https://github.com/alsa-project/alsa-ucm-conf/files/10079707/pactl_patch.txt)

**Comment by perexg** [comment]
The pro-audio profile does not make any sense for this hardware. The ac3-surround encoder is pure PW addon. You may ask PW developers to add the support for this for the UCM PCM devices.
