### ISSUE TITLE
S/PDIF no output (Realtek® ALC4080)   

### ISSUE THREAD

**Issue by uragan1987** [alsa-project/alsa-ucm-conf#241]
http://alsa-project.org/db/?f=2f67942734d0a5123454a73ae0dcfabf508dd7f5

Bus 001 Device 003: ID 0db0:6cc9 Micro Star International USB Audio

MPG-Z590-GAMING-PLUS

No output on S/PDIF

Is there a easy fix?

**Comment by perexg** [comment]
Could you try the above patch ?

**Comment by uragan1987** [comment]
Is it enough at my alsa Version to copy ucm and ucm2 folder to /use/share/alba,  or i need to compile the last alsa LIB version

Did only copy this 2 folders, restart, but no changes, still no sound

**Comment by perexg** [comment]
You are at the right place. This UCM configuration repository describes the new hardware. I just added your USB ID - https://github.com/alsa-project/alsa-ucm-conf/commit/b121b63f30c24e89beec506ae1d2bac9ebb3cc61 - https://github.com/alsa-project/alsa-ucm-conf/blob/master/ucm2/USB-Audio/USB-Audio.conf, but the https://github.com/alsa-project/alsa-ucm-conf/blob/master/ucm2/USB-Audio/Realtek/ALC4080-HiFi.conf may require some modifications, too. The dump command I mentioned should print the configuration or an error when something is wrong.

**Comment by perexg** [comment]
And as you can see, the S/PDIF PCM device has the right default configuration in the HiFi file:

```
        SpdifName "S/PDIF Output"
	SpdifPCM "hw:${CardId},3"
	SpdifMixer "PCM"
	SpdifMindex "2"
```

**Comment by uragan1987** [comment]
used command:
`alsaucm -c hw:0 dump text`
with this output
`ALSA lib parser.c:2021:(parse_master_file) Incompatible syntax 6 in HDA-Intel.conf
ALSA lib main.c:1412:(snd_use_case_mgr_open) error: failed to import hw:0 use case configuration -22
alsaucm: error failed to open sound card hw:0: Invalid argument`

**Comment by perexg** [comment]
Upgrade alsa-lib to version 1.2.8.

**Comment by uragan1987** [comment]
Is there a way to update with "apt-get install" to 1.2.8?

**Comment by perexg** [comment]
You should use the distribution support for those questions.

**Comment by uragan1987** [comment]
http://alsa-project.org/db/?f=56170ce7348ed194f740e09c3450e375b020d24b
Got only lib to 1.2.8

Still same error

**Comment by uragan1987** [comment]
now it works, after hours of search

`alsaucm --version`  gived me the last version,  but system dont used last LIB, dunno why my system use "/usr/lib/x86_64-linux-gnu/" folder as main

if compile and make install, whole compiled files are installed to "/usr/lib64/"

so i have just copy "libasound.so.2.0.0" from "/usr/lib64/"  to "/usr/lib/x86_64-linux-gnu/"
restart and now it fixed
