### ISSUE TITLE
ALC4080 z790 apex no sound

### ISSUE THREAD

**Issue by pipes80-collab** [alsa-project/alsa-ucm-conf#257]
good evening everyone, I have a problem with the realtek alc4080 audio peripheral integrated in the Z790 apex, the peripheral connected to my yamaha 5.1 amplifier signals the pcm but no sound comes out, everything works normally under windows, I followed some solutions on the alsa-ucm configuration -conf for the device but to no avail. then invo output lsusb and aplay -l

Bus 006 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 005 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 002: ID 174c:3074 ASMedia Technology Inc. ASM1074 SuperSpeed hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 005: ID 046d:c08b Logitech, Inc. G502 SE HERO Gaming Mouse
Bus 001 Device 003: ID 054c:0ce6 Sony Corp. DualSense wireless controller (PS5)
Bus 001 Device 006: ID 195d:2030 Itron Technology iONE Func KB-460 Gaming Keyboard
Bus 001 Device 004: ID 05e3:0608 Genesys Logic, Inc. Hub
Bus 001 Device 002: ID 174c:2074 ASMedia Technology Inc. ASM1074 High-Speed hub
Bus 001 Device 009: ID 05e3:0608 Genesys Logic, Inc. Hub
Bus 001 Device 008: ID 0b05:1a52 ASUSTek Computer, Inc. USB Audio
Bus 001 Device 007: ID 0b05:18f3 ASUSTek Computer, Inc. AURA LED Controller
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
[filippo@pipes ~]$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: Audio [USB Audio], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: Audio [USB Audio], device 1: USB Audio [USB Audio #1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: Audio [USB Audio], device 2: USB Audio [USB Audio #2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: Audio [USB Audio], device 3: USB Audio [USB Audio #3]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: Controller [Wireless Controller], device 0: USB Audio [USB Audio]
  Subdevices: 1/1

**Comment by pipes80-collab** [comment]
no help?

**Comment by pipes80-collab** [comment]
problem solved with this https://github.com/alsa-project/alsa-ucm-conf/blob/master/ucm2/USB-Audio/USB-Audio.conf#L42
and this https://github.com/alsa-project/alsa-ucm-conf/blob/master/ucm2/USB-Audio/Realtek/ALC4080-HiFi.conf
Now go to try if i can enable dts-hd

**Comment by perexg** [comment]
It seems like a resolved issue with the latest configuration files.
