### ISSUE TITLE
Can not play/record with PA commands  

### ISSUE THREAD

**Issue by fchiby** [alsa-project/alsa-ucm-conf#263]
Hello @perexg, 

When I boot my board and check my amixer controls, they are set as my configuration in Bootsequence. And I can play/record music using all pcm audio devices. However, once I start pulseaudio, my controls are turned to off and can't get any sound when playing music.
I tried these steps to play/record sound using PA commands but it doesn't work: 

```
#set headphones as a default sink
$ pactl set-default-sink 0 
$ pacmd set-sink-port 0 [Out] Headphones
# set headset mic as a default source
$ pactl set-default-source 3
$ pacmd set-source-port 3 [In] Mic1
$ alsaucm  -c hw:0  set _verb HiFi set _enadev Headphones
$ alsaucm  -c hw:0  set _verb HiFi set _enadev Mic1

$ paplay music
# record audio with parecord 
parecord test.wav 
```
@perexg , do you please have an idea ?

Here my pull request concerning the alsa-ucm configuration for mt8365-evk [
ucm2: MediaTek: mt8365-evk: Add alsa-ucm support](https://github.com/alsa-project/alsa-ucm-conf/pull/260)

**Comment by perexg** [comment]
It seems like a resolved issue.
