### ISSUE TITLE
Some issue might related to alsa-ucm-conf on Dell XPS 9320

### ISSUE THREAD

**Issue by IchikaZou** [alsa-project/alsa-ucm-conf#264]
Distribution: Gentoo Linux
Kernel: 6.0.16
sof-firmware version 2.2.2
alsa-ucm-conf version: 1.2.7.2

I recently facing some problem of my laptop doesn’t have sound, I originally think it might related to sof-firmware but after kernel 6.0.13 update(sof-firmware patch included into kernel) my laptop still has no sound.

here is my original issue:
https://github.com/thesofproject/linux/issues/4128

I’m not very familiar with ALSA so not sure what’s the solution.

**Comment by perexg** [comment]
It should work with pipewire or pulseaudio. For gentoo setup (direct ALSA access), ask on the specific gentoo forums.
