### ISSUE TITLE
[BUG] Incompatible syntax 6 in sof-essx8336.conf

### ISSUE THREAD

**Issue by faerics** [alsa-project/alsa-ucm-conf#271]
Hello there. I have Infinix inbook X2 laptop with linux mint installed on it and... no sound. I created an [issue](https://github.com/thesofproject/linux/issues/3873) at sof repo, and my sound card is now (probably) exposed to userspace. 

The next step is ucm. I updated configuration as per readme.md and I got
```
alsaucm list _devices
ALSA lib parser.c:2021:(parse_master_file) Incompatible syntax 6 in sof-essx8336.conf
ALSA lib main.c:1412:(snd_use_case_mgr_open) error: failed to import hw:0 use case configuration -22
alsaucm: error failed to open sound card hw:0: Invalid argument
```
which is certainly not what it should be.
Attaching alsa-info.
[alsa-info-v6+tplg.txt](https://github.com/alsa-project/alsa-ucm-conf/files/10521451/alsa-info-v6%2Btplg.txt)

Thank you for your help

**Comment by faerics** [comment]
The problem persists event with fresh ucm2 tree v 1.2.8. 
@perexg hello, you are the one who contributed last commit into /ucm2/Intel/sof-essx8336/. Can you help with debugging?

**Comment by perexg** [comment]
Upgrade alsa-lib.

**Comment by faerics** [comment]
Thahks for answer, 
Upgraded labasound2 to 1.2.8 and now there's another error:
```
alsaucm list _devices
alsaucm: error failed to get list _devices: No such file or directory
```

Any help is appreciated :)
