### ISSUE TITLE
alsa-ucm.c: UCM not available for card sof-bytcr-rt5640

### ISSUE THREAD

**Issue by youling257** [alsa-project/alsa-ucm-conf#28]
(  30.692|   0.006) I: [pulseaudio] (alsa-lib)main.c: error: failed to import hw:0 use case configuration -2
(  30.693|   0.000) I: [pulseaudio] (alsa-lib)main.c: error: failed to import sof-bytcr-rt5640 use case configuration -2
(  30.693|   0.000) I: [pulseaudio] alsa-ucm.c: UCM not available for card sof-bytcr-rt5640

**Comment by youling257** [comment]
what's the mean of this https://github.com/alsa-project/alsa-ucm-conf/commit/d0a796a55cd0c8d2ad76fdbd590de41a0b1ac813 ?
https://github.com/alsa-project/alsa-ucm-conf/commit/08069c3a3d7883058f85de580783ea313dc54126

**Comment by youling257** [comment]
how to enable legacy card name bytcht_rt5640?
If.bytcht_rt5640 {
	Condition {
		Type String
		Haystack "${CardName}"
		Needle "bytcht rt5640"
	}
	True {
		<bytcr-rt5640/HiFi.conf>
	}

the proc/asound/cards is 
 0 [sofbytcrrt5640 ]: sof-bytcr-rt564 - sof-bytcr-rt5640
                      bytcr-rt5640-stereo-spk-in3-mic

**Comment by perexg** [comment]
The config for https://github.com/thesofproject/linux/pull/2021 .
