### ISSUE TITLE
Pinebook Pro: Speaker mute (Fn+F4) doesn't work in chroot

### ISSUE THREAD

**Issue by myself600** [alsa-project/alsa-ucm-conf#280]
**Related to #112**

### Description

While playing games with Wine (Box86), I'm unable to toggle speaker mute using Fn+F4 keys (it works outside chroot). Removing `SectionDevice."Speaker" {}` from /usr/share/alsa/ucm2/Rockchip/es8316/HiFi.conf and restarting PipeWire (`systemctl --user restart pipewire`) makes Fn+F4 work in chroot, but it reduces the maximum volume and breaks alsactl/alsaucm.

### How to reproduce

https://forum.manjaro.org/t/fn-f4-speaker-mute-doesnt-work-in-chroot/131400/4

**Comment by perexg** [comment]
It's probably a question for pipewire - https://gitlab.freedesktop.org/pipewire/pipewire/-/issues .

**Comment by myself600** [comment]
Moving to https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/3037
