### ISSUE TITLE
Headphone jack volume on ALC287 (Thinkpad X1 extreme gen 5) is too low unless the speaker channel's volume is past a certain threshold.

### ISSUE THREAD

**Issue by Noted-Jrelvas** [alsa-project/alsa-ucm-conf#298]
First of all, apologies for the verbose title.

I've ran into a very interesting issue with my Thinkpad X1 extreme gen 5's audio. For whatever reason, the headphone jack's sound output is very quiet unless I raise the speaker channel's volume past a certain threshold.

The headphone jack sounds very quiet...
![image](https://user-images.githubusercontent.com/55360900/228303084-57945125-59ba-4daf-befb-bb9e18b6f491.png)

...but raising the speaker channel's volume fixes the issue:
![image](https://user-images.githubusercontent.com/55360900/228303657-30efa3c3-2965-4b3b-a870-b4ae6e803aba.png)

I suggest automatically setting the speaker channel's volume to 100% when the headphones are plugged in and restoring it to its original volume once they're plugged out.

Here's the output given by `alsa-info.sh`:
http://alsa-project.org/db/?f=21904435b29e0eb23d2d0b30bbabe15734df7ad7

**Comment by perexg** [comment]
Does the headphone control affect the volume, too? Could you do a test with native ALSA tools without any sound server ?

**Comment by Noted-Jrelvas** [comment]
Yes, the headphone control does work as normal. (And doesn't affect speaker volume, only headphones). I will do an alsa-only test ASAP.

**Comment by Noted-Jrelvas** [comment]
Hey, just an update. I haven't been able to test without a sound server yet, but interestingly enough, I noticed that the sound is at its normal loudness shortly before the headphones' integrated mic is detected. It only gets quieter as soon as it pops up.

![image](https://user-images.githubusercontent.com/55360900/230587030-7f19e06d-8da2-4d25-9b45-64f96165cad2.png)
The sound only gets quieter when the "Headphones Stereo Microphone" channel is detected. This happens even if the speaker's channel volume is 100%, but the difference isn't so big as below the "threshold".

**Comment by Noted-Jrelvas** [comment]
Sorry for the delay @perexg. I believe I've found the underlying cause for this issue. 

This looks like a codec probing issue, not an alsa-ucm one. Thinkpad X1e/P1 gen 5 (possibly gen 4 and gen 6 as well) are probed with the outputs switched, which causes this weird behavior with the headphones. NID 0x02 should be connected to the speakers (NID 0x17), while NID 0x03 should be connected to the headphones (0x21). If I manually switch them using HDA-Analyzer, sound levels appear to be consistent.

You can go ahead and close this issue. This would have to be solved with a hda fixup for my laptop model.

Now to slowly and painfully debug the rest of this ALC287...
