### ISSUE TITLE
No sound output of headphone on Senary SN6140

### ISSUE THREAD

**Issue by pyma1** [alsa-project/alsa-ucm-conf#300]
Thinkpad L14 got a senary SN6140 codec, speaker, Dmic, headset mic works fine.
Only no sound output from headphone.

add snd-intel-dspcfg.dsp_driver=1 to kernel cmdline the issue is reproduced too.

When not fully plugin headset, it didn't trigger headphone switch, sound output can be enabled in alsamixer.

Disable pipewire or pulseaudio, the issue is the same as before.

[alsa-info.txt](https://github.com/alsa-project/alsa-ucm-conf/files/11108039/alsa-info.txt)
[alsaucm.txt](https://github.com/alsa-project/alsa-ucm-conf/files/11108047/alsaucm.txt)

Would be appreciated for your help.

**Comment by perexg** [comment]
Your problem is not UCM related. You may report this bug to the alsa-devel mailing list or to https://bugzilla.kernel.org (Audio component).

**Comment by pyma1** [comment]
Filed a kernel bug: https://bugzilla.kernel.org/show_bug.cgi?id=217345
