### ISSUE TITLE
Realtek ALC 4080 on MSI B650 Tomahawk

### ISSUE THREAD

**Issue by arleyantes** [alsa-project/alsa-ucm-conf#306]
I have Realtek ALC 4080 on an MSI B650 Tomahawk and the chip is not getting recognized, its usb id is "Bus 001 Device 003: ID 0db0:422d Micro Star International USB Audio". Manually changing the ids in ucm in File /usr/share/alsa/ucm2/USB-Audio/USB-Audio.conf made it show up correctly.

**Comment by arleyantes** [comment]
![Captura de tela de 2023-04-21 10-06-38](https://user-images.githubusercontent.com/43615658/233650829-a76dabd9-77e0-463b-a444-2659c532cd44.png)

**Comment by arleyantes** [comment]
I found someone with a similar issue under https://mailman.alsa-project.org/pipermail/alsa-devel/2023-January/210407.html which helped getting it to work.

**Comment by fxzzi** [comment]
stuff sill seems a little iffy for me.

![Image](https://github.com/user-attachments/assets/f6d3ea4d-c2c4-4dff-83ff-5e7a57405f14)

i see these errors which also causes there to be a delay in my audio working.
