### ISSUE TITLE
MSI MAG B650M Mortar Wifi Spdif input & output are reversed

### ISSUE THREAD

**Issue by RenEH01** [alsa-project/alsa-ucm-conf#311]
Hi, I have a MSI MAG B650M Mortar Wifi. I have installed this UCM conf files which provided no sound. I further installed pauvcontrol and I found changing the USB Audio device under Configuration to Pro Audio and changing the output device under Output Devices to USB Audio Pro 2 allowed for sound. 

When I select Digital Stereo (IEC958) Output under configuration I get no sound.

When I select Digital Stereo Duplex Duplex under configuration I get no sound, but there is sound under Input Devices. I believe this is reversed. I do not think this board has spdif input functionality at all. 

A side effect of using Pro Audio 2 for output is that none of my multi channel tracks are downsampled for 2.0. I'm guessing this will be resolved if the above isssue is resolved. Would that be correct?

**Comment by perexg** [comment]
Could you show output from `lsusb` ? And make sure that you rebooted if you upgraded UCM configuration. It seems that the UCM configuration is not active in your case.

**Comment by RenEH01** [comment]
Please see the screesshot below:
![Screenshot from 2023-05-06 13-42-03](https://user-images.githubusercontent.com/52057841/236645887-1e2a66fe-ede2-4413-ac90-bc2a40a0d9ec.png)

**Comment by perexg** [comment]
Ok, `0db0:7696 MSI MAG B650M Mortar Wifi` is in the current UCM configuration. You should see devices like 'Speaker', 'Front Headphones'  and 'S/PDIF output'. If you see other device names, the UCM is not active for a reason.

**Comment by RenEH01** [comment]
> Ok, `0db0:7696 MSI MAG B650M Mortar Wifi` is in the current UCM configuration. You should see devices like 'Speaker', 'Front Headphones' and 'S/PDIF output'. If you see other device names, the UCM is not active for a reason.

I thinky you are correct. Duing the booting process the command line states it found something alone the lines of Intel HDA Audio Found. I don't have any intel devices in this computer, so I find that odd. I am not getting any of the naming convention like "Front Headphones" from pavucontrol. Any idea as to why this is occuring? This is a fresh Ubuntu 22.04 install. Thanks.

**Comment by RenEH01** [comment]
Ok, one issue down. I wiped the OS and fresh installed 23.10 Ubuntu. UCM2 works and the devices are recognized, however the toslink reversed input/output issue persists. 

For future reference. It seems 22.04 is not compatible with the Realtek 4080 plus UCM2 combo.
