### ISSUE TITLE
Newest Update for Fedora 37 (alsa-ucm-1.2.9-1.fc37) causes crackling with device

### ISSUE THREAD

**Issue by ClaraCrazy** [alsa-project/alsa-ucm-conf#314]
First bug report here + not skilled with debugging, so please go easy on me :smile: 

OS: Fedora 37
Alsa-lib: 1.2.9-1
Issue: Audio crackling
Audio Device: `Logic3 TX101 5.1 Soundbar` connected via `Scarlett 2i2 3rd Gen audio interface (USB)`

Reverted lib back to `alsa-lib.1.2.8-2.fc37` (which in turn also downgraded alsa-ucm and alsa-utils again) and issues are fixed. I have no idea how to debug this, but would love to help in any way possible, sadly there was no issue template that would give me infos on what logs are useful / where to get those so uh.. please someone just point me in the right direction :)

Thanks for your time

**Comment by perexg** [comment]
Is your card detected as `Focusrite Scarlett 2i4 Gen 2` with 1.2.8 ? Also Line2 device should be present in 1.2.8, but removed in 1.2.9.

If it's correct, try 1.2.9 again and modify `/usr/share/alsa/ucm2/USB-Audio/Focusrite/Scarlett-2i-HiFi.conf` - change `PlaybackChannels` and `DirectPlaybackChannels` from 2 to 4 in `If.scarlett_2i2_gen3` block there.

**Comment by perexg** [comment]
Oops. Wrong file. It should be `/usr/share/alsa/ucm2/USB-Audio/Focusrite/Scarlett-2i.conf` of course.

**Comment by ClaraCrazy** [comment]
Well, I tried changing it to 4, but sadly that does not fix my issue. Quite the opposite in fact. When changing both values to 4, I get no audio out at all. I'll try each value at a time and will edit this in a few minutes

**Comment by AceBlade258** [comment]
I am having this issue (more of #329), but this is still open. Making the suggested change to `/usr/share/alsa/ucm2/USB-Audio/Focusrite/Scarlett-2i.conf` prevents pulseaudio from starting.

I can confirm the changes in the latest UCM configuration work.

@ClaraCrazy If you are still having this issue, try updating line 27 of `/usr/share/alsa/ucm2/USB-Audio/Focusrite/Scarlett-2i.conf` to be `Generation "3rd"`.

**Comment by perexg** [comment]
Release 1.2.10 fixed this issue.
