### ISSUE TITLE
How fix microphone for ALC4080

### ISSUE THREAD

**Issue by h4kuna** [alsa-project/alsa-ucm-conf#317]
Hello,
i'am running on Ubuntu 22.04 where is `lsa-ucm-conf 1.2.6.3-1ubuntu1.5`. The sound card does't work. I have motherboard [MAG X570S TOMAHAWK MAX WIFI](https://www.msi.com/Motherboard/MAG-X570S-TOMAHAWK-MAX-WIFI/Specification) where is `Realtek® ALC4080`. I saw, it added later. I try to use live CD ubuntu 23.04, where sound works, but microphone still doesn't work.

### Ubuntu 22.04
Output from [alsa-info](http://alsa-project.org/db/?f=d2e40705662fc6a0f9e64af8e64bfd0ded304aae)

```
lsusb | grep 'USB Audio'
Bus 003 Device 002: ID 0db0:a073 Micro Star International USB Audio
```

What can i to do for fix microphone? What do you need information?

**Comment by ksenchy** [comment]
Is it not working or is it just very low in volume? Like try shouting into it and make a recording

**Comment by h4kuna** [comment]
Hello, thank you for response.

Test is on live cd ubuntu 23.04

Really does not work.

Rear input: mic: no, headphones: yes https://youtu.be/GIOzwoSfHGk

Front input: mic: no, headphones: looks working, but hear nothing: https://youtu.be/DwqZXagaPP4

For check my headphones working
External sound card Vention: mic: yes, headphones: yes https://youtu.be/YFLmlBNFmx8

For right connection: in Windows 11 works all use cases, front / rear / mic / headphones

> In front i have four pole jack.

**Comment by perexg** [comment]
The support for 0db0:a073 was added in commit ad7b33fd49e8480910ab86574e3d422f2974a073 . I cannot verify, if the support is complete or not. I trust contributors.

Basically, UCM describes the ALSA PCM devices and mixer controls for the sound servers. I suggest to follow https://github.com/alsa-project/alsa-ucm-conf/blob/master/ucm2/DEBUG.md documentation.

**Comment by perexg** [comment]
Closing as completed.

**Comment by serhii-nakon** [comment]
@perexg I have ASUS ROG STRIX B650E-I GAMING WIFI with ALC4080 and Debian 12 with Linux 6.9 and all works fine with latest alsa-ucm-conf but my microphone 3.5 very silent and I already checked with alsamixer that this input turned to 100 percentage of volume and exactly this microphone works perfectly with my laptop and other PCs.

**Comment by serhii-nakon** [comment]
@perexg Does it possible to fix?

**Comment by serhii-nakon** [comment]
@perexg Looks like alsa does not use internal hardware amplifier for microphone inputs by some reason, It only control volume of input to ADC.

**Comment by meganukebmp** [comment]
> [@perexg](https://github.com/perexg) Looks like alsa does not use internal hardware amplifier for microphone inputs by some reason, It only control volume of input to ADC.

Where did this information come from?

**Comment by serhii-nakon** [comment]
@meganukebmp In documentation of ALC4080 exists Microphone Boost (like analog amplifier) and it has fixed values of amplification  +0db, +10db, +20db, +30db, but in Linux available to control only volume like -17.25db to +12db of microphone while this amplifier set to +0db be default or something like that

And this exactly matched with datasheet on this codec

<img width="1931" height="1367" alt="Image" src="https://github.com/user-attachments/assets/ed32e5f0-d76e-4b81-b576-9908bd7f5794" />

**Comment by serhii-nakon** [comment]
Here related ticked for Linux ALSA https://bugzilla.kernel.org/show_bug.cgi?id=218913

**Comment by serhii-nakon** [comment]
For me it seems that this codec does not expose many features through USB UAC or maybe driver in Windows by default amplify microphone like by software not by hardware

**Comment by meganukebmp** [comment]
> For me it seems that this codec does not expose many features through USB UAC or maybe driver in Windows by default amplify microphone like by software not by hardware

I've noticed the software on Windows does not amplify well either. At +30db and at 0db the difference is very minor.

**Comment by meganukebmp** [comment]
PS: I hacked the firmware installer for an MSI board which claimed to "fix microphone volume" to install on my Asus board (bypassed VID and PID) checks. This installed the MSI firmware and changed my chip's vid and PID. And I installed the MSI driver instead. It works fine with those drivers but the mic volume is still quiet all the same.
