### ISSUE TITLE
Linux Mint 21 MSI Z790-A WIFI (ALC4080) no audio from spdif

### ISSUE THREAD

**Issue by jasonzliang** [alsa-project/alsa-ucm-conf#318]
Hi,

I been troubleshooting problems with sound not coming out from my optical port and I narrowed it down to Linux having problems with the ALC4080 chipset on my MSI Z790-A WIFI motherboard (id: 0db0:d1d7). The version of alsa-ucm-conf installed on my system is 1.2.6.3-1ubuntu1.5. 

My question is, what changes do I need to make to the alsa configuration files in order to get audio working again?

Thanks

**Comment by Shmob1** [comment]
Hi, @jasonzliang I had a similar problem with my mobo, although it is a different model. I have documented it in #334. You are correct, to at least get some functionality you only need to make 2 changes, in line with those discussed & created in #229 (something like https://github.com/hwchong/alsa-ucm-conf/commit/3ec7e6e2a61240764b77c30892f0bc56803799cc, with your USD id).

Hope that helps & happy to help more if you haven't already solved this!

**Comment by perexg** [comment]
0db0:d1d7 USB ID is already in UCM configuration for ALC4080. Closing as completed.
