### ISSUE TITLE
Matebook 11 Intel 2021; always need to manually set config in amixer

### ISSUE THREAD

**Issue by adambrangenberg** [alsa-project/alsa-ucm-conf#319]
Hey, the drivers in sof got fixed but I still need to manually set the alsa config. My microphone also isn't working, not sure why. This got investigated a bit in the other issue too.

Config:

 ```bash
amixer -c 0 cset name='Headphone Switch' on
amixer -c 0 cset name='Headphone Playback Volume' 3,3
amixer -c 0 cset name='Right Headphone Mixer Right DAC Switch' on
amixer -c 0 cset name='Left Headphone Mixer Left DAC Switch' on
amixer -c 0 cset name='DAC Playback Volume' 999,999
amixer -c 0 cset name='Headphone Mixer Volume' 999,999
amixer -c 0 cset name='Differential Mux' lin1-rin1
amixer -c 0 cset name='Differential Mux' lin2-rin2
amixer -c 0 cset name='DAC Soft Ramp Switch' off
```

Issue in SOF:
https://github.com/thesofproject/sof-bin/issues/121

**Comment by perexg** [comment]
All commands are required to make sound working ?

**Comment by TigerbyteDev** [comment]
> All commands are required to make sound working ?

Yup

**Comment by perexg** [comment]
If you need to set the identical values again, it looks like a bug in the driver. The user space values should correspond to the hardware state.
