### ISSUE TITLE
Focusrite Scarlett 2i2 3rd Gen suffers from high output latency with the 1.2.9-1 update

### ISSUE THREAD

**Issue by IsaacLambat** [alsa-project/alsa-ucm-conf#329]
Hello, I have recently upgraded from `alsa-ucm-conf 1.2.8-1` to `1.2.9-1` and this has caused some latency of around 1/2 seconds for outputting audio via the `Focusrite Scarlett 2i2 3rd Gen` which is connected to the computer via USB. No latency is introduced when plugging wired headphones directly in to the motherboard so issue seems to be isolated to the device. 

I noticed the change logs indicate better support for this device was added in this version (which is great!) so these changes may have affected the existing settings of the headphones. I have downgraded only `alsa-ucm-conf` to `1.2.8-1` and the output has no latency so I am using this as a workaround.

I use PulseAudio with ALSA on Arch Linux.

Versions:
```
alsa-card-profiles - 0.3.71
alsa-lib - 1.2.9
alsa-ucm-conf - 1.2.9
alsa-utils - 1.2.9

pulseaudio - 16.1
Arch Linux - 6.3.9-arch1-1
```

dmesg detects the product as `Scarlett 2i2 USB`

Please let me know if any more information is needed (such as logs or config files) and if there is anything I should try.

Many thanks :D

**Comment by perexg** [comment]
May be similar to #314 .

**Comment by IsaacLambat** [comment]
That's worked!! Big thanks for the quick fix
