### ISSUE TITLE
Broken microphone switch on mtk-rt5650

### ISSUE THREAD

**Issue by jenneron** [alsa-project/alsa-ucm-conf#336]
The problem is that both headphones and mic use `JackControl "Headset Jack"` When there are headphones without mic connected it switches to external mic which is not present.

In kernel there appears to be only one switch https://github.com/torvalds/linux/blob/3c8b5861850c734add65233e538d4a8c2dff95d9/sound/soc/mediatek/mt8173/mt8173-rt5650.c#L130-L135 responsible for handling both headphone and microphone. So, how is userspace supposed to distinguish connection of headset and headphones?

**Comment by perexg** [comment]
You may try ask original authors https://github.com/torvalds/linux/commit/0f83f9296d5c91d08cf46cf1ba8a17fb870dedf0 . I removed JackControl lines, because in this case, user must select the correct output device manually.

**Comment by jenneron** [comment]
It is fixed in https://lore.kernel.org/alsa-devel/20230802175737.263412-1-alpernebiyasak@gmail.com/T/
