### ISSUE TITLE
MSI MAG X570S TOMAHAWK MAX WIFI - microphone + front audio panel not working - attempt 2

### ISSUE THREAD

**Issue by motomyslen** [alsa-project/alsa-ucm-conf#337]
I tried with `alsa-ucm-conf-1.2.9` but microphone still not working. Front audio panel detects headphones but no sound and mic not working as well.

If I'm not wrong ID of my device is `0db0:a073` and it was added a year ago to `USB-Audio.conf` but still something is wrong. Do I need to install alsa-utils 1.2.9?

[alsa-info.txt](https://github.com/alsa-project/alsa-ucm-conf/files/12165950/alsa-info.txt)

Related https://github.com/alsa-project/alsa-ucm-conf/issues/186

**Comment by motomyslen** [comment]
Microphone from rear panel started working after I changed `Syntax 6` to `Syntax 4` in `USB-Audio.conf`. Thanks to this comment https://github.com/alsa-project/alsa-ucm-conf/issues/186#issuecomment-1259589603.

**Comment by perexg** [comment]
We do not support old libraries.
