### ISSUE TITLE
MSI x570s Carbon Max WiFi ALC 4080

### ISSUE THREAD

**Issue by zpackrat** [alsa-project/alsa-ucm-conf#338]
Fedora 38 patched to current, issue has existed for months. Rear output jacks for Center/Sub and Rear Speakers are reversed. I use a 5.1 speaker setup. When I run sound tests in the gnome audio settings the issue is verifiable. Also audio that requires center channel for dialogue has issues. This is specifically the rear audio I/O ports.

**Comment by zpackrat** [comment]
OK, after digging, I hope this gets fixed in future releases. I have it working by modifying USB-Audio.conf uncer /usr/share/alsa/ucm2/USB-Audio/ Un-commented out the line for my mobo and added ((0db0:419c)|(0b05:1996)|(0db0:a073)) to the Regex line. Not sure if both are needed,

**Comment by perexg** [comment]
All USB IDs are in latest UCM configuration files. Closing as complete.
