### ISSUE TITLE
Front 3.5mm panel not recognized (MSI X370 Gaming Pro & MSI B450-A Pro)

### ISSUE THREAD

**Issue by fiftydinar** [alsa-project/alsa-ucm-conf#344]
Realtek ALC892 soundcard on both.

alsa-info.sh (MSI X370 Gaming Pro)
http://alsa-project.org/db/?f=26d6d5ef7701fabf260fd75e0d2bd135976019dd

alsa.info.sh (MSI B450-A Pro)
http://alsa-project.org/db/?f=621f405abe6c94f4a3069caba7ab7cb802d03563

**Comment by perexg** [comment]
The HDA hardware should be correctly described in the kernel driver. If things does not work with the latest Linux kernel, send an e-mail to linux-sound@vger.kernel.org .

**Comment by fiftydinar** [comment]
I have this issue for at least 3 years already, no matter the kernel version.

I sent an email, will report here If I get response, for the users who have the same issue as me.

**Comment by fiftydinar** [comment]
> I have this issue for at least 3 years already, no matter the kernel version.
> 
> I sent an email, will report here If I get response, for the users who have the same issue as me.

I got no response from the mail & I still have this issue.
