### ISSUE TITLE
 ASUS RoG Strix Z790-F: No SPDIF Sound output

### ISSUE THREAD

**Issue by Nightwing0815** [alsa-project/alsa-ucm-conf#348]
Hey folks,

I think, I posted in the wrong section, so here another try to get rid of no SPDIF Sound on my ASUS Motherboard.
More information can be grabbed in the topic here at [alsa-lib](https://github.com/alsa-project/alsa-ucm-conf/issues/350)

Thanks in advance,

ToM

**Comment by perexg** [comment]
Dup of #350 .
