### ISSUE TITLE
ASUS RoG Strix Z790-F: No SPDIF Sound output

### ISSUE THREAD

**Issue by Nightwing0815** [alsa-project/alsa-ucm-conf#350]
Hey guys,

what Can I do to get my optical toslink output ( pcm signal undecoded ) working?
Here are an inxi report of my system:

```
System:
  Host: Ultron Kernel: 6.1.0-1013-oem x86_64 bits: 64 compiler: N/A
    parameters: BOOT_IMAGE=/vmlinuz-6.1.0-1013-oem
    root=UUID=aa125f57-ee1e-4fd4-93fc-a77a180ec451 ro quiet splash
  Desktop: Cinnamon 5.6.8 tk: GTK 3.24.33 wm: muffin vt: 7
    dm: LightDM 1.30.0 Distro: Linux Mint 21.1 Vera base: Ubuntu 22.04 jammy
Machine:
  Type: Desktop System: ASUS product: N/A v: N/A serial: <superuser required>
  Mobo: ASUSTeK model: ROG STRIX Z790-F GAMING WIFI v: Rev 1.xx
    serial: <superuser required> UEFI: American Megatrends v: 0904
    date: 03/29/2023
Battery:
  Message: No system battery data found. Is one present?
Memory:
  RAM: total: 62.57 GiB used: 2.13 GiB (3.4%)
  RAM Report:
    unknown-error: Unknown dmidecode error. Unable to generate data.
PCI Slots:
  Unknown-error: Unknown dmidecode error. Unable to generate data.
CPU:
  Info: model: 13th Gen Intel Core i7-13700K bits: 64 type: MST AMCP
    arch: N/A family: 6 model-id: 0xB7 (183) stepping: 1 microcode: 0x113
  Topology: cpus: 1x cores: 16 mt: 8 tpc: 2 st: 8 threads: 24 smt: enabled
    cache: L1: 1.4 MiB desc: d-8x32 KiB, 8x48 KiB; i-8x32 KiB, 8x64 KiB
    L2: 24 MiB desc: 8x2 MiB, 2x4 MiB L3: 30 MiB desc: 1x30 MiB
  Speed (MHz): avg: 3100 high: 3400 min/max: 800/5300:5400:4200 scaling:
    driver: intel_pstate governor: powersave cores: 1: 1100 2: 3400 3: 3400
    4: 3400 5: 3400 6: 3400 7: 3400 8: 3400 9: 3400 10: 3400 11: 3400
    12: 3400 13: 3400 14: 3400 15: 1100 16: 3400 17: 800 18: 3400 19: 3400
    20: 3400 21: 3400 22: 3400 23: 3400 24: 3400 bogomips: 164044
Graphics:
  Device-1: NVIDIA vendor: CardExpert driver: nvidia v: 530.41.03
    alternate: nvidiafb,nouveau,nvidia_drm ports: active: none
    off: DP-1,HDMI-A-1 empty: DP-2,DP-3 bus-ID: 0000:01:00.0
    chip-ID: 10de:2782 class-ID: 0300
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: nvidia
    gpu: nvidia display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1920x2160 s-dpi: 46 s-size: 1060x1167mm (41.7x45.9")
    s-diag: 1577mm (62.1")
  Monitor-1: DP-1 pos: primary,bottom res: 1920x1080 hz: 60 dpi: 102
    size: 477x268mm (18.8x10.6") diag: 547mm (21.5")
  Monitor-2: HDMI-0 pos: primary,top res: 1920x1080 hz: 60 dpi: 38
    size: 1280x720mm (50.4x28.3") diag: 1469mm (57.8")
  OpenGL: renderer: NVIDIA GeForce RTX 4070 Ti/PCIe/SSE2
    v: 4.6.0 NVIDIA 530.41.03 direct render: Yes
Audio:
  Device-1: Intel vendor: ASUSTeK driver: snd_hda_intel v: kernel
    alternate: snd_sof_pci_intel_tgl bus-ID: 0000:00:1f.3 chip-ID: 8086:7a50
    class-ID: 0403
  Device-2: NVIDIA vendor: CardExpert driver: snd_hda_intel v: kernel
    bus-ID: 0000:01:00.1 chip-ID: 10de:22bc class-ID: 0403
  Device-3: ASUSTek USB Audio type: USB
    driver: hid-generic,snd-usb-audio,usbhid bus-ID: 1-2:2 chip-ID: 0b05:1a52
    class-ID: 0300
  Sound Server-1: ALSA v: k6.1.0-1013-oem running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: no
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Intel vendor: ASUSTeK driver: igc v: kernel port: N/A
    bus-ID: 0000:05:00.0 chip-ID: 8086:125c class-ID: 0200
  IF: eno2 state: up speed: 1000 Mbps duplex: full mac: c8:7f:54:6a:7e:55
  IP v4: 192.168.178.10/24 type: noprefixroute scope: global
    broadcast: 192.168.178.255
  IP v6: 2a02:8070:8a80:77c0:aac9:dade:e3e2:8611/64 type: temporary dynamic
    scope: global
  IP v6: 2a02:8070:8a80:77c0:64ef:c8d5:1d2b:3a7f/64
    type: dynamic mngtmpaddr noprefixroute scope: global
  IP v6: fe80::6d94:62d1:90b5:608b/64 type: noprefixroute scope: link
  IF-ID-1: virbr0 state: down mac: 52:54:00:e9:bf:38
  IP v4: 192.168.100.1/24 scope: global broadcast: 192.168.100.255
  WAN IP: 46.5.221.128
Bluetooth:
  Message: No bluetooth data found.
Logical:
  Message: No logical block device data found.
RAID:
  Hardware-1: Intel Device driver: vmd v: 0.6 port: N/A bus-ID: 0000:00:0e.0
    chip-ID: 8086:a77f rev: class-ID: 0104
Unmounted:
  Message: No unmounted partitions found.
USB:
  Hub-1: 1-0:1 info: Hi-speed hub with single TT ports: 16 rev: 2.0
    speed: 480 Mb/s chip-ID: 1d6b:0002 class-ID: 0900
  Device-1: 1-2:2 info: ASUSTek USB Audio type: Audio,HID
    driver: hid-generic,snd-usb-audio,usbhid interfaces: 8 rev: 2.0
    speed: 480 Mb/s power: 100mA chip-ID: 0b05:1a52 class-ID: 0300
  Device-2: 1-4:3 info: ASUSTek AURA LED Controller type: HID
    driver: hid-generic,usbhid interfaces: 2 rev: 2.0 speed: 12 Mb/s
    power: 16mA chip-ID: 0b05:19af class-ID: 0300 serial: 9876543210
  Hub-2: 1-10:4 info: ASMedia ASM1074 High-Speed hub ports: 4 rev: 2.1
    speed: 480 Mb/s power: 100mA chip-ID: 174c:2074 class-ID: 0900
  Device-1: 1-10.3:6 info: Fujitsu Siemens s KB955 USB Keyboard
    type: Keyboard,HID driver: hid-generic,usbhid interfaces: 2 rev: 1.1
    speed: 1.5 Mb/s power: 100mA chip-ID: 0bf8:102e class-ID: 0300
  Device-2: 1-10.4:8 info: Logitech G5 Laser Mouse type: Mouse,HID
    driver: hid-generic,usbhid interfaces: 2 rev: 2.0 speed: 12 Mb/s
    power: 98mA chip-ID: 046d:c049 class-ID: 0300
  Hub-3: 1-11:5 info: Genesys Logic Hub ports: 4 rev: 2.0 speed: 480 Mb/s
    power: 100mA chip-ID: 05e3:0608 class-ID: 0900
  Hub-4: 1-13:7 info: Genesys Logic Hub ports: 4 rev: 2.0 speed: 480 Mb/s
    power: 100mA chip-ID: 05e3:0608 class-ID: 0900
  Hub-5: 2-0:1 info: Super-speed hub ports: 8 rev: 3.1 speed: 20 Gb/s
    chip-ID: 1d6b:0003 class-ID: 0900
  Hub-6: 2-8:2 info: ASMedia ASM1074 SuperSpeed hub ports: 4 rev: 3.0
    speed: 5 Gb/s power: 8mA chip-ID: 174c:3074 class-ID: 0900
Sensors:
  System Temperatures: cpu: 32.5 C mobo: 30.0 C gpu: nvidia temp: 36 C
  Fan Speeds (RPM): fan-1: 0 fan-2: 808 fan-3: 0 fan-4: 0 fan-5: 447
    fan-6: 453 fan-7: 2288 gpu: nvidia fan: 0%
```

Thanks in advance,

ToM

**Comment by perexg** [comment]
Note that this entry was added in version 1.2.10.

**Comment by BrettRyland** [comment]
That would explain why it's not working on Ubuntu 23.04, which is using 1.2.6.3.
```bash
brett@brett-home:~/Downloads$ apt-cache policy alsa-ucm-conf
alsa-ucm-conf:
  Installed: 1.2.6.3-1ubuntu9.1
  Candidate: 1.2.6.3-1ubuntu9.1
  Version table:
 *** 1.2.6.3-1ubuntu9.1 500
        500 http://no.archive.ubuntu.com/ubuntu lunar-updates/main amd64 Packages
        500 http://no.archive.ubuntu.com/ubuntu lunar-updates/main i386 Packages
        100 /var/lib/dpkg/status
     1.2.6.3-1ubuntu8 500
        500 http://no.archive.ubuntu.com/ubuntu lunar/main amd64 Packages
        500 http://no.archive.ubuntu.com/ubuntu lunar/main i386 Packages
brett@brett-home:~/Downloads$ lsusb | grep '0b05:1a52'
Bus 001 Device 002: ID 0b05:1a52 ASUSTek Computer, Inc. USB Audio
brett@brett-home:~/Downloads$ grep -rI '0b05:1a52' /usr/share/alsa/
brett@brett-home:~/Downloads$ sudo inxi --audio --machine --system | grep Z790  # Note: Z790-F not Z790-E
  Mobo: ASUSTeK model: ROG STRIX Z790-F GAMING WIFI v: Rev 1.xx
```

Can we just add that entry into one of the files under `/usr/share/alsa/` to get this working or do we need to wait for Ubuntu 23.10?

**Comment by perexg** [comment]
1.2.6 is almost two years old. I would recommend to use alsa-lib 1.2.8+ for latest configs.

**Comment by BrettRyland** [comment]
According to https://packages.ubuntu.com/search?searchon=sourcenames&keywords=alsa-lib, the binary packages for Ubuntu 23.04 (lunar) are using 1.2.8 for libasound2, but the package for alsa-ucm-conf seems somewhat behind. This could then be a packaging issue for Ubuntu, maybe?

**Comment by BrettRyland** [comment]
OK. I did a release upgrade to Ubuntu 23.10 (`libasound2=1.2.9-2`, `alsa-ucm-conf=1.2.9-1ubuntu1`) and now I get the "HiFi 5.1 channels" profile. However, it doesn't work correctly when testing with the HE-AAC Bitstream (from https://www2.iis.fraunhofer.de/AAC/multichannel.html).
- When using "S/PDIF Output" the rear surround channels come out of the front speakers instead, i.e., RS comes out of FR and LS comes out of FL. FL, FR, FC and LFE appear to be correct though.
- When using "Speakers", only the front left and front right channels are heard, with the remaining ones being silent despite the volume meter on pavucontrol indicating that they should be producing sound.

**Comment by Nightwing0815** [comment]
@perexg @BrettRyland 

Thank you both for your effort, but I've got one question: Whats the right way to update the libs and ucm with linuxmint, which is based on 22.04? Just deleting files and extract the new ones seems not right, am I right?

ToM

**Comment by somejavadev** [comment]
@Nightwing0815 did you manage to update yours?

**Comment by Nightwing0815** [comment]
@somejavadev sadly: no I don't know, which files i have to overwrite, or which packages are to update ignoring dependencies...

**Comment by somejavadev** [comment]
@Nightwing0815 not as yet, looking at building alsa locally but not sure if that would resolve the issue. I am on ubuntu 22.04. @perexg or @BrettRyland do you perhaps have an idea on the best approach here and which steps to take? I loaded Fedora 38 but it also seems to have the same issue.

**Comment by BrettRyland** [comment]
> @Nightwing0815 not as yet, looking at building alsa locally but not sure if that would resolve the issue. I am on ubuntu 22.04. @perexg or @BrettRyland do you perhaps have an idea on the best approach here and which steps to take?

You could upgrade ubuntu to the devel-release version like I did with `sudo do-release-upgrade -d`. It has the caveats that I mentioned above though.

**Comment by Nightwing0815** [comment]
@BrettRyland I have LinuxMint 21.2 (latest release) and i want to stay with mint, so is there a solution to only upgrade the whole alsa libs and configs, without updating operating system?

**Comment by BrettRyland** [comment]
> @BrettRyland I have LinuxMint 21.2 (latest release) and i want to stay with mint, so is there a solution to only upgrade the whole alsa libs and configs, without updating operating system?

For Ubuntu, it was a matter of upgrading libasound2 and alsa-ucm-conf (plus whatever dependencies) to version 1.2.9 from versions 1.2.8 and 1.2.6 respectively. I don't know how LinuxMint's package versions are related to Ubuntu's, but if you can get those upgraded to more recent versions such that `/usr/share/alsa/ucm2/USB-Audio/USB-Audio.conf` (or similar) contains an entry for `0b05:1a52`, e.g.,
```bash
$ grep '0b05:1a52' /usr/share/alsa/ucm2/USB-Audio/USB-Audio.conf 
                # 0b05:1a52 ASUS ROG Strix Z790-E Gaming Wifi
```
then I think it ought to work.

**Comment by somejavadev** [comment]
Thanks @BrettRyland I have installed from source the following (Ubuntu LTS 22.04):

alsa-lib
alsa-utils
alsa-ucm-conf

**Install dependencies:**

```bash
sudo apt install build-essential libfuse2 automake libtool apt-file libglib2.0-dev-bin gettext libncurses5-dev git libglib2.0-dev-bin gir1.2-gtk-2.0 libgtk2.0-dev libglib2.0-dev libfltk1.3-dev libfltk1.3
```
**Configure git config:**

```
git config --global core.eol lf
git config --global core.autocrlf false
```
 **Compile Install Alsa Lib**
```
git clone https://github.com/alsa-project/alsa-lib.git
cd alsa-lib
git checkout -b tags/v1.2.10 v1.2.10
./gitcompile
sudo make install
```

 **Compile Install alsa-utils**
```
git clone https://github.com/alsa-project/alsa-utils.git
cd alsa-utils
git checkout -b tags/v1.2.10 v1.2.10
./gitcompile
sudo make install
```
**Install alsa-ucm-conf**
```
wget ttps://github.com/alsa-project/alsa-ucm-conf/archive/refs/tags/v1.2.10.tar.gz
tar xvzf v1.2.10.tar.gz -C /usr/share/alsa --strip-components=1 --wildcards "*/ucm" "*/ucm2"
````

I can see my alasa-mixer (v1.2.10) have been successfully updated:

![Screenshot from 2023-09-10 14-41-22](https://github.com/alsa-project/alsa-ucm-conf/assets/6507120/7937fbc9-84f0-460f-bddd-c88ddc7345d7)

I don't see the HiFi options in pavucontrol (version 5.0)

![Screenshot from 2023-09-10 14-43-46](https://github.com/alsa-project/alsa-ucm-conf/assets/6507120/94349360-901b-4cdf-8704-5e915ed0b68c)

Although I am not entirely sure my libasound2 has been updated/installed correctly, is there a way to verify this?

I have tried `cat /proc/asound/version` which shows:

```
Advanced Linux Sound Architecture Driver Version k6.2.0-32-generic.
```

**Comment by BrettRyland** [comment]
I don't know, sorry. It worked for me (albeit with the above mentioned caveats). I presume you have rebooted since then?
I'm on kernel `6.4.6-060406-generic` via Ubuntu's `mainline` project if that makes any difference.

**Comment by somejavadev** [comment]
No problem at all, let me check upgrading the kernel and see if it makes a difference. What I did notice is if I run: `sudo dmesg | grep 0b05` the results are:

```
[    3.969873] usb 1-6: New USB device found, idVendor=0b05, idProduct=1a53, bcdDevice= 0.14
[    5.541268] usb 1-11: New USB device found, idVendor=0b05, idProduct=18f3, bcdDevice= 1.00
``` 

The usb listed is off by one: `1a53` instead of the `1a52` although this card is listed in the UCM configs:

```
grep '0b05:1a53' /usr/share/alsa/ucm2/USB-Audio/USB-Audio.conf 
		# 0b05:1a53 ALC4082 on ASUS ROG Crosshair X670E Extreme

```

**Comment by somejavadev** [comment]
@BrettRyland interesting when running the `alsa-info.sh --no-upload` script and going through the log it seems it is still loading the older alsa-lib version. Do you perhaps remember how you installed the latest/newer version?

**Comment by somejavadev** [comment]
@BrettRyland thanks but unfortunately no luck this side. I updated the kernel and rebuilt the libraries without any luck. I could verify that the latest libs which I built are being loaded via `alsa-info.sh --no-upload`  should anyone else want to verify theirs.

**Comment by Nightwing0815** [comment]
@BrettRyland I get segmention fault error while compiling, even with oem kernel 6.5.0, so I'm not able to update ...

**Comment by somejavadev** [comment]
Update: I managed to get it to work although not perfectly or entirely. I followed these steps https://github.com/alsa-project/alsa-ucm-conf/issues/350#issuecomment-1712805898. Then it seems like the wrong sync was being used. I tested it by playing around with (It would be possible that the below work without even compiling to the latest version): 

```
aplay -D plughw:1,0 /usr/share/sounds/alsa/Front_Center.wav
aplay -D plughw:1,1 /usr/share/sounds/alsa/Front_Center.wav
aplay -D plughw:1,2 /usr/share/sounds/alsa/Front_Center.wav
```

plughw:1,2 was the one working for me. Manually calling `pacmd load-module module-alsa-sink device=hw:1,2` then makes the sound setting temporary persistent.

For some reason adding `load-module module-alsa-sink device=hw:1,2` in my `/etc/pulse/default.pa` or `~/.config/pulse/default.pa` file doesn't work to make it persistent.

It seems that my HDMI sound on my ATI 7900XT Graphics card keeps defaulting to the sync to use for some reason.

for now I have added a function in my .bashrc which I run once my PC is started

```
fix_sound() {
pacmd load-module module-alsa-sink device=hw:1,2
}
```

I still think the ucm2 configs are not being loaded since none of the HiFi profiles are shown. `dmesg` shows 

```
[    3.894813] usb 1-6: New USB device found, idVendor=0b05, idProduct=1a53, bcdDevice= 0.14
[    3.894822] usb 1-6: New USB device strings: Mfr=3, Product=1, SerialNumber=0
[    3.894825] usb 1-6: Product: USB Audio
[    3.894828] usb 1-6: Manufacturer: Generic
```

I am not entirely sure how the loading of the profiles work but it might be the regex in the in the USB-Audio.conf not picking up mine specifically. Mine is the [rog-maximus-z790](https://rog.asus.com/motherboards/rog-maximus/rog-maximus-z790-hero-model/helpdesk/)

**Comment by dougfulop** [comment]
@somejavadev your pacmd load-module command was the only solution I've found so far to get SPDIF out on my Z790 Hero. Thank you!

**Comment by BrettRyland** [comment]
Is there any progress on this for the `ROG STRIX Z790-F GAMING WIFI`? I have audio output via the S/PDIF with the `HiFi 5.1 channels` profile, but the rear channels are played over the front speakers.

**Comment by Nightwing0815** [comment]
Obviously, I had luck today with compiling, and with that command, I can hear a sound from my soundsystem:
`aplay -D plughw:1,2 /usr/share/sounds/alsa/Front_Center.wav`

How can i tell pipewire, to use this hardware?

ToM

**Comment by perexg** [comment]
@Nightwing0815 : Could you show me `amixer -c 1 info` output ?

**Comment by Nightwing0815** [comment]
@perexg : sure:
```
nightwing@Ultron:~$ amixer -c 1 info
Card sysdefault:1 'Audio'/'Generic USB Audio at usb-0000:00:14.0-2, high speed'
  Mixer name	: 'USB Mixer'
  Components	: 'USB0b05:1a52'
  Controls      : 29
  Simple ctrls  : 6

```

**Comment by perexg** [comment]
You should select the right soundcard for the alsaucm command: `alsaucm -c hw:1 dump text` . The 0b05:1a52 USB ID should use the device number 2 for S/PDIF in current configuration files: https://github.com/alsa-project/alsa-ucm-conf/blob/a0856afae4e8e071e7626958667cde049ec81e97/ucm2/USB-Audio/Realtek/ALC4080-HiFi.conf#L76-L83

**Comment by Nightwing0815** [comment]
@perexg Sorry for that, but with your command, it won't change:
```
nightwing@Ultron:~$ alsaucm -c hw:1 dump text
ALSA lib parser.c:2021:(parse_master_file) Incompatible syntax 6 in HDA-Intel.conf
ALSA lib main.c:1412:(snd_use_case_mgr_open) error: failed to import hw:1 use case configuration -22
alsaucm: error failed to open sound card hw:1: Invalid argument
```
Let me attach the alsa-info script, I think, this will help you a lot: [click me softly](http://alsa-project.org/db/?f=63f0fc3b701ed8b8d27252987e21e7902640cf8a)

ToM

**Comment by perexg** [comment]
The card number is assigned dynamically and I just collected the number from your previous posts. Use `aplay -l` command or `cat /proc/asound/cards` to look for the current USB card number. With latest alsa-info, the number is 2.

**Comment by Nightwing0815** [comment]
```
nightwing@Ultron:~$ alsaucm -c hw:2 dump text
ALSA lib parser.c:2021:(parse_master_file) Incompatible syntax 6 in USB-Audio.conf
ALSA lib main.c:1412:(snd_use_case_mgr_open) error: failed to import hw:2 use case configuration -22
alsaucm: error failed to open sound card hw:2: Invalid argument

```

**Comment by perexg** [comment]
As discussed many times here. You are using old version of alsa-lib package. I cannot help you.

**Comment by Nightwing0815** [comment]
I just [compiled the 1.2.10 version](https://github.com/alsa-project/alsa-ucm-conf/issues/350#issuecomment-1712805898), is there a newer one?

**Comment by perexg** [comment]
But it's not installed in your system. 1.2.8+ should be fine.

**Comment by Nightwing0815** [comment]
Okay thank you very much. I think, I need to wait til may, when linuxmint will use the ubuntu 24.04 base, am I right?

ToM

**Comment by Nightwing0815** [comment]
@perexg got a hint in mint-forums for a [workaround](https://forums.linuxmint.com/viewtopic.php?p=2336249#p2336249)

I've got now SPDIF working, only on 2 front channels, no profile available, no pcm. But it's a huge progress!
Now, I don't need to turn on my TV for listening to music. :+1: 

Here's my new output from command `alsaucm -c hw:2 dump text`:
```
nightwing@Ultron:~$ alsaucm -c hw:2 dump text
ALSA lib parser.c:1866:(parse_master_section) unknown field 0g0�� in master section
ALSA lib parser.c:937:(parse_sequence) error: sequence command 'disdevall' is ignored
Verb.HiFi {
	Device.Speaker {
		Comment Speakers
		Values {
			CaptureCTL "_ucm0001.hw:Audio"
			JackControl "Speaker - Output Jack"
			PlaybackCTL "_ucm0001.hw:Audio"
			PlaybackChannels 2
			PlaybackMixerElem PCM,0
			PlaybackPCM "_ucm0001.hw:Audio"
			PlaybackPriority 200
			TQ HiFi
		}
	}
	Device.Headphones {
		Comment "Front Headphones"
		Values {
			CaptureCTL "_ucm0001.hw:Audio"
			JackControl "Headphone - Output Jack"
			PlaybackCTL "_ucm0001.hw:Audio"
			PlaybackMixerElem PCM,1
			PlaybackPCM "_ucm0001.hw:Audio,1"
			PlaybackPriority 300
			TQ HiFi
		}
	}
	Device.SPDIF {
		Comment "S/PDIF Output"
		Values {
			CaptureCTL "_ucm0001.hw:Audio"
			PlaybackCTL "_ucm0001.hw:Audio"
			PlaybackMixerElem PCM,2
			PlaybackPCM "_ucm0001.hw:Audio,2"
			PlaybackPriority 100
			TQ HiFi
		}
	}
	Device.Line1 {
		Comment "Line Input"
		Values {
			CaptureCTL "_ucm0001.hw:Audio"
			CaptureMixerElem Line,0
			CapturePCM "_ucm0001.hw:Audio,1"
			CapturePriority 100
			JackControl "Line - Input Jack"
			PlaybackCTL "_ucm0001.hw:Audio"
			TQ HiFi
		}
	}
	Device.Mic1 {
		Comment Microphone
		Values {
			CaptureCTL "_ucm0001.hw:Audio"
			CaptureMixerElem Mic,0
			CapturePCM "_ucm0001.hw:Audio,2"
			CapturePriority 300
			JackControl "Mic - Input Jack"
			PlaybackCTL "_ucm0001.hw:Audio"
			TQ HiFi
		}
	}
}
```

ToM

**Comment by perexg** [comment]
Thanks for this update.

I'm closing this bug, because things seem to be fixed. The support for ubuntu/debian with old libraries is really pain. The Syntax changes are not recommended, because other USB hardware variants are using newer configuration syntax, so you can screw things for other USB hardware.

**Comment by BrettRyland** [comment]
Should I open a new issue for the misconfiguration that I reported [above](https://github.com/alsa-project/alsa-ucm-conf/issues/350#issuecomment-1739234512) then?

<details>
<summary>apt-cache policy alsa-utils</summary>

```
alsa-utils:
  Installed: 1.2.9-1ubuntu1
  Candidate: 1.2.9-1ubuntu1
  Version table:
 *** 1.2.9-1ubuntu1 500
        500 http://no.archive.ubuntu.com/ubuntu mantic/main amd64 Packages
        100 /var/lib/dpkg/status
```
</details>
<details>
<summary>amixer -c 1 info</summary>

```
Card sysdefault:1 'Audio'/'Generic USB Audio at usb-0000:00:14.0-2, high speed'
  Mixer name  : 'USB Mixer'
  Components  : 'USB0b05:1a52'
  Controls      : 29
  Simple ctrls  : 6
```
</details>
<details>
<summary>alsaucm -c hw:1 dump text</summary>

```
Verb.HiFi {
  Comment "HiFi 2.0 channels"
  Device.Speaker {
    Comment Speakers
    Values {
      CaptureCTL "_ucm0001.hw:Audio"
      JackControl "Speaker - Output Jack"
      PlaybackCTL "_ucm0001.hw:Audio"
      PlaybackChannels 2
      PlaybackMixerElem PCM,0
      PlaybackPCM "_ucm0001.hw:Audio"
      PlaybackPriority 200
      TQ HiFi
    }
  }
  Device.Headphones {
    Comment "Front Headphones"
    Values {
      CaptureCTL "_ucm0001.hw:Audio"
      JackControl "Headphone - Output Jack"
      PlaybackCTL "_ucm0001.hw:Audio"
      PlaybackMixerElem PCM,1
      PlaybackPCM "_ucm0001.hw:Audio,1"
      PlaybackPriority 300
      TQ HiFi
    }
  }
  Device.SPDIF {
    Comment "S/PDIF Output"
    Values {
      CaptureCTL "_ucm0001.hw:Audio"
      PlaybackCTL "_ucm0001.hw:Audio"
      PlaybackMixerElem PCM,2
      PlaybackPCM "_ucm0001.hw:Audio,2"
      PlaybackPriority 100
      TQ HiFi
    }
  }
  Device.Line1 {
    Comment "Line Input"
    Values {
      CaptureCTL "_ucm0001.hw:Audio"
      CaptureMixerElem Line,0
      CapturePCM "_ucm0001.hw:Audio,1"
      CapturePriority 100
      JackControl "Line - Input Jack"
      PlaybackCTL "_ucm0001.hw:Audio"
      TQ HiFi
    }
  }
  Device.Mic1 {
    Comment Microphone
    Values {
      CaptureCTL "_ucm0001.hw:Audio"
      CaptureMixerElem Mic,0
      CapturePCM "_ucm0001.hw:Audio,2"
      CapturePriority 300
      JackControl "Mic - Input Jack"
      PlaybackCTL "_ucm0001.hw:Audio"
      TQ HiFi
    }
  }
}
Verb."HiFi 5+1" {
  Comment "HiFi 5.1 channels"
  Device.Speaker {
    Comment Speakers
    Values {
      CaptureCTL "_ucm0001.hw:Audio"
      JackControl "Speaker - Output Jack"
      PlaybackCTL "_ucm0001.hw:Audio"
      PlaybackChannels 6
      PlaybackMixerElem PCM,0
      PlaybackPCM "_ucm0001.hw:Audio"
      PlaybackPriority 200
      TQ HiFi
    }
  }
  Device.Headphones {
    Comment "Front Headphones"
    Values {
      CaptureCTL "_ucm0001.hw:Audio"
      JackControl "Headphone - Output Jack"
      PlaybackCTL "_ucm0001.hw:Audio"
      PlaybackMixerElem PCM,1
      PlaybackPCM "_ucm0001.hw:Audio,1"
      PlaybackPriority 300
      TQ HiFi
    }
  }
  Device.SPDIF {
    Comment "S/PDIF Output"
    Values {
      CaptureCTL "_ucm0001.hw:Audio"
      PlaybackCTL "_ucm0001.hw:Audio"
      PlaybackMixerElem PCM,2
      PlaybackPCM "_ucm0001.hw:Audio,2"
      PlaybackPriority 100
      TQ HiFi
    }
  }
  Device.Line1 {
    Comment "Line Input"
    Values {
      CaptureCTL "_ucm0001.hw:Audio"
      CaptureMixerElem Line,0
      CapturePCM "_ucm0001.hw:Audio,1"
      CapturePriority 100
      JackControl "Line - Input Jack"
      PlaybackCTL "_ucm0001.hw:Audio"
      TQ HiFi
    }
  }
  Device.Mic1 {
    Comment Microphone
    Values {
      CaptureCTL "_ucm0001.hw:Audio"
      CaptureMixerElem Mic,0
      CapturePCM "_ucm0001.hw:Audio,2"
      CapturePriority 300
      JackControl "Mic - Input Jack"
      PlaybackCTL "_ucm0001.hw:Audio"
      TQ HiFi
    }
  }
}
Verb."HiFi 7+1" {
  Comment "HiFi 7.1 channels"
  Device.Speaker {
    Comment Speakers
    Values {
      CaptureCTL "_ucm0001.hw:Audio"
      JackControl "Speaker - Output Jack"
      PlaybackCTL "_ucm0001.hw:Audio"
      PlaybackChannels 8
      PlaybackMixerElem PCM,0
      PlaybackPCM "_ucm0001.hw:Audio"
      PlaybackPriority 200
      TQ HiFi
    }
  }
  Device.Headphones {
    Comment "Front Headphones"
    Values {
      CaptureCTL "_ucm0001.hw:Audio"
      JackControl "Headphone - Output Jack"
      PlaybackCTL "_ucm0001.hw:Audio"
      PlaybackMixerElem PCM,1
      PlaybackPCM "_ucm0001.hw:Audio,1"
      PlaybackPriority 300
      TQ HiFi
    }
  }
  Device.SPDIF {
    Comment "S/PDIF Output"
    Values {
      CaptureCTL "_ucm0001.hw:Audio"
      PlaybackCTL "_ucm0001.hw:Audio"
      PlaybackMixerElem PCM,2
      PlaybackPCM "_ucm0001.hw:Audio,2"
      PlaybackPriority 100
      TQ HiFi
    }
  }
  Device.Line1 {
    Comment "Line Input"
    Values {
      CaptureCTL "_ucm0001.hw:Audio"
      CaptureMixerElem Line,0
      CapturePCM "_ucm0001.hw:Audio,1"
      CapturePriority 100
      JackControl "Line - Input Jack"
      PlaybackCTL "_ucm0001.hw:Audio"
      TQ HiFi
    }
  }
  Device.Mic1 {
    Comment Microphone
    Values {
      CaptureCTL "_ucm0001.hw:Audio"
      CaptureMixerElem Mic,0
      CapturePCM "_ucm0001.hw:Audio,2"
      CapturePriority 300
      JackControl "Mic - Input Jack"
      PlaybackCTL "_ucm0001.hw:Audio"
      TQ HiFi
    }
  }
}
```
</details>

**Comment by perexg** [comment]
For S/PDIF device: The audio server should take UCM devices named as SPDIF (or SPDIF1/SPDIF2 etc.) as digital outputs and look for IEC958 controls to set the pass-through mode. It's not UCM thing. You should ask sound server developers to add proper support for the S/PDIF pass-through mode.

For channel positions: ALSA API has PCM channel mapping extension. For USB devices, the positions should be described in USB descriptors. Thus the driver is responsible to pass correct positions to applications. You may check `/proc/asound/card?/stream?` contents to get the positions obtained from hardware. If hardware does not provide correct list, we may eventually override this in UCM or driver. The driver is definitely best option, because all installations (event without UCM/sound servers) can benefit from it. So, I suggest to create a new discussion at linux-sound@vger.kernel.org about this issue. Also pipewire probably does not support channel mapping API  by default: https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2648 . But it's sound server issue.

**Comment by BrettRyland** [comment]
ok, thanks

**Comment by perexg** [comment]
Could you report this to pipewire ? UCM devices should have `use-chmap` flag enabled by default.

**Comment by BrettRyland** [comment]
> Could you report this to pipewire ? UCM devices should have `use-chmap` flag enabled by default.

OK, reported here [3801](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/3801).

**Comment by dtl131** [comment]
@perexg : I'm a bit confused on why the OP did not have the necessary components for libasound 1.2.10 after installing it manually and the ALSA info reporting 1.2.10 for the version of ALSA lib.

I was going to tell the OP to try upgrading libasound through PPA, but I wasn't sure if that would work since the user built and installed alsa-lib locally. https://launchpad.net/~dtl131/+archive/ubuntu/mediahacks2?field.series_filter=jammy
