### ISSUE TITLE
UCM is not supported for this HDA model (HDA NVidia at 0xfc080000 irq 130) - how to disable HDA Nvidia?

### ISSUE THREAD

**Issue by motomyslen** [alsa-project/alsa-ucm-conf#384]
I upgraded my system and all microphones stopped working. Before that I had loaded custom UCM configs to make my microphone working.
Upgrades which can be related to the issue:
- `alsa-ucm-conf:all 1.2.6.3-1ubuntu1.4 1.2.6.3-1ubuntu1.9`
- `nvidia-driver-510:amd64 510.108.03-0ubuntu0.22.04.1 525.147.05-0ubuntu0.22.04.1`

After OS upgrade I loaded again all latests UCM configs from the repo. I also tried older which I had but the error is the same.

First issue:
```
alsaucm reload;
ALSA lib parser.c:2021:(parse_master_file) Incompatible syntax 6 in HDA-Intel.conf
ALSA lib main.c:1412:(snd_use_case_mgr_open) error: failed to import hw:0 use case configuration -22
alsaucm: error failed to open sound card hw:0: Invalid argument
```
I fixed it by changing syntax from 6 to 4 in HDA-Intel.conf. It worked for me before OS upgrade.

Next issue:
```
$ alsaucm reload;
ALSA lib parser.c:243:(error_node) UCM is not supported for this HDA model (HDA NVidia at 0xfc080000 irq 130)
ALSA lib main.c:1412:(snd_use_case_mgr_open) error: failed to import hw:0 use case configuration -6
alsaucm: error failed to open sound card hw:0: No such device or address
```
I tried to disable HDA Nvidia module from loading by adding `snd_hda_codec_hdmi` to `/etc/modprobe.d/blacklist.conf` but it didn't work.

How to solve this issue? I don't need audio through HDMI. It would be nice to have it working without any hacks but disabling it is enough for me. Can I somehow disable HDA Nvidia in UCM?
I can't downgrade Nvidia driver because I need that.

[alsa-info.txt](https://github.com/alsa-project/alsa-ucm-conf/files/13942996/alsa-info.txt)

**Comment by motomyslen** [comment]
I run `alsactl init` it showed me that one more HDA-Intel.conf has invalid syntax. I set it to 4 instead of 6 and my microphone started working.

**Comment by perexg** [comment]
The packages are really old. You should handle those issues with your distribution maker.
