### ISSUE TITLE
Asus ROG Strix Z790-A Gaming WIFI II audio codec detected as generic USB audio, headphones and SPDIF not working

### ISSUE THREAD

**Issue by danielton1** [alsa-project/alsa-ucm-conf#394]
Hi, I have an Asus ROG STRIX Z790-A GAMING WIFI II motherboard with a Realtek ALC4080 audio codec. Sound is working through the speakers via the line out jack, and it does detect when I plug headphones in, but everything I'm finding is that the ALSA UCM is failing to detect the device as a Realtek ALC4080 and instead is just using a generic USB profile, probably due to the USB ID being unknown. Audio always comes out the line out jack no matter what is plugged in to the front panel or SPDIF or how pipewire/ALSA are configured.

This is what lsusb gives as the ID:
Bus 001 Device 002: ID 0b05:1af1 ASUSTek Computer, Inc. USB Audio

This is the output of alsa-info.sh: http://alsa-project.org/db/?f=3dc5eb049583da76a18466a6cf16d144dae95f53

I've tried modifying the files in /usr/share/alsa/ucm2/USB-Audio several different ways per several forum threads I came across online and ended up with no sound at all, so I'm not sure what's going on or how to fix this. Any help would be greatly appreciated!

**Comment by perexg** [comment]
Please, test the above change.

**Comment by danielton1** [comment]
Thank you so much! That fixed it!
