### ISSUE TITLE
MAG Z790 TOMAHAWK WIFI DDR4 no Sound Front Audio Realtek 4080

### ISSUE THREAD

**Issue by Acer6920** [alsa-project/alsa-ucm-conf#395]
Greetings,

back audio is working the sound card is recognized as Generic USB Audio
3 [Audio ]: USB-Audio - USB Audio Generic USB Audio at usb-0000:00:14.0-11, high speed

alsa information:
http://alsa-project.org/db/?f=655312de1f9b11ddc33de5fa41c6cad87bcbab9d

if i missed something excuse it please i use zorin os/linux since yesterday and need some advice if you need more information.

thanks a lot.

ace

**Comment by perexg** [comment]
USB ID 0db0:a74b is already registered in the latest UCM configuration. See https://github.com/alsa-project/alsa-ucm-conf/blob/master/README.md or upgrade your alsa-ucm-conf package to latest (1.2.11).

**Comment by Acer6920** [comment]
Thank you for the feedback i just saw the msi board and missread the ID in the list.
I had to change the Syntax from 6 to 4 and now front audio jack is working.

**Comment by Acer6920** [comment]
Done
