### ISSUE TITLE
ASUS VivoBook Pro 14: platform::micmute led not working

### ISSUE THREAD

**Issue by Dinolek** [alsa-project/alsa-ucm-conf#400]
There is `/sys/class/leds/platform::micmute` from `asus-nb-wmi`, but `snd_ctl_led` isn't loaded.
Microphone isn't connected to acp, so `snd_rn_pci_acp3x` isn't getting loaded.

I can get led switching working if I attach 'Capture Switch'

```
modprobe snd_ctl_led
echo 'Capture Switch' > /sys/class/sound/ctl-led/mic/card1/attach
```

[alsa-info](http://alsa-project.org/db/?f=05aff573aedf6ddd6954ca739d8de8f827a78e86)

**Comment by perexg** [comment]
For standard HDA hardware, audio LED triggers are activated only for specific models using quirks. It's not a job for UCM at the moment. You may discuss this in linux-sound@vger.kernel.org mailing list.
