### ISSUE TITLE
[Remove Mbox3 UCM] Request to revert pull 237

### ISSUE THREAD

**Issue by ManuLinares** [alsa-project/alsa-ucm-conf#412]
https://github.com/alsa-project/alsa-ucm-conf/pull/237

The SplitPCM adds not only latency, https://github.com/alsa-project/alsa-ucm-conf/issues/238 but other general issues when streaming, etc.

So I propose removing the UCM profile.

**Comment by perexg** [comment]
The issues should be debugged (probably report this in alsa-lib with some debug info - the best way is to reproduce the issue without additional software like sound servers). Also, UCM is capable to avoid using the share plugin from alsa-lib and the sound server can obtain only information for the channel split operation. And for the last, users can always select the direct UCM profile.
