### ISSUE TITLE
Virtual nodes created by UCM rules have the exact same nick, making them indistinguishable in KDE's audio applet

### ISSUE THREAD

**Issue by z411** [alsa-project/alsa-ucm-conf#426]
Hello,

Recently KDE Plasma's applet started using the node's nick to show the name of the device. The problem is that for audio interfaces that separate their inputs into virtual interfaces, they end up with something like this:

```
alsa.card_name = "Volt 2"
device.profile.description = "Mono Input 1"
node.description = "Volt 2 Mono Input 1"
node.nick = "Volt 2"
```

```
alsa.card_name = "Volt 2"
device.profile.description = "Mono Input 2"
node.description = "Volt 2 Mono Input 2"
node.nick = "Volt 2"
```

Since they use the same nick, the end result is that we end up with an input list that looks like this:

![image](https://github.com/alsa-project/alsa-ucm-conf/assets/1988512/34e794ce-07ce-45b8-8be4-073dad24d339)

Could the node nick be changed to reflect that this is a virtual device that refers to a different input from the same device? We already have an issue about this open in PipeWire and KDE issue trackers but we're not sure where this should be really fixed.

Thanks.

**Comment by perexg** [comment]
UCM does not create / define those nicks. The sound server is responsible.

**Comment by z411** [comment]
I see, I'll report this to PipeWire. Thank you.
