### ISSUE TITLE
ALC4080 onboard audio support on the MSI X870 Tomahawk motherboard

### ISSUE THREAD

**Issue by nfp0** [alsa-project/alsa-ucm-conf#455]
@perexg As mentioned [here](https://github.com/alsa-project/alsa-ucm-conf/issues/447#issuecomment-2431686575), it seems the ALC4080 audio on the new MSI X870 Tomahawk motherboard is not supported.

USB ID is `0db0:cd0e`

I have tested adding `cd0e` on the `USB-Audio.conf` file like so:
```
Regex "USB((0414:a0(0e|1[0124]))|(0b05:(19(84|9[69])|1a(16|2[07]|5[23c]|97|f1)))|(0db0:(cd0e|005a|124b|151f|1feb|3130|36e7|4(19c|22d|240|88c)|62a4|6c[0c]9|70d3|7696|82c7|8af7|961e|a(073|228|47c|74b)|b202|d1d7|d6e7))|(26ce:0a0[68]))"
```

With this, the microphone now seems to be correctly mapped and works. But the problem is that it's volume is way too low.
It is set to 100% in both KDE and alsamixer (it's the Line one).

![image](https://github.com/user-attachments/assets/034e8f45-9e17-4338-9c1b-fda0b56dae29)

How can I help solve this problem? Should I open a separate issue?

**Comment by nfp0** [comment]
@perexg Sorry, I forgot to attach the output of `alsa-info.sh --no-upload`.
[alsa-info.txt](https://github.com/user-attachments/files/17490268/alsa-info.txt)

**Comment by nfp0** [comment]
I have also noticed that the output volume is also quite low by default.

ALSA looks like this by default:

![image](https://github.com/user-attachments/assets/06258634-e8d3-4f09-9df6-a7534770ef7f)

With ALSA set like this, it's not possible to achieve a high volume, on KDE, for example.

Is this situation normal or is it caused by alsa-ucm-conf not yet supporting this motherboard?
I'm not very knowledgeable about the Linux sound stack, so please tell me if I'm posting this issue in the wrong project.

**Comment by ykonoclast** [comment]
I have similar audio problems with the same motherboard :

- Audio output working from the back motherboard jack port

- No audio output from front jack port, even though headphone is detected : it appears in the list of audio devices (in Gnome parameters) but, when selected, audio is still outputed by the speakers (plugged at the back). Unplugging the speakers and plugging the headphone to the back MoBo port makes it work, though it is impractical.

- No microphone input working at all (front AND back) even though, like above, microphone is detected and appears in input devices list. There is no sound recorded (changing volume levels doesn’t work).

- When in audio conferences, system sounds are transmitted to others : they don’t hear the microphone but they hear error bells, clicks on sliders etc. There seems to be some piping problem here.

**Comment by bojankseneman** [comment]
I was experiencing the same issue on my Asus X670E-F.
I've modified the regex in alsa conf locally so it doesn't load ALC4080 driver and instead uses the generic driver which has normal audio volume.
As for the microphone low level, I gave up and I just bought a 10$ USB sound online and plugged the microphone into it.
Good luck solving this the proper way. I keep my fingers crossed for you.

**Comment by nfp0** [comment]
@bojankseneman In this motherboard's case (X870 Tomahawk), if we don't load the ALC4080 driver, we don't get microphone input at all, so that is not an option. But thank you for the input.

**Comment by perexg** [comment]
> I've modified the regex in alsa conf locally so it doesn't load ALC4080 driver and instead uses the generic driver which has normal audio volume.

The UCM device should handle volume in similar way as direct ALSA devices, because UCM is on top of the standard USB driver. Something is probably misconfigured for your case. Create another report and try to find differences between volume setup for your generic way and standard UCM way (check alsamixer or so to look for ALSA volume changes).

**Comment by nfp0** [comment]
@perexg What should I do about the volume situation I mentioned previously? Should I also open another issue here?
If not, what's the correct project to open an issue at?

**Comment by perexg** [comment]
If the ALSA USB driver cannot set the proper volume, then it's a driver support fault. See https://github.com/alsa-project/alsa-ucm-conf/blob/master/ucm2/DEBUG.md#checking-of-the-corresponding-simple-mixer-name . Basically, if you cannot set volume using a direct ALSA mixer tool like alsamixer, UCM won't help.

It seems that ALC4080 hardware have more firmware variants and it's not clear how the volume should be handled correctly. The information exposed using USB Audio protocol (specification) seems incomplete. Someone with a reverse engineering knowledge may catch and analyze the USB audio packets from the Windows driver to add missing parts to the Linux driver.

Another possibility is that the microphone volume control is limited for this hardware and digital gain should be increased.  There's possibility to increase this gain using `pactl` or `wpctl` tool like:

```
pactl set-source-volume alsa_input.usb-C-Media_Electronics_Inc._KURZWEIL_Pro_Microphone_KM-1U-00.analog-stereo 200%
# ... or pipewire alternative ...
wpctl set-volume @DEFAULT_AUDIO_SOURCE@ 2.0
```

**Comment by nfp0** [comment]
Yes, digital gain certainly works around the issue, as I've tried it, but I was trying to understand if this is a normal expected out-of-the-box experience and if not, where to report it.
Thank you for the clarification.

Indeed it's not possible to raise the volume any further with any ALSA tools such as `alsamixer` or `amixer`. And as you said, there seem to be multiple ALC4080 firmware being used by different motherboard manufacturers.

I have also noticed that this problem is also present on Windows without the motherboard drivers installed. Later I will install the driver on Windows and try to see if the problem is solved, and if so, try to see what method is being used by the driver to boost the volume. If need be I'll capture the USB packets on Windows.

Thank you again for your help, and I think I will try to get in contact with the Linux driver developers.

**Comment by ryannathans** [comment]
Same issue on the x870 Tomahawk. Is this an issue on all ALC4080 motherboards or just the Tomahawk?

**Comment by perexg** [comment]
> Is there any reason in particular why the mic gain cannot be adjusted on Linux?

Unless there's a mixer control, then this functionality is not exposed using standard USB audio interface. Information from the hardware vendor (or using reverse-engineering) should be collected before any other action.

> Where should this issue be reported?

Unless there's information what to do in the USB audio driver, there's no place to report.

**Comment by nfp0** [comment]
For anyone searching for this, see further discussion on https://github.com/alsa-project/alsa-ucm-conf/issues/541

**Comment by vmpartner** [comment]
Fix it and wrote instruction https://gist.github.com/vmpartner/d7846bd8d1f10248d52075178b1f2539

**Comment by bilgehanG** [comment]
> Fixed it and wrote instruction https://gist.github.com/vmpartner/d7846bd8d1f10248d52075178b1f2539

Thanks, this fixed my issue on MSI MPG B850 EDGE TI WIFI as well, it had the same USB ID:  `0db0:cd0e`

```
flooder@flooder:~$ lsusb | grep Audio
Bus 001 Device 003: ID 0db0:cd0e Micro Star International USB Audio
```

**Comment by mr5z** [comment]
Codec for `MSI MAG x870e Tomahawk Wifi` is still missing. Tried several workarounds but this seems requires a kernel update as well.
