### ISSUE TITLE
BridgeCast v2 not working properly despite V2 configuration files

### ISSUE THREAD

**Issue by acerammos** [alsa-project/alsa-ucm-conf#458]
Hi everybody,

I (sadly) made the firmware update for the Roland BridgeCast and it came out broken.
It was working flawlessly before the update, thanks to you i had all the Output/Input channels available and i was able to assign sound sources on them individually through the system settings gui (Kmix - Plasma).

Today, as a now "V2", it is over. The BridgeCast seems to be assigned to the new conf files with its new usb tag, to `BridgeCastV2-Hifi.conf` and not former the `BridgeCast-Hifi.conf`. It seems to be a good start, thanks to Fulmer for the merge and first testing Roland's update.

But now, i have a weird mix of "auxiliary channels" instead of proper audio outputs like before : 

![Copie d'écran_20241106_154428](https://github.com/user-attachments/assets/4240924b-9650-41f4-a167-aaa05f6daac9)
> _(Tell me if you need Fr>En translation on that screenshot)_

Note that "chromium" (wich is in fact a client like spotify, playing music) cannot be assigned to a specific output, because BridgeCast is now detected to be "only one channel" so the option is missing. An exemple after also enabling my speakers :

![Copie d'écran_20241106_155745](https://github.com/user-attachments/assets/d01d1a67-f040-4672-a1cc-f67a14c79d95)
> _Old behaviour allowed me to choose between all the output channels of the BridgeCast, like "Games", "Aux", "Music", Chat" or "System"_

Something else i've (maybe) noticed is the differences for the channel maps, between the `cat /proc/asound/cardX/stream0` channels output and what is written in the `Roland/BridgeCastV2-Hifi.conf`.

`cat /proc/asound/cardX/stream0 :`

```
Roland BRIDGE CAST V2 at usb-0000:00:14.0-1, high speed : USB Audio

Playback:
  Status: Running
    Interface = 1
    Altset = 1
    Packet Size = 392
    Momentary freq = 48000 Hz (0x6.0000)
  Interface 1
    Altset 1
    Format: S32_LE
    Channels: 14
    Endpoint: 0x0d (13 OUT) (ASYNC)
    Rates: 48000
    Data packet interval: 125 us
    Bits: 24
    Channel map: FL FR FC LFE RL RR FLC FRC RC SL SR TC -- --
    Sync Endpoint: 0x8e (14 IN)
    Sync EP Interface: 2
    Sync EP Altset: 1
    Implicit Feedback Mode: Yes

Capture:
  Status: Stop
  Interface 2
    Altset 1
    Format: S32_LE
    Channels: 6
    Endpoint: 0x8e (14 IN) (ASYNC)
    Rates: 48000
    Data packet interval: 125 us
    Bits: 24
    Channel map: FL FR FC LFE RL RR
    Sync Endpoint: 0x0d (13 OUT)
    Sync EP Interface: 1
    Sync EP Altset: 1
    Implicit Feedback Mode: Yes
```

`BridgeCastV2-Hifi.conf :`

```
Macro [
	{
		SplitPCM {
			Name "bc_stereo_out"
			Direction Playback
			Channels 2
			HWChannels 14
			HWChannelPos0 FL
			HWChannelPos1 FR
			HWChannelPos2 FL
			HWChannelPos3 FR
			HWChannelPos4 FL
			HWChannelPos5 FR
			HWChannelPos6 FL
			HWChannelPos7 FR
			HWChannelPos8 FL
			HWChannelPos9 FR
			HWChannelPos10 FL
			HWChannelPos11 FR
			HWChannelPos12 FL
			HWChannelPos13 FR
		}
	}
	{
		SplitPCM {
			Name "bc_stereo_in"
			Direction Capture
			Channels 2
			HWChannels 6
			HWChannelPos0 FL
			HWChannelPos1 FR
			HWChannelPos2 FL
			HWChannelPos3 FR
			HWChannelPos4 FL
			HWChannelPos5 FR
		}
	}
]
```

I'm completely new to this kind of code/linux driver wizardry so i haven't been able to gather more data, but i'm not afraid to be messing around, so if i can be of any help, screenshot, command outputs, random file testing, i'll gladly help.

Regards, and thank you all !

> _Edits : Spelling/Grammar mistakes_

**Comment by perexg** [comment]
Could you show `alsaucm -c hw:0 dump text` output for this card (replace zero with the proper card number). It looks like the UCM configuration is not detected for your device.

**Comment by acerammos** [comment]
Looks like you were right

`alsaucm -c hw:2 dump text` :
```
ALSA lib conf.c:2012:(_snd_config_load_with_include) _toplevel_:484:0:Unexpected char
ALSA lib utils.c:375:(uc_mgr_config_load_into) could not load configuration file /usr/share/alsa/ucm2/conf.d/USB-Audio/USB-Audio.conf
ALSA lib parser.c:2812:(load_toplevel_config) error: could not parse configuration for card hw:2
ALSA lib main.c:1554:(snd_use_case_mgr_open) error: failed to import hw:2 use case configuration -22
alsaucm: error failed to open sound card hw:2: Invalid argument

```

**Comment by acerammos** [comment]
Here's some data :

- `lsusb` :
`Bus 001 Device 002: ID 0582:031e Roland Corp. BRIDGE CAST V2`  

- `aplay -l` :
```
carte 2 : V2 [BRIDGE CAST V2], périphérique 0 : USB Audio [USB Audio]
  Sous-périphériques : 0/1
  Sous-périphérique #0 : subdevice #0
```

**Comment by perexg** [comment]
Oops. It seems that there was something missing in one commit. Please, retry with latest UCM2 configuration tree or apply the above fix manually. Thank you for your report.

**Comment by acerammos** [comment]
It works now, thanks to your update !

**Comment by Simon99de** [comment]
hello, unfortunately it does not work for me. (the same error picture).
i guess it's because of the file:
/ucm2/USB-Audio/USB-Audio.conf
