### ISSUE TITLE
Device selection regression in 1.2.13 for LNL

### ISSUE THREAD

**Issue by CarelessCaution** [alsa-project/alsa-ucm-conf#474]
On Intel Lunar Lake, there seems to be a regression in alsa-ucm-conf that affects device selection in KDE Plasma and probably in other software. In 1.2.12, there are the options Play HiFi Quality Music and Pro Audio for both input and output. However, when upgrading to 1.2.13, there is only the option for Pro Audio.

This problem is immediately remedied by downgrading just the alsa-ucm-conf package on Arch Linux.

According to `aplay -l`, the audio card is sofhdadsp.

Before (1.2.12):

![before](https://github.com/user-attachments/assets/c7fa81e0-97f1-45ae-a14e-8549f85cdd27)

After (1.2.13):

![after](https://github.com/user-attachments/assets/5867886b-6686-4265-ad68-50c7f53e1a47)

**Comment by perexg** [comment]
Dup of #472 .
