### ISSUE TITLE
No built-in microphone in Thinkpad X1 Carbon (Gen 12) after update to v1.2.13

### ISSUE THREAD

**Issue by iyanmv** [alsa-project/alsa-ucm-conf#476]
I think the title is self-explanatory. After updating from v1.2.12 to v1.2.13 in Arch Linux, the built-in microphone on my laptop is not working. Downgrading to previous versions fixes the issue.

In addition, I also noticed that when attached to an external monitor using a docking station, the speakers of the monitor are not listed as before, and only the laptop's built-in speaker appears.

I'm running linux 6.12.1 and KDE Plasma 6.2.3.

**Comment by aronerben** [comment]
Same issue here on a HP ProBook 450 G9, also Arch Linux, Kernel 6.12.1, no desktop manager. 
Downgrading to 1.2.12 fixed the issue for me, too.

**Comment by perexg** [comment]
Dup of #472. Fix is available.
