### ISSUE TITLE
No microphone USB audio Behringer UMC204HD ALSA update

### ISSUE THREAD

**Issue by emiltoacs** [alsa-project/alsa-ucm-conf#479]
No input on my Behringer UMC204HD because of an update in the following packages on Arch Linux alsa-card-profiles,alsa-lib,alsa-ucm-conf,alsa-utils,lib32-alsa-lib

alsa-card-profiles 1:1.2.6-1 -> 1:1.2.7-1
alsa-lib 1.2.12-1 -> 1.2.13-1
alsa-ucm-conf 1.2.12-1 -> 1.2.13-2
alsa-utils 1.2.12-1 -> 1.2.13-2
lib32-alsa-lib 1.2.12-1 -> 1.2.13-1

The error messages related by pipewire :

```
pw.node: (alsa_output.pci-0000_00_1f.3.stereo-fallback-57) graph xrun not-triggered (0 suppressed)
pw.node: (alsa_output.pci-0000_00_1f.3.stereo-fallback-57) xrun state:0x7ba2cfaed008 pending:6/6 s:0 a:0 f:0 waiting:0 process:0 status:triggered
pw.node: (alsa_output.pci-0000_00_1f.3.stereo-fallback-57) graph xrun not-triggered (4 suppressed)
pw.node: (alsa_output.pci-0000_00_1f.3.stereo-fallback-57) xrun state:0x7ba2cfaed008 pending:1/1 s:2663559587040 a:2663559606728 f:2663559630434 waiting:19688 process:23706 status:triggered
pw.node: (alsa_output.pci-0000_00_1f.3.stereo-fallback-57) graph xrun not-triggered (0 suppressed)
pw.node: (alsa_output.pci-0000_00_1f.3.stereo-fallback-57) xrun state:0x7ba2cfaed008 pending:1/1 s:5553029600968 a:5553029610813 f:5553029623757 waiting:9845 process:12944 status:triggered
```

If I revert package the package to these version it works again :

alsa-card-profiles-1:1.2.6-1-x86_64.pkg.tar.zst alsa-lib-1.2.12-1-x86_64.pkg.tar.zst lib32-alsa-lib-1.2.12-1-x86_64.pkg.tar.zst alsa-utils-1.2.12-1-x86_64.pkg.tar.zst alsa-ucm-conf-1.2.12-1-any.pkg.tar.zst 

In the meantime I add
: --ignore alsa-card-profiles,alsa-lib,alsa-ucm-conf,alsa-utils,lib32-alsa-lib
to my pacman update.

**EDIT**
only the alsa-ucm-conf package is faulty somewhere between these two version 
alsa-ucm-conf 1.2.12-1 -> 1.2.13-2

Workaround:
Downgrade to alsa-ucm-conf-1.2.12-1

With this package built by the maintainer @christian-heusel  for testing https://pkgbuild.com/\~gromit/alsa-ucm-conf-v1.2.13.r6.g62acef2-1-any.pkg.tar.zst  
the microphone seens to work but in the logs I have the same error message as above :

```
pipewire[2522]: pw.node: (alsa_output.pci-0000_00_1f.3.stereo-fallback-56) graph xrun not-triggered (0 suppressed)
pipewire[2522]: pw.node: (alsa_output.pci-0000_00_1f.3.stereo-fallback-56) xrun state:0x7e7d78f97008 pending:6/6 s:69949980861 a:69950023367 f:69950232612 waiting:42506 process:209245 status:triggered
```

although I manage to receive the signal of my microphone.

See https://bbs.archlinux.org/viewtopic.php?pid=2211786 for the details of our discussion with @christian-heusel

**Comment by christian-heusel** [comment]
> EDIT
> only the alsa-ucm-conf package is faulty somewhere between these two version
> alsa-ucm-conf 1.2.12-1 -> 1.2.13-2

Just to highlight the difference between these versions, we have backported 11b028a9a01e47fc9b48e4a566803752011902e2 (see [archlinux/packaging/packages/alsa-ucm-conf!1](https://gitlab.archlinux.org/archlinux/packaging/packages/alsa-ucm-conf/-/merge_requests/1)) and apparently this seems to cause the issue reported above.

**Comment by christian-heusel** [comment]
So expanding on OP's edit: The error is _not_ present with the latest `master` branch, but instead a different error is shown (although sound still seems to work)

**Comment by emiltoacs** [comment]
Hey sorry for the reports but it ends up that after a full purge and reinstall of all my package related to the sound :

    alsa pipewire wireplumber easyeffects qpwgraph

with the alsa-ucm-conf in its latest version 1.2.13-2 the inputs of the Behringer UMC204HD are working correctly.

The errors I can still see in the logs seems related to wireplumber 

    systemd[1]: Manage Sound Card State (restore and store) was skipped because of an unmet condition check (ConditionPathExists=/etc/alsa/state-daemon.conf).
    ...
    wireplumber[1686]: spa.alsa: Unable to load mixer: No such file or directory
    wireplumber[1686]: spa.alsa: Failed to find a working mixer device (_ucm0003.default:U192k).
    ...

and some other error seems to be related to easy effects

    pipewire[2590]: pw.node: (alsa_input.usb-BEHRINGER_UMC204HD_192k-00.HiFi__Mic1__source-43) graph xrun not-triggered (0 suppressed)
    pipewire[2590]: pw.node: (alsa_input.usb-BEHRINGER_UMC204HD_192k-00.HiFi__Mic1__source-43) xrun state:0x7ac9670ec008 pending:15/19 s:0 a:0 f:0 waiting:0 process:0 status:triggered
    pipewire[2590]: pw.node: (ee_sie_stereo_tools-168) xrun state:0x7ac965f87008 pending:0/2 s:56446132704 a:0 f:0 waiting:18446744017263418912 process:0 status:triggered
    pipewire[2590]: pw.node: (ee_soe_equalizer-111) xrun state:0x7ac965f79008 pending:0/2 s:56444688635 a:56446141200 f:0 waiting:1452565 process:18446744017263410416 status:awake

but I can use my microphone correctly through the sound card.

Sorry for mistakenly though that alsa UCM was faulty.

**Comment by tuffnerdstuff** [comment]
I just wanted to add my two cents here regarding issues with my Behringer UMC202HD so that the solution can be googled by fellow users. After a recent update to Endeavor OS (Arch based) I was only getting sound from Line B via headphones on profile "default". For all other profiles there was no sound. I fixed such issues in the past by unmuting the stubborn channels using `alsamixer` and raising the volume. I tried `alsactl init` and also deleting `asound.state` but to no avail. However, when selecting my card in `alsamixer` I got this error: `cannot open mixer: No such file or directory`. After some hours of comparing between Endeavor OS and my NixOS machine (where it still worked), I rolled back to the same `alsa-ucm-conf` version `1.2.12-1` and it worked again (including `alsamixer`). Then I upgraded back to `1.2.13-2` and sound still worked, but `alsamixer` gave me the same error as before. I will try the suggested fix by @emiltoacs and report back.

**Comment by emiltoacs** [comment]
> when selecting my card in alsamixer I got this error: cannot open mixer: No such file or directory

I have the same error, although I haven't noticed earlier. `alsamixer` works until I try to select the embed sound card on my laptop `HDA Intel PCK` or my UMC204HD
