### ISSUE TITLE
Unable to request ucm2 to load BootSequence controls defaults

### ISSUE THREAD

**Issue by singalsu** [alsa-project/alsa-ucm-conf#480]
I'm stuck with my ucm2 patch to set by default control switches for SOF DRC and beamformer "on" when the controls appear for first time. I don't seem to be able to reset the controls for the SOF sound card to defaults.

There's a similar feature in https://github.com/alsa-project/alsa-ucm-conf/blob/62acef2efffdcb75a35f90d266bcad145b4eab35/ucm2/Intel/sof-hda-dsp/sof-hda-dsp.conf#L112 for "Dmic0 Capture Volume". But I haven't been able to see the volume to go to 70% in my tries to reset the configuration.

In Fedora 41 I've tried to remove /var/lib/alsa/asound.state and rename /usr/sbin/alsactl, reboot, and rename it back. But no success. The volume control remains in 100%. Similarly my tries to get DRC and TDFB enabled fail.

What is the right trick needed to trigger the BootSequence?

**Comment by perexg** [comment]
Have you tried sequence from https://github.com/alsa-project/alsa-ucm-conf/blob/master/README.md ?

**Comment by singalsu** [comment]
Thanks, yes that works!
