### ISSUE TITLE
CS42L43 headset mic enable/disable not applied when jack insert state changes

### ISSUE THREAD

**Issue by rfvirgil** [alsa-project/alsa-ucm-conf#489]
Originally the configuration for sof-soundwire/cs42l43*.conf had the headset mic and internal mics on the same ALSA capture device 4. The Headset Mic enable and disable sequences ran as expected when the headset jack was inserted  and removed.

But SOF expects that device 4 is the internal mics, and headset mic should be on device 1. So we made this change to move the headset mic to capture device 1:
https://github.com/alsa-project/alsa-ucm-conf/commit/30989bd0c2aa3f9f4b6f5e393397b39678717f45

But now the Headset Mic enable and disable sequences do not run when the headset jack state changes.
Seen on multiple systems with Pipewire + alsa-ucm + CS42L43 on sof-soundwire.

Example from a system that booted with jack unplugged. The jack was then plugged in. The CS42L43 has reported that the headset mic is present:

```
Simple mixer control 'Headset Mic',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [on]
```

But the enable sequence has not been applied (DP2TX1 and DP2TX2 should have been set to Decimator 1):

```
Simple mixer control 'cs42l43 DP2TX1 Input',0
  Capabilities: enum
  Items: 'None' 'Tone Generator 1' 'Tone Generator 2' 'Decimator 1' 'Decimator 2' 'Decimator 3' 'Decimator 4' 'ASPRX1' 'ASPRX2' 'ASPRX3' 'ASPRX4' 'ASPRX5' 'ASPRX6' 'DP5RX1' 'DP5RX2' 'DP6RX1' 'DP6RX2' 'DP7RX1' 'DP7RX2' 'ASRC INT1' 'ASRC INT2' 'ASRC INT3' 'ASRC INT4' 'ASRC DEC1' 'ASRC DEC2' 'ASRC DEC3' 'ASRC DEC4' 'ISRC1 INT1' 'ISRC1 INT2' 'ISRC1 DEC1' 'ISRC1 DEC2' 'ISRC2 INT1' 'ISRC2 INT2' 'ISRC2 DEC1' 'ISRC2 DEC2' 'EQ1' 'EQ2'
  Item0: 'None'
Simple mixer control 'cs42l43 DP2TX2 Input',0
  Capabilities: enum
  Items: 'None' 'Tone Generator 1' 'Tone Generator 2' 'Decimator 1' 'Decimator 2' 'Decimator 3' 'Decimator 4' 'ASPRX1' 'ASPRX2' 'ASPRX3' 'ASPRX4' 'ASPRX5' 'ASPRX6' 'DP5RX1' 'DP5RX2' 'DP6RX1' 'DP6RX2' 'DP7RX1' 'DP7RX2' 'ASRC INT1' 'ASRC INT2' 'ASRC INT3' 'ASRC INT4' 'ASRC DEC1' 'ASRC DEC2' 'ASRC DEC3' 'ASRC DEC4' 'ISRC1 INT1' 'ISRC1 INT2' 'ISRC1 DEC1' 'ISRC1 DEC2' 'ISRC2 INT1' 'ISRC2 INT2' 'ISRC2 DEC1' 'ISRC2 DEC2' 'EQ1' 'EQ2'
  Item0: 'None'
```

**Comment by perexg** [comment]
The jack state should be reported using 'Jack' controls and you have 'JackControl "Headset Mic Jack"' in config.

Example (for HDA driver):

```
$ amixer -c 0 controls
...
numid=12,iface=CARD,name='Headphone Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=off
...
```

**Comment by perexg** [comment]
To be more precise: It seems that pipewire has not found the right jack control. It's not a mixer control.

**Comment by perexg** [comment]
You have also probably some mixer `Headset Mic Switch` or volume controls which were referred incorrectly - see `amixer -c 0 controls | grep "Headset Mic"`.

Anway, the wireplumber debug log is required to check the issue like:

```
systemctl --user stop wireplumber
WIREPLUMBER_DEBUG="spa.*:5" wireplumber
```

Look for Jack and ucm lines.

**Comment by perexg** [comment]
> Hmm... we do have "Headphone Switch"/"Headset Mic Switch" controls, but getting rid of them doesn't seem to fix anything.

I'm just saying that you have two controls with almost similar name, but only 'Jack' one with iface=CARD type is handled as source for the jack detection.
 
> Running wireplumber as you suggest I get no output, if I drop the ":5" (_WIREPLUMBER_DEBUG="spa.*" wireplumber_) and boot with the Jack inserted I get this:

No idea. I followed https://julian.pages.freedesktop.org/wireplumber/daemon/logging.html and the `"spa.*:5"` works for me (pipewire 1.0.9).

> ```
> C 14:27:37.785131           spa.alsa ../spa/plugins/alsa/acp/alsa-ucm.c:1433:pa_alsa_ucm_set_port: Failed to enable ucm device Mic
> C 14:27:38.186705           spa.alsa ../spa/plugins/alsa/acp/alsa-ucm.c:1433:pa_alsa_ucm_set_port: Failed to enable ucm device Speaker
> ```
> 
> If I boot with the jack removed I get the reciprocal fail for the headset, when I plug it in:
> 
> ```
> C 14:31:10.995911           spa.alsa ../spa/plugins/alsa/acp/alsa-ucm.c:1433:pa_alsa_ucm_set_port: Failed to enable ucm device Headset
> C 14:31:11.038700           spa.alsa ../spa/plugins/alsa/acp/alsa-ucm.c:1433:pa_alsa_ucm_set_port: Failed to enable ucm device Headphones
> ```
> 
> Perhaps it fails because of the ConflictingDevice? I am unsure if it should be pipewire or alsaucm that will disable the other device when it does the switch, but certainly looking through the pipewire code, the only place it disables a device (_disdev) is when it switches profiles. So it will certainly try to enable the new device without disabling the conflicting one, although why this doesn't also cause a problem when they are on the same subdevice I have no idea.

Could you provide UCM dump? `alsaucm -c hw:0 dump text`

**Comment by charleskeepax** [comment]
Yeah I will keep the Switch controls removed whilst we finish testing, then when its all working we can see if adding them back is ok. I think perhaps my version of pipewire is a bit out of date I will update and retest things, although we have reports from others of this issue too, so probably not just my version being a bit old.

UCM Dump:
[ucm.txt](https://github.com/user-attachments/files/18213199/ucm.txt)

**Comment by perexg** [comment]
The dump looks fine. What's your pipewire version?

**Comment by stuhenderson** [comment]
Hi,
I've reproduced this on another system running Ubuntu 24.04, which appears to use:
pipewire
Compiled with libpipewire 1.0.5
wireplumber
Compiled with libwireplumber 0.4.17
alsa-utils  1.2.9-1ubuntu5

I've attached the alsaucm dump and wireplumber logs for working vs non-working here:
[ucm-notworking.txt](https://github.com/user-attachments/files/18239639/ucm-notworking.txt)
[ucm-working.txt](https://github.com/user-attachments/files/18239640/ucm-working.txt)
[wp-notworking.txt](https://github.com/user-attachments/files/18239641/wp-notworking.txt)
[wp-working.txt](https://github.com/user-attachments/files/18239642/wp-working.txt)

Note the only difference in the alsaucm dump between working and non-working is the sub device.

For working (Mic is disabled before enabling Headset when the jack is inserted):
D 12:30:46.527483           spa.alsa ../spa/plugins/alsa/acp/alsa-ucm.c:1466:pa_alsa_ucm_set_port: Enable ucm device Mic
D 12:30:46.560966           spa.alsa ../spa/plugins/alsa/acp/alsa-ucm.c:1466:pa_alsa_ucm_set_port: Enable ucm device Speaker
D 12:31:13.559712           spa.alsa ../spa/plugins/alsa/acp/alsa-ucm.c:1456:pa_alsa_ucm_set_port: Disable ucm device Mic
D 12:31:13.568912           spa.alsa ../spa/plugins/alsa/acp/alsa-ucm.c:1466:pa_alsa_ucm_set_port: Enable ucm device Headset

For non-working (we don't appear to disable Mic prior to enabling Headset when jack is inserted, and then we blow up):
D 12:31:53.165741           spa.alsa ../spa/plugins/alsa/acp/alsa-ucm.c:1466:pa_alsa_ucm_set_port: Enable ucm device Mic
D 12:31:53.211670           spa.alsa ../spa/plugins/alsa/acp/alsa-ucm.c:1466:pa_alsa_ucm_set_port: Enable ucm device Speaker
D 12:32:00.742967           spa.alsa ../spa/plugins/alsa/acp/alsa-ucm.c:1466:pa_alsa_ucm_set_port: Enable ucm device Headset
C 12:32:00.742970           spa.alsa ../spa/plugins/alsa/acp/alsa-ucm.c:1468:pa_alsa_ucm_set_port: Failed to enable ucm device Headset

It looks like this was fixed somewhere along the way, as I can't reproduce on 24.10 (pipewire 1.2.4 and wireplumber 0.5.6) but difficult to see what component fixed it.
Thanks,
Stu

**Comment by perexg** [comment]
Source code for pipewire UCM implementation: https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/master/spa/plugins/alsa/acp/alsa-ucm.c

Issue tracker: https://gitlab.freedesktop.org/pipewire/pipewire/-/issues

The problem is (was) probably in the pipewire UCM implementation. Please, follow their directions to resolve it.

**Comment by KaiChuan-Hsieh** [comment]
@stuhenderson hello,

Could you check if the package fix your problem? https://bugs.launchpad.net/ubuntu/+source/pipewire/+bug/2122556/comments/4

Thanks,
