### ISSUE TITLE
dcef48f "add support for AMD acp microphone devices" can break pulseaudio

### ISSUE THREAD

**Issue by danielrparks** [alsa-project/alsa-ucm-conf#54]
I recently upgraded alsa-ucm-conf from 1.2.3 to 1.2.4 on Arch Linux, and now pulseaudio fails to initialize my sound card.
This system is a Dell Inspiron 7405 with a Ryzen 7 4700U and a Realtek ALC3204 sound card. The microphone is handled by the audio co-processor.
Pulseaudio generates the following error:
```
Failed to find a working profile.
Failed to load module "module-alsa-card" (argument: "device_id="1" name="pci-0000_03_00.6" card_name="alsa_card.pci-0000_03_00.6" namereg_fail=false tsched=yes fixed_latency_range=no ignore_dB=no deferred_volume=yes use_ucm=yes avoid_resampling=no card_properties="module-udev-detect.discovered=1""): initialization failed.
```
[notworking-journal.txt](https://github.com/alsa-project/alsa-ucm-conf/files/5397852/notworking-journal.txt)
[working-pacmd-list-sinks.txt](https://github.com/alsa-project/alsa-ucm-conf/files/5397853/working-pacmd-list-sinks.txt)

I did a git bisect and got this:
```
dcef48f13d4f5db79b006755074940b94730a883 is the first bad commit
commit dcef48f13d4f5db79b006755074940b94730a883
Author: Jaroslav Kysela <perex@perex.cz>
Date:   Wed Jun 24 13:39:07 2020 +0200

    HDA-Intel: add support for AMD acp microphone devices
    
    - move the generic HDA code from sof-hda-dsp to HDA-Intel
    - add generic codecs/hda/hdmi.conf
    
    Signed-off-by: Jaroslav Kysela <perex@perex.cz>

 ucm2/HDA-Intel/HDA-Capture-value.conf   |   4 +
 ucm2/HDA-Intel/HDA-Intel.conf           |  28 +++++++
 ucm2/HDA-Intel/Hdmi.conf                |  37 +++++++++
 ucm2/HDA-Intel/HiFi-acp.conf            |   8 ++
 ucm2/HDA-Intel/HiFi-analog.conf         | 133 +++++++++++++++++++++++++++++++
 ucm2/HDA-Intel/HiFi.conf                |  32 ++++++++
 ucm2/HDA-Intel/init.conf                |  39 +++++++++
 ucm2/codecs/hda/hdmi.conf               |  25 ++++++
 ucm2/module/lib/linked.conf             |   3 +
 ucm2/module/snd_acp3x_rn.conf           |   1 +
 ucm2/sof-hda-dsp/HDA-Capture-value.conf |   4 -
 ucm2/sof-hda-dsp/Hdmi.conf              |  78 +++++-------------
 ucm2/sof-hda-dsp/HiFi.conf              | 135 +-------------------------------
 13 files changed, 331 insertions(+), 196 deletions(-)
 create mode 100644 ucm2/HDA-Intel/HDA-Capture-value.conf
 create mode 100644 ucm2/HDA-Intel/HDA-Intel.conf
 create mode 100644 ucm2/HDA-Intel/Hdmi.conf
 create mode 100644 ucm2/HDA-Intel/HiFi-acp.conf
 create mode 100644 ucm2/HDA-Intel/HiFi-analog.conf
 create mode 100644 ucm2/HDA-Intel/HiFi.conf
 create mode 100644 ucm2/HDA-Intel/init.conf
 create mode 100644 ucm2/codecs/hda/hdmi.conf
 create mode 100644 ucm2/module/lib/linked.conf
 create mode 120000 ucm2/module/snd_acp3x_rn.conf
 delete mode 100644 ucm2/sof-hda-dsp/HDA-Capture-value.conf
```

**Comment by perexg** [comment]
Provide debug log for pulseaudio, please. '-vvvvvv' argument. https://fedoraproject.org/wiki/How_to_debug_PulseAudio_problems#General_advice

**Comment by danielrparks** [comment]
I didn't know you could have that many v's! :smiley: 
[vvvvvv.txt](https://github.com/alsa-project/alsa-ucm-conf/files/5398453/vvvvvv.txt)

Here's a problem that didn't show up when I tried it before (I think with 4 v's):
```
D: [pulseaudio] alsa-util.c: Trying hw:acp with SND_PCM_NO_AUTO_FORMAT ...
I: [pulseaudio] alsa-util.c: Error opening PCM device hw:acp: Device or resource busy
```

**Comment by perexg** [comment]
I see the issue:

<pre>
I: [pulseaudio] (alsa-lib)main.c: error: failed to import hw:2 (empty configuration)
I: [pulseaudio] (alsa-lib)main.c: error: failed to import acp (empty configuration)
I: [pulseaudio] alsa-ucm.c: UCM not available for card acp
</pre>

The sound card should be skipped in this case. It's alsa-lib's issue. It should be fixed in https://github.com/alsa-project/alsa-lib/commit/d77fb4731886ff1244e815a05b2be6d261382cbe . Thank you for your report.
