### ISSUE TITLE
No sound after upgrade from 1.2.3 to 1.2.4 (Xiaomi Redmibook 16 II Ryzen Edition)

### ISSUE THREAD

**Issue by deponian** [alsa-project/alsa-ucm-conf#55]
Hello.
Yesterday I have upgraded Arch Linux on my laptop with `pacman -Syu` and after reboot I've had no sound from built-in speakers. I had downgraded all upgraded packages and started upgrading one-by-one with reboot after every step. I have found out that upgrading `alsa-ucm-conf` package from `1.2.3-2` to `1.2.4-1` is causing the issue. If I understand correctly my laptop has something called `Family 17h (Models 10h-1fh) HD Audio Controller` which is using for output and `Raven/Raven2/FireFlight/Renoir Audio Processor Stereo` which is using for input. After upgrading to `1.2.4` I had had only broken output, the input (microphone) was working correctly.
I have attached two outputs of `alsa-info.sh` to this message: one before and other one after upgrade.
[alsa-info-1.2.3.txt](https://github.com/alsa-project/alsa-ucm-conf/files/5403794/alsa-info-1.2.3.txt)
[alsa-info-1.2.4.txt](https://github.com/alsa-project/alsa-ucm-conf/files/5403796/alsa-info-1.2.4.txt)
I hope it will help.

**Comment by perexg** [comment]
https://github.com/alsa-project/alsa-ucm-conf/issues/54

**Comment by dvzrv** [comment]
For reference: https://github.com/alsa-project/alsa-lib/issues/87

Seems I need to downgrade all of the packages now.

@perexg do you have a rough estimate for a release of 1.2.4?

**Comment by perexg** [comment]
Today. In few hours.

**Comment by tbbrave** [comment]
+1，with kernel 5.8.15-301.fc33.x86_64.
