### ISSUE TITLE
ucm2:sof-soundwire: Add Support For Dell Privacy Mic Mute LED Control

### ISSUE THREAD

**Issue by GoPerry** [alsa-project/alsa-ucm-conf#59]
Dell is going to add internal microphone mute led control for Dell privacy system,
which has hardware level protection for audio privacy, when mic mute
state is changed, the ucm2 will help to switch the Mic Mute LED state.

This solution has been discussed by this FR.
https://github.com/thesofproject/linux/issues/2496

This system EC which support audio privacy needs get ACK event when the LED state need to change.
I add one new mixer for RT715 (local mics) to switch the mic mute led state
So the UCM2 will help to call the mixer to notify the LED state is changed.
The led trigger driver will emit the notification to EC through the  LED driver.
Then LED state controlled by the EC will be changed accordingly.

**Comment by plbossart** [comment]
@GoPerry what 'new mixer for RT715 (local mics) to switch the mic mute led state' are you referring to? and are you referring to RT715 or the RT715-sdca version?

**Comment by GoPerry** [comment]
@plbossart 
I add one new control in the codec driver rt715.c
https://lkml.org/lkml/2020/11/3/538

I did some testing with this mixer, it can work.
This system use the rt715 as the local mic , dose it need to add same code to rt715-sdca ?
It will be great if you could help check if is the right place or mixer name added to support privacy mic mute feature.

**Comment by GoPerry** [comment]
https://patchwork.kernel.org/project/platform-driver-x86/patch/20201103125542.8572-1-Perry_Yuan@Dell.com/
this the privacy driver we are going to use for privacy mic mute feature.

**Comment by perexg** [comment]
This should be resolved in https://github.com/alsa-project/alsa-ucm-conf/pull/67 .
