### ISSUE TITLE
Lose HDMI audio and internal DMIC after upgrade from 1.2.3 to 1.2.4 on Intel TigerLake machines

### ISSUE THREAD

**Issue by starnight** [alsa-project/alsa-ucm-conf#66]
We have some laptops equipped with Intel i7-1165G7 and i5-1135G7.  The HDMI audio and internal Intel SST DMIC can be detected by PulseAudio with alsa-ucm-conf at **v1.2.3**.  But, they are lost when upgrade alsa-ucm-conf to **v1.2.4** (including latest).

I did bisect and found it starts to be failed at commit dcef48f ("HDA-Intel: add support for AMD acp microphone devices").

[alsa-info.txt](https://github.com/alsa-project/alsa-ucm-conf/files/5677934/alsa-info.txt)

**Comment by perexg** [comment]
Could you try https://github.com/alsa-project/alsa-ucm-conf/commit/33be660e4b1e75c19d5332556c3d2636dd3344bf ?

**Comment by perexg** [comment]
Please, show debug output from pulseaudio (-vvv): https://fedoraproject.org/wiki/How_to_debug_PulseAudio_problems

**Comment by starnight** [comment]
Sure!  Here it is 
[pulseaudio.log](https://github.com/alsa-project/alsa-ucm-conf/files/5678147/pulseaudio.log)
[pacmd-ls.txt](https://github.com/alsa-project/alsa-ucm-conf/files/5678146/pacmd-ls.txt)

**Comment by perexg** [comment]
Something is wrong:

`(alsa-lib)main.c: error: failed to import sof-hda-dsp use case configuration -17`

Please, attach also output from 'alsa-info.sh --no-upload' . Thank you.

**Comment by starnight** [comment]
> Something is wrong:
> 
> `(alsa-lib)main.c: error: failed to import sof-hda-dsp use case configuration -17`

Thanks for pointing!!! I guess we need newer alsa-lib to parse the new configuration files.

I upgrade alsa-lib and alsa-utils from **1.2.3** to **1.2.4**, then the HDMI audio and internal DMIC show up and work with alsa-ucm-conf **v1.2.4** (including latest)!

So, I close this issue.
