### ISSUE TITLE
How to install on debian buster?

### ISSUE THREAD

**Issue by kopax** [alsa-project/alsa-ucm-conf#8]
I use kernel 5.3 on debian buster and I am following thos offical Lenovo tutorial to install the microphone on my x1c7:

https://forums.lenovo.com/lnv/attachments/lnv/lx02_en/3199/1/Enabling%20audio%20on%20the%20X1C7.pdf

It says:

![image](https://user-images.githubusercontent.com/1866564/71328607-1a5e8180-251a-11ea-8621-1655d7746c60.png)

Now the [link](https://github.com/alsa-project/alsa-ucm-conf/tree/master/ucm/sof-skl_hda_card) is 404, what do I need to get now ?

Thanks in advance and merry xmas!

**Comment by lgirdwood** [comment]
@kopax did you manage to fix this ? Is there a new link ?

**Comment by kopax** [comment]
yes, I downloaded the most recent one, ignore that it is not `signed-intel`, it will work.
