### ISSUE TITLE
ucm2: sof-hda-dsp: DMICS may not be present

### ISSUE THREAD

**Issue by plbossart** [alsa-project/alsa-ucm-conf#80]
UCM files assume that when SOF is used, the number of DMICs is between 1 and 4.

That's an invalid assumption in the following two cases:
a) the user plays with kernel parameters to select SOF on a platform without DMIC
options snd_intel_dspcfg dsp_driver=3
b) the user plays with kernel parameters to work-around invalid dmic information, e.g. for UpExtreme the NHLT information reports 4 microphones but none are attached to the connector by default
options snd_sof_intel_hda_common dmic_num=0

In those two cases, the only solution is to comment out the entire 'Mic1' section in ucm2/sof-hda-dsp/HiFi.conf. It'd be nicer to detect this case with the component information

The machine driver currently only provides the cfg-dmics component string when the real or overridden number of dmics is > 0.
The component string is as follows

````
amixer -Dhw:0 info
Card hw:0 'sofhdadsp'/'AAEON-UP_WHL01-V1.0'
  Mixer name	: 'Realtek ALC892'
  Components	: 'HDA:8086280b,80860101,00100000 HDA:10ec0892,160d0892,00100302'
  Controls      : 40
  Simple ctrls  : 15
````
Reported by @worldgeek and confirmed on my platform.

@perexg @kv2019i @libinyang FYI

**Comment by perexg** [comment]
I don't see any benefit to use the SOF driver for the legacy HDA hardware. The ACPI NHLT tables should not advertise DMICs or the DMI checks in snd-intel-dspcfg may be improved (add workarounds for buggy BIOSes) to ensure that the driver selection works properly.

**Comment by plbossart** [comment]
> I don't see any benefit to use the SOF driver for the legacy HDA hardware. The ACPI NHLT tables should not advertise DMICs or the DMI checks in snd-intel-dspcfg may be improved (add workarounds for buggy BIOSes) to ensure that the driver selection works properly.

Agree if the firmware is a pass-through. But the firmware could add DRC for loudness (being added now to SOF), or processing e.g. speaker protection. It's done in Windows on HDaudio platforms even on desktop skews without DMICs, so it's only a matter of time before it comes to Linux. With all the work-from-home trend, there's growing ask to put more processing that improves sound quality on speakers.

Also I don't disagree with the buggy BIOS, but when do you decide it's buggy? On Up Extreme board, the connector allows for DMICs to be exposed, but you still need to actually connect them. The BIOS can't account for this. The kernel parameter is one way of say. If the users knows for a fact that there's no dmic connected, how does it tell UCM/PulseAudio to remove this non-existent input?

**Comment by perexg** [comment]
> > I don't see any benefit to use the SOF driver for the legacy HDA hardware. The ACPI NHLT tables should not advertise DMICs or the DMI checks in snd-intel-dspcfg may be improved (add workarounds for buggy BIOSes) to ensure that the driver selection works properly.
> 
> Agree if the firmware is a pass-through. But the firmware could add DRC for loudness (being added now to SOF), or processing e.g. speaker protection. It's done in Windows on HDaudio platforms even on desktop skews without DMICs, so it's only a matter of time before it comes to Linux. With all the work-from-home trend, there's growing ask to put more processing that improves sound quality on speakers.

Ok, we are at the point where the DSP does something. We should use the config from 'HDA-Intel' tree for this case. I'll try to propose something.

> Also I don't disagree with the buggy BIOS, but when do you decide it's buggy? On Up Extreme board, the connector allows for DMICs to be exposed, but you still need to actually connect them. The BIOS can't account for this. The kernel parameter is one way of say. If the users knows for a fact that there's no dmic connected, how does it tell UCM/PulseAudio to remove this non-existent input?

The BIOS should have an option for those universal motherboards to avoid the DMIC advertisement when the user does not acknowledge the presence. So, it's BIOS thing.

Users can use 'options snd_intel_dspcfg dsp_driver=1' for the non-capable BIOS at the moment.

**Comment by perexg** [comment]
I tried to write a configuration which should handle the no dmics: https://github.com/alsa-project/alsa-ucm-conf/pull/97

**Comment by perexg** [comment]
It should be fixed in https://github.com/alsa-project/alsa-ucm-conf/pull/97 . Closing.

**Comment by lkraav** [comment]
I'm fairly certain this is exactly what I'm running into at https://github.com/thesofproject/linux/issues/1879#issuecomment-1093501408

But even with #97 in alsa-ucm-1.2.6.3, pulseaudio failed with

```
I: [pulseaudio] alsa-util.c: Error opening PCM device _ucm0001.hw:sofhdadsp,6: No such file or directory                                                                                                                                      E: [pulseaudio] module-alsa-card.c: Failed to find a working profile.                                                                                                                                                                         
```

Only after I manually deleted this device from UCM conf, everything worked.

Does #97 need further amends to also accommodate my machine?
