### ISSUE TITLE
UCM profile for the Chromebook Yoga C630.  Please add.

### ISSUE THREAD

**Issue by neil-vonholtum** [alsa-project/alsa-ucm-conf#82]
Here is the HiFi.conf file contents:

SectionVerb {
Value {
 OutputDspName "speaker_eq"
 FullySpecifiedUCM "1"
}
EnableSequence [
 cdev "hw:kblda7219max" 

 cset "name='codec1_out mo media0_in mi Switch' off"
 cset "name='codec0_out mo media0_in mi Switch' off"
 cset "name='Playback Digital Volume' 111"
 cset "name='Playback Digital Switch' 1"
 cset "name='Out DACL Mux' DAIL"
 cset "name='Out DACR Mux' DAIR"
 cset "name='Mixer Out FilterL DACL Switch' 1"
 cset "name='Mixer Out FilterR DACR Switch' 1"
 cset "name='ST Mixer Out FilterL Out FilterL Switch' 1"
 cset "name='ST Mixer Out FilterR Out FilterR Switch' 1"
 cset "name='Headphone Jack Switch' off"
 cset "name='Headset Mic Switch' off"
 cset "name='Mic Volume' 5"
 cset "name='Capture Digital Volume' 111"
 cset "name='Capture Digital Switch' 1"
 cset "name='Mixin Volume' 10"
 cset "name='Mixin Switch' 1"
 cset "name='Mixer In Mic Switch' 1"
 cset "name='Out DAIL Mux' ADC"
 cset "name='Out DAIR Mux' ADC"
 cset "name='media0_out mo codec0_in mi Switch' off"
 cset "name='media0_out mo dmic01_hifi_in mi Switch' off"
 cset "name='Pin5-Port0 Mux' 1"
 cset "name='Pin6-Port0 Mux' 2"
 cset "name='Pin7-Port0 Mux' 3"
 cset "name='Gain Ramp Rate' 1"
]
DisableSequence [
]
}

SectionDevice."Speaker".0 {
Value {
 PlaybackPCM "hw:kblda7219max,0"
}
EnableSequence [
 cdev "hw:kblda7219max"
 cset "name='codec0_out mo media0_in mi Switch' on"
 cset "name='Spk Switch' on"
]
DisableSequence [
 cdev "hw:kblda7219max"
 cset "name='codec0_out mo media0_in mi Switch' off"
 cset "name='Spk Switch' off"
]
}

SectionDevice."Headphone".0 {
Value {
 PlaybackPCM "hw:kblda7219max,0"
 MixerName "Headphone"
 JackName "kblda7219max Headset Jack"
 JackType "gpio"
 JackSwitch "2"
 OutputDspName ""
}
EnableSequence [
 cdev "hw:kblda7219max"
 cset "name='codec1_out mo media0_in mi Switch' on"
 cset "name='Headphone Jack Switch' on"
 cset "name='Headphone Switch' 1"
]
DisableSequence [
 cdev "hw:kblda7219max"
 cset "name='codec1_out mo media0_in mi Switch' off"
 cset "name='Headphone Jack Switch' off"
 cset "name='Headphone Switch' 0"
]
}

SectionDevice."Line Out".0 {
Value {
 PlaybackPCM "hw:kblda7219max,0"
 MixerName "Headphone"
 JackName "kblda7219max Headset Jack"
 JackType "gpio"
 JackSwitch "6"
 OutputDspName ""
}
EnableSequence [
 cdev "hw:kblda7219max"
 cset "name='codec1_out mo media0_in mi Switch' on"
 cset "name='Headphone Jack Switch' on"
 cset "name='Headphone Switch' 1"
]
DisableSequence [
 cdev "hw:kblda7219max"
 cset "name='codec1_out mo media0_in mi Switch' off"
 cset "name='Headphone Jack Switch' off"
 cset "name='Headphone Switch' 0"
]
}
 
SectionDevice."Internal Mic".0 {
Value {
 CapturePCM "hw:kblda7219max,3"
 CaptureChannelMap "0 1 -1 -1 -1 -1 -1 -1 -1 -1 -1"
 MaxSoftwareGain "2000"
}
EnableSequence [
 cdev "hw:kblda7219max"
 cset "name='media0_out mo dmic01_hifi_in mi Switch' on"
]
DisableSequence [
 cdev "hw:kblda7219max"
 cset "name='media0_out mo dmic01_hifi_in mi Switch' off"
]
}

SectionDevice."Mic".0 {
Value {
 CapturePCM "hw:kblda7219max,1"
 MixerName "Headset Mic"
 JackName "kblda7219max Headset Jack"
 JackType "gpio"
}
EnableSequence [
 cdev "hw:kblda7219max"
 cset "name='Headset Mic Switch' on"
 cset "name='media0_out mo codec0_in mi Switch' on"
 cset "name='Mic Switch' on"
]
DisableSequence [
 cdev "hw:kblda7219max"
 cset "name='Headset Mic Switch' off"
 cset "name='media0_out mo codec0_in mi Switch' off"
 cset "name='Mic Switch' off"
]
}

SectionDevice."HDMI1".0 {
Value {
 PlaybackPCM "hw:kblda7219max,4"
 JackName "kblda7219max HDMI/DP, pcm=4 Jack"
 JackType "gpio"
 OutputDspName ""
}
EnableSequence [
]
DisableSequence [
]
}

SectionDevice."HDMI2".0 {
Value {
 PlaybackPCM "hw:kblda7219max,5"
 JackName "kblda7219max HDMI/DP, pcm=5 Jack"
 JackType "gpio"
 OutputDspName ""
}
EnableSequence [
]
DisableSequence [
]
}

SectionDevice."HDMI3".0 {
Value {
 PlaybackPCM "hw:kblda7219max,6"
 JackName "kblda7219max HDMI/DP, pcm=6 Jack"
 JackType "gpio"
 OutputDspName ""
}
EnableSequence [
]
DisableSequence [
]
}

**Comment by perexg** [comment]
Unless updated to latest syntax, this ChromeOS configuration won't be accepted.
