### ISSUE TITLE
Bass speaker is off on yoga slim 7i 15 (Yoga Slim 7-15ITL05)

### ISSUE THREAD

**Issue by juliusvonkohout** [alsa-project/alsa-ucm-conf#83]
Alsainfo: http://alsa-project.org/db/?f=673e04313fa931831176ed3f50a9af1c9206395e

I tested with fedora 33, 34 and Ubuntu 21.04. Only the high frequency speakers at the laptop bottom are working, while the speakers above the keyboard are off. Here is a link to the laptop https://www.lenovo.com/de/de/laptops/yoga/yoga-slim-series/Yoga-Slim-7-15IIL05/p/88YGS701403

In Microsoft Windows 10 everything is fine.

In Ubuntu 21.04 i can at least change the bass speaker volume in alsamixer, but it is changing hardware master volume instead of hardware bass speaker volume.

In Feodra 33 and 34 i can not even change the bass speaker volume in alsamixer
![audiobug](https://user-images.githubusercontent.com/45896133/107797084-d3090500-6d5a-11eb-86fb-229800b546b0.png)

You can immiediatly hear, that the bass speaker above the keyboard is off
[audio.zip](https://github.com/alsa-project/alsa-ucm-conf/files/5973232/audio.zip)

There are related bugs for ALC287
The same bug on other yoga laptops https://bugzilla.kernel.org/show_bug.cgi?id=205755
Patches for the issue on other yoga Laptops https://patchwork.kernel.org/project/alsa-devel/patch/20201205051130.8122-1-hui.wang@canonical.com/

**Comment by perexg** [comment]
It's a kernel driver bug and we have already bug for the kernel driver you mentined. Closing.
