### ISSUE TITLE
rockchip/veyron sound level issues

### ISSUE THREAD

**Issue by kapouer** [alsa-project/alsa-ucm-conf#87]
Hi,

setup:
> asus c201 (speedy veyron)
> linux 5.10.28 or 5.11.13
> debian bullseye: alsa 1.2.4, asa-ucm-conf (and topology) installed, pulseaudio 14.2, gnome 3.38 on wayland

what works:
- jack input/output using headset

problems:
- speaker output is somewhat low even at 100% (feels like 50%)
- microphone is so low that it cannot detect sound (smashing the mic hole with a stick is detected but barely audible)
- last time i checked hdmi was working - i need to check again though

What can i provide ?
pulseaudio -vvvvvv ?

**Comment by perexg** [comment]
UCM is just automation for the mixer / route setup. You may use amixer / alsamixer to set the controls and report back the . The UCM configuration is  here: https://github.com/alsa-project/alsa-ucm-conf/blob/master/ucm2/Rockchip/max98090/HiFi.conf

The hw volume controls should be described, too.

**Comment by kapouer** [comment]
Right !
After playing a bit with alsamixer i found out that "DMIC Mux" should be set to "DMIC" instead of "ADC" - that fixes the issue with the internal microphone. I suppose i'll find out later for speaker output.
Should i PR the "right" settings here ?

**Comment by perexg** [comment]
Yep, it's the preferred way to fix things... Thank you.

**Comment by kapouer** [comment]
Oh ! it seems pulseaudio is ignoring "DMIC Mux" setting from alsa-ucm-conf.

**Comment by kapouer** [comment]
Oh ! it seems pulseaudio is mostly the one having issues right now. Many PR for it to better manage ucm profiles... so i'm not even sure the issue is in the ucm profile itself now. Closing.
