### ISSUE TITLE
Release tarballs ship other version, break build scripts

### ISSUE THREAD

**Issue by dvzrv** [alsa-project/alsa-ucm-conf#95]
Hi! I package this for Arch Linux.

The release tarballs on the ALSA website ship the 1.2.5 data in a directory with a differing version number:

`alsa-ucm-conf-1.2.4.81.g4884e/`

This breaks build system assumptions about the contents of these tarballs. Please provide the data in directories that match the release version.

**Comment by jpalus** [comment]
Note that similar issue affects alsa-topology-conf-1.2.5 release tarball.

**Comment by perexg** [comment]
Yes, it's a result to not push the annotated tag to the repo before the release announce to avoid fast pickups, so the release scripts for those two packages were not able to gather this information. I'll release 1.2.5.1 soon (will try to fix https://github.com/alsa-project/alsa-lib/issues/142 anyway).

**Comment by dvzrv** [comment]
Many thanks! :)

**Comment by jpalus** [comment]
@perexg I see 1.2.5.1 is out with corrected alsa-ucm-conf. Would it be possible to repackage alsa-topology-conf as well?

**Comment by perexg** [comment]
@jpalus : Done.

**Comment by jpalus** [comment]
@perexg Thanks! Just one last note, sorry for abusing this ticket -- alsa main page says latest alsa-plugins release is 1.2.2 while I believe it's 1.2.5.

**Comment by perexg** [comment]
@jpalus : Fixed, too. Thank you for your notice.
